### ISSUE TITLE
Can not read all rows about chinese utf8

### ISSUE THREAD

**Issue by myhat123** [mattn/go-oci8#10]
os.Setenv("NLS_LANG", "SIMPLIFIED CHINESE_CHINA.UTF8")

but can not read all rows about chinese utf8, it only read one normal row of chinese.

**Comment by josesanchezr** [comment]
Hi, I have a problem to convert accented characters that come when sql query. have been converted to hexadecimal and later in the code Golang we are getting the equivalent value

Table: Room
Field: description
Value: 'Cotillón'
query: select RAWTOHEX (UTL_RAW.cast_to_raw ((desciption)) from room
 

When I run the query the hexadecimal value '436F74696C6CF36E' is obtained,
trying to get the equivalent value, using hex through Golang package: hex.DecodeString (value), I get the 'Cotill�n' value
expected value 'Cotillón'

Someone can help me

**Comment by tgulacsi** [comment]
If you convert in the server (with cast_to_raw) you'll get text encoded
with server/database's charset. That's why you should force utf8 encoding
at client side.
If you really need server-side encoding, use utl_i18n package with explicit
charsets!
2015. ápr. 24. du. 6:48 ezt írta ("josesanchezr" <notifications@github.com

**Comment by josesanchezr** [comment]
The following is the code I am using to validate. I used the utl_i18n.raw_to_char function with a charset: UTF8, AL32UTF8 and WE8ISO8859P1. But I get the same result.

	package log

	import (
		"database/sql"
		"encoding/hex"
		"fmt"
		"os"
		"strings"
		"testing"

		_ "github.com/tgulacsi/goracle/godrv"
	)

	var db *sql.DB

	func Test_Encoding(t *testing.T) {

		getConnection()
		// Spanish language
		ExecQuery("SELECT 'Cotillón' FROM DUAL", 0)
		ExecQuery("select RAWTOHEX (UTL_RAW.cast_to_raw ('Cotillón')) FROM DUAL", 1)

		// Russian language
		ExecQuery("SELECT 'Комплекс, 4 дня.' FROM DUAL", 0)
		ExecQuery("select RAWTOHEX (UTL_RAW.cast_to_raw ('Комплекс, 4 дня.')) FROM DUAL", 1)
		ExecQuery("select RAWTOHEX (UTL_RAW.cast_to_raw (utl_i18n.raw_to_char(utl_raw.cast_to_raw('Комплекс, 4 дня.'), 'UTF8'))) FROM DUAL", 1)
		ExecQuery("select RAWTOHEX (UTL_RAW.cast_to_raw (utl_i18n.raw_to_char(utl_raw.cast_to_raw('Комплекс, 4 дня.'), 'WE8ISO8859P1'))) FROM DUAL", 1)	
		ExecQuery("select RAWTOHEX (UTL_RAW.cast_to_raw (utl_i18n.raw_to_char(utl_raw.cast_to_raw('Комплекс, 4 дня.'), 'AL32UTF8'))) FROM DUAL", 1)	

		closeCon()
	}

	func getConnection() {
		var err error
		db, err = sql.Open("goracle", "") //your connection db
		if err != nil {
			fmt.Println(err)
			return
		}
	}

	func closeCon() {
		db.Close()
	}

	func ExecQuery(query string, tipo int) {
		os.Setenv("NLS_LANG", "AMERICAN_AMERICA.AL32UTF8")

		rows, err := db.Query(query)
		if err != nil {
			fmt.Println(err)
			return
		}

		if tipo == 0 {
			ObtainNormalData(rows)
		} else {
			ObtainHexData(rows)
		}
		rows.Close()

	}

	func ObtainNormalData(rows *sql.Rows) {
		for rows.Next() {
			var descripcion string
			rows.Scan(&descripcion)
			fmt.Printf("Descripcion %s \n", descripcion)
		}
	}

	func ObtainHexData(rows *sql.Rows) {
		for rows.Next() {
			var descripcion string
			rows.Scan(&descripcion)
			fmt.Println("hex", descripcion)
			dataDescription, _ := hex.DecodeString(descripcion)
			fmt.Printf("Descripcion %s \n", dataDescription)
			fmt.Println("Descripcion2-utf8", toUtf8(dataDescription))
		}
	}

	func toUtf8(iso8859_1_buf []byte) string {
		buf := make([]rune, len(iso8859_1_buf))
		for i, b := range iso8859_1_buf {
			buf[i] = rune(b)
		}
		return string(buf)
	}

**Comment by tgulacsi** [comment]
Hey hey hey!

1. this is go-oci8, but I see you use github.com/tgulacsi/goracle/godrv, which sets NLS_LANG right before initializing the OCI library, iff it is not set already, or not for AL32UTF8.
2. My lib has moved to gopkg.in/goracle.v1 and has some small fixes, which may or may not help here.

3. the main culprit: ExecQuery("select RAWTOHEX (UTL_RAW.cast_to_raw ('Комплекс, 4 дня.')) FROM DUAL", 1) - here you're sending some UTF-8 encoded query string to Oracle, ask it to CAST it to raw (with UNSPECIFIED encoding!), then spit it out as HEX. I don't see the output HEX, so don't know, but what is the DB's native charset?
You should log these strings without manipulation and with RAWTOHEX (UTL_RAW.cast_to_raw(x)) at the DB side, too to see what the DB gets.

**Comment by josesanchezr** [comment]
The following code is corrected. But still dating the same mistake with caractesres that have accents or are in Russian.

	package encode

	import (
		"database/sql"
		"encoding/hex"
		"fmt"
		"os"
		"testing"

		_ "gopkg.in/goracle.v1"
	)

	var db *sql.DB
	var descripcion string

	func Test_Encoding(t *testing.T) {

		getConnection()

		// validates Spanish language
		ExecQuery("SELECT 'Cotillón' AS NAME FROM DUAL", 0)
		if descripcion != "Cotillón" {
			t.Errorf("Error: expected [Cotillón] - obtained [%s] \n", descripcion)
		}

		ExecQuery("SELECT RAWTOHEX(UTL_RAW.cast_to_raw('Cotillón')) AS NAME FROM DUAL", 1)
		if descripcion != "Cotillón" {
			t.Errorf("Error: expected [Cotillón] - obtained [%s] \n", descripcion)
		}

		ExecQuery("SELECT RAWTOHEX(UTL_I18N.STRING_TO_RAW('Cotillón','UTF8')) AS NAME FROM DUAL", 1)
		if descripcion != "Cotillón" {
			t.Errorf("Error: expected [Cotillón] - obtained [%s] \n", descripcion)
		}

		ExecQuery("SELECT RAWTOHEX(UTL_I18N.STRING_TO_RAW('Cotillón','WE8ISO8859P1')) AS NAME FROM DUAL", 1)
		if descripcion != "Cotillón" {
			t.Errorf("Error: expected [Cotillón] - obtained [%s] \n", descripcion)
		}

		// validates Russian language
		ExecQuery("SELECT '????????, 4 ???.' AS NAME FROM DUAL", 0)
		if descripcion != "????????, 4 ???." {
			t.Errorf("Error: expected [????????, 4 ???.] - obtained [%s] \n", descripcion)
		}

		ExecQuery("SELECT RAWTOHEX(UTL_RAW.cast_to_raw('????????, 4 ???.')) AS NAME FROM DUAL", 1)
		if descripcion != "????????, 4 ???." {
			t.Errorf("Error: expected [????????, 4 ???.] - obtained [%s] \n", descripcion)
		}

		ExecQuery("SELECT RAWTOHEX(UTL_I18N.STRING_TO_RAW('????????, 4 ???.','UTF8')) AS NAME FROM DUAL", 1)
		if descripcion != "????????, 4 ???." {
			t.Errorf("Error: expected [????????, 4 ???.] - obtained [%s] \n", descripcion)
		}

		ExecQuery("SELECT RAWTOHEX(UTL_I18N.STRING_TO_RAW('????????, 4 ???.','WE8ISO8859P1')) AS NAME FROM DUAL", 1)
		if descripcion != "????????, 4 ???." {
			t.Errorf("Error: expected [????????, 4 ???.] - obtained [%s] \n", descripcion)
		}

		closeConnection()
	}

	func getConnection() {
		var err error
		db, err = sql.Open("goracle", "user/passwd@server:port/database")
		if err != nil {
			fmt.Println(err)
		}
	}

	func closeConnection() {
		db.Close()
	}

	func ExecQuery(query string, tipo int) {
		os.Setenv("NLS_LANG", "AMERICAN_AMERICA.WE8ISO8859P1")

		rows, err := db.Query(query)
		if err != nil {
			fmt.Println(err)
		}

		if tipo == 0 {
			ObtainNormalData(rows)
		} else {
			ObtainHexData(rows)
		}
		rows.Close()
	}

	func ObtainNormalData(rows *sql.Rows) string {

		for rows.Next() {
			rows.Scan(&descripcion)
			fmt.Printf("Normal Descripcion %s \n", descripcion)
		}
		return descripcion
	}

	func ObtainHexData(rows *sql.Rows) string {
		for rows.Next() {
			var dataDescription string
			rows.Scan(&dataDescription)
			descripcionHex, _ := hex.DecodeString(dataDescription)
			fmt.Printf("Hex Descripcion %s \n", descripcionHex)
			descripcion = string(descripcionHex)
		}

		return descripcion
	}

thanks for help me

**Comment by tgulacsi** [comment]
What is the exact output? What is the result of server-side logging (some
insert into t_log ... Select * from t_log...)?
2015. ápr. 28. 2:03 ezt írta ("josesanchezr" <notifications@github.com>):

**Comment by josesanchezr** [comment]
The result of server-side is, with Oracle SQL Developer tool:

	SELECT 'Cotillón' AS NAME FROM DUAL;
	Result: Cotillón
	SELECT RAWTOHEX(UTL_RAW.cast_to_raw('Cotillón')) AS NAME FROM DUAL;
	Result: 436F74696C6CF36E
	SELECT RAWTOHEX(UTL_I18N.STRING_TO_RAW('Cotillón','UTF8')) AS NAME FROM DUAL
	Result: 436F74696C6CC3B36E
	SELECT RAWTOHEX(UTL_I18N.STRING_TO_RAW('Cotillón','WE8ISO8859P1')) AS NAME FROM DUAL
	Result: 436F74696C6CF36E

	SELECT 'Комплекс, 4 дня.' AS NAME FROM DUAL
	Result: ¿¿¿¿¿¿¿¿, 4 ¿¿¿.
	SELECT RAWTOHEX(UTL_RAW.cast_to_raw('Комплекс, 4 дня.')) AS NAME FROM DUAL
	Result: BFBFBFBFBFBFBFBF2C203420BFBFBF2E
	SELECT RAWTOHEX(UTL_I18N.STRING_TO_RAW('Комплекс, 4 дня.','UTF8')) AS NAME FROM DUAL
	Result: C2BFC2BFC2BFC2BFC2BFC2BFC2BFC2BF2C203420C2BFC2BFC2BF2E
	SELECT RAWTOHEX(UTL_I18N.STRING_TO_RAW('Комплекс, 4 дня.','WE8ISO8859P1')) AS NAME FROM DUAL
	Result: BFBFBFBFBFBFBFBF2C203420BFBFBF2E




The result of client-side is:

	Normal Descripcion Cotillón
	Hex Descripcion Cotill▒n
	Hex Descripcion Cotillón
	Hex Descripcion Cotill▒n
	Normal Descripcion ¿¿¿¿¿¿¿¿, 4 ¿¿¿.
	Hex Descripcion ▒▒▒▒▒▒▒▒, 4 ▒▒▒.
	Hex Descripcion ¿¿¿¿¿¿¿¿, 4 ¿¿¿.
	Hex Descripcion ▒▒▒▒▒▒▒▒, 4 ▒▒▒.
	--- FAIL: Test_Encoding (0.60s)
	        encode_test.go:53: Error: expected [Cotillón] - obtained [Cotill▒n]
	        encode_test.go:63: Error: expected [Cotillón] - obtained [Cotill▒n]
	        encode_test.go:69: Error: expected [Комплекс, 4 дня.] - obtained [¿¿¿¿¿¿¿¿, 4 ¿¿¿.]
	        encode_test.go:74: Error: expected [Комплекс, 4 дня.] - obtained [▒▒▒▒▒▒▒▒, 4 ▒▒▒.]
	        encode_test.go:79: Error: expected [Комплекс, 4 дня.] - obtained [¿¿¿¿¿¿¿¿, 4 ¿¿¿.]
	        encode_test.go:84: Error: expected [Комплекс, 4 дня.] - obtained [▒▒▒▒▒▒▒▒, 4 ▒▒▒.]
	FAIL
	exit status 1

thanks for help me

**Comment by tgulacsi** [comment]
How can the client-side Hex result be no hex???
Please INSERT INTO some table, then SELECT from it. Both the string, and
the hex value, both directions.

Start with the new cs_test.go

2015-04-28 16:48 GMT+02:00 josesanchezr <notifications@github.com>:

**Comment by MichaelS11** [comment]
Is this still an issue?

**Comment by MichaelS11** [comment]
@mattn Close this? Original issue owner has not responded since first opening.

**Comment by mattn** [comment]
Please reopen you still have issue and it is related on go-oci8.
