### ISSUE TITLE
sql: database is closed

### ISSUE THREAD

**Issue by mimzychou** [mattn/go-oci8#100]
what dose it mean?

**Comment by mimzychou** [comment]
my config code:
oracleconfig := &Config{
        driver: "oci8",
        config: "qrtz/karakal@ceshi119",
        sqls:   []string{`select * from ZM_PRJECT`},
        parms:  nil,
    }

**Comment by mimzychou** [comment]
mysql config code:
oracleconfig := &Config{
        driver: "oci8",
        config: "hehe/hehe@ceshi119",
        sqls:   []string{`select * from ZM_PRJECT`},
        parms:  nil,
    }

**Comment by mimzychou** [comment]
mysql config code:
`oracleconfig := &Config{
driver: "oci8",
config: "hehe/hehe@ceshi119",
sqls: []string{select * from ZM_PRJECT},
parms: nil,
}`

**Comment by mattn** [comment]
where is a whole source code?

**Comment by MichaelS11** [comment]
@mattn Close this?

**Comment by mattn** [comment]
please reopen if you still have this issue.
