### ISSUE TITLE
Could you help to check the stuck issue?  when it got high concurrent requests, sometimes the issue will happen

### ISSUE THREAD

**Issue by haiylin** [mattn/go-oci8#105]
goroutine 190888 [syscall, locked to thread]:
plug-in/go-oci8._Cfunc_WrapOCILogon(0x7f9827c2b5f0, 0x7f9805b2a980, 0x7f9827745a30, 0x7f9800000008, 0x7f98250f8cc0, 0x9, 0x7f9826ec3ed0, 0xc200000006, 0x0, 0x0)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/plug-in/go-oci8/:271 +0x63
plug-in/go-oci8.(_OCI8Driver).Open(0xe6abb8, 0xc20803ad57, 0x19, 0x0, 0x0, 0x0, 0x0)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/plug-in/go-oci8/oci8.go:547 +0x5cd
database/sql.(_DB).conn(0xc213fa9e00, 0x2, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:664 +0x506
database/sql.(_DB).Ping(0xc213fa9e00, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:462 +0x3a
common.(_DbPool).GetConn(0xc20803b350, 0x0, 0x0, 0x0)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/common/public.go:167 +0x2ad
dao/siteDao.GetPoolForCluster(0xc20d27254c, 0x2, 0x0, 0x0, 0x0, 0x0)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/dao/siteDao/dsGetSiteAPI.go:341 +0xa1
controllers.DataService.GetSiteInfo(0xc20d6eca20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc20fc19680, 0x7, ...)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/controllers/apiMain.go:894 +0x4cb
controllers.(_DataService).GetSiteInfo(0xc20cea5980, 0xc20fc19680, 0x7, 0xc20fc196a0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        <autogenerated>:40 +0x135
reflect.Value.call(0x930260, 0xc20cea5980, 0x4153, 0x933ca0, 0x4, 0xc20d6ecae0, 0x4, 0x4, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x930260, 0xc20cea5980, 0x4153, 0xc20d6ecae0, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:296 +0xbc
plug-in/gorest.prepareServe(0xc20d6eca20, 0x960c70, 0xb, 0x935760, 0x3, 0xc208053901, 0x4d, 0x0, 0x0, 0xc208053901, ...)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/plug-in/gorest/reflect.go:391 +0x16aa
plug-in/gorest.manager.ServeHTTP(0xc208138d20, 0xc208138d50, 0x7f9d70083b70, 0xc21312fe80, 0xc20e1a89c0)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/plug-in/gorest/gorest.go:215 +0x638
plug-in/gorest.(_manager).ServeHTTP(0xc2081c6310, 0x7f9d70083b70, 0xc21312fe80, 0xc20e1a89c0)
        <autogenerated>:6 +0xbd
common.(_ApacheLoggingHandler).ServeHTTP(0xc208147bc0, 0x7f9d854e5138, 0xc20bf73180, 0xc20e1a89c0)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/common/handleInitail.go:82 +0x294
common.(_authenticationFilter).ServeHTTP(0xc2081b9cb0, 0x7f9d854e5138, 0xc20bf73180, 0xc20e1a89c0)
        /root/jenkins/workspace/1-Portal/CMSE-DataServices/src/common/authenticationFilter.go:40 +0x210
net/http.(_ServeMux).ServeHTTP(0xc20803ba70, 0x7f9d854e5138, 0xc20bf73180, 0xc20e1a89c0)
        /usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc2081c42a0, 0x7f9d854e5138, 0xc20bf73180, 0xc20e1a89c0)
        /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(_conn).serve(0xc2091a6500)
        /usr/local/go/src/net/http/server.go:1204 +0xb57

**Comment by haiylin** [comment]
I have used the latest version.

**Comment by djadala** [comment]
what is the error ?

**Comment by MichaelS11** [comment]
Test this again?

**Comment by MichaelS11** [comment]
@mattn Close this?
