### ISSUE TITLE
go1.8: support for additional features

### ISSUE THREAD

**Issue by kardianos** [mattn/go-oci8#116]
Many new important features will land in go1.8. Please see document:
https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit?usp=sharing for the full list.

Because these features are new we want drivers to implement them before they are released. Ideally they should be implemented by 2016-12-12 to allow for any driver provided feedback from implementation if necessary.

**Comment by devarsh** [comment]
What is the status of context support with this library, are cancellable queries supported now.

**Comment by mattn** [comment]
See https://docs.google.com/spreadsheets/d/1y7AzkFNPeTBado0xJJipB5MpWlcqylQg410Q5wHz2Ew/edit?usp=sharing

**Comment by devarsh** [comment]
Will be needing read access to the document.

Thanks.

**Comment by mattn** [comment]
Sorry, https://docs.google.com/spreadsheets/d/1y7AzkFNPeTBado0xJJipB5MpWlcqylQg410Q5wHz2Ew/pubhtml

**Comment by jeremija** [comment]
@mattn is it currently possible to call stored procedures that return a single result set? can i help in any way with the implementation of multiple result sets?

**Comment by mattn** [comment]
No. Go's database/sql doesn't support exchanging values via stored proc.

**Comment by kardianos** [comment]
@mattn What is blocking support for this in database/sql?

**Comment by jeremija** [comment]
@mattn so is this issue just about being to extract results from multiple queries in a single statement?

**Comment by mattn** [comment]
@jeremija multiple result set is just like union. not for stored proc.

**Comment by mattn** [comment]
@kardianos we can use stored procedure if it doesn't have out parameter. But not if it have out parameter, 

https://github.com/mattn/go-oci8/issues/55

**Comment by MichaelS11** [comment]
Is this now good with adding of SQL out? Can this be closed?

**Comment by mattn** [comment]
yah, closing.
