### ISSUE TITLE
ORA-01000 error occurs after 2016-11-09 version

### ISSUE THREAD

**Issue by linlexing** [mattn/go-oci8#120]
When I use the latest version, found OPEN_CURSORS continues to increase, last ORA-01000 error occurs, switch back to the previous version did not find this problem (version: 2016-10-14)
```go
package main

import (
	"time"

	"database/sql"

	_ "github.com/mattn/go-oci8"
)

func main() {
	db, err := sql.Open("oci8", "***/***@localhost:1521/orcl")
	if err != nil {
		panic(err)
	}
	for i := 0; i < 1000; i++ {
		d := 0
		strSql := "select 1 from dual"
		rows, err := db.Query(strSql)

		if err != nil {
			panic(err)
		}
		rows.Next()
		err = rows.Scan(&d)
		if err != nil {
			panic(err)
		} else {
			rows.Close()
			print(d)
		}
		time.Sleep(time.Second * 3)
	}
	defer db.Close()
}

```

**Comment by mattn** [comment]
I will look into it in later. But could you please try to comment-out this part to make sure this fix?

https://github.com/mattn/go-oci8/blob/master/oci8.go#L537-L546

**Comment by bwinterton** [comment]
I am experiencing the exact same issue. Long lived connection is open, but all result sets are closed (with the exception of QueryRow since the *Row returned does not need to be closed per the documentation)
