### ISSUE TITLE
need help on ORA-01805

### ISSUE THREAD

**Issue by QthCN** [mattn/go-oci8#124]
I met ORA-01805 when I query a table with "TIMESTAMP(6) WITH TIME ZONE" column. I find some suggestions from "https://github.com/kubo/ruby-oci8/issues/28", but the solution in this link is about ruby-oci8. Does go-oci8 support something like "OCI8::BindType::Mapping[Time] = OCI8::BindType::LocalTime" metioned in that link? I can't find the similar thing in go-oci8's document. Thank you.

**Comment by hurrycaine** [comment]
I am using ruby-oci8 but none of the fixes in https://github.com/kubo/ruby-oci8/issues/28 helped me either.
It is not well documented but you can set an environment variable ORA_TZFILE .

In my example we had updated the oracle server but not the timezone file (11). We used the new oracle instant client timezone file 14) and oci8 and it failed. 
I set the variable back to 11 and it worked.
ORA_TZFILE=%ORACLE_HOME%\oracore\zoneinfo\timezlrg_11.dat

hope this helps!

**Comment by MichaelS11** [comment]
@mattn Close this?
