### ISSUE TITLE
need help on 'LONG' type

### ISSUE THREAD

**Issue by QthCN** [mattn/go-oci8#126]
Hi mattn, 

When I use go-oci8 to query all_tab_columns.DATA_DEFAULT(which is a "LONG" DATA TYPE), I get error: ORA-01406. I guess that go-oci8 didn't get the right size of 'LONG' type when the actual size is larger than go-oci8 think. In other language oracle packages, for example in Python cx_Oracle, I find that they will handle LONG/LOB differently with normal data types. 

Could you help to check if go-oci8 is doing correct on 'LONG' type? Thanks very much.

**Comment by mattn** [comment]
could you please show me whole query?

**Comment by QthCN** [comment]
thanks :)
