### ISSUE TITLE
mac faild.

### ISSUE THREAD

**Issue by ahlzhang** [mattn/go-oci8#128]
mac installed faild.
oci8 put /usr/lib/pkgconfig/ 
prefix=$GOPATH/src/instantclient_12_1
prefixdir=$GOPATH/src/instantclient_12_1/sdk
exec_prefix=${prefix}
libdir=${prefix}
includedir=${prefix}/include

Name: OCI
Description: Oracle Database Engine
Version: 11.2
Libs: -L${libdir} -lclntsh
Libs.private:
Cflags: -I${includedir}
 
go get github.com/mattn/go-oci8
# github.com/mattn/go-oci8
go-oci8/oci8.go:4:10: fatal error: 'oci.h' file not found
#include <oci.h>
^
1 error generated

My English is not so good。sorry

**Comment by mattn** [comment]
This is not an issue of go-oci8. please fix your environment.

**Comment by ahlzhang** [comment]
Do you have a Mac OSX of the configuration method?

**Comment by ahlzhang** [comment]
ok.thx.I'm try agan.

**Comment by ahlzhang** [comment]
hi mattn.

Present problem:

 go get github.com/mattn/go-oci8
# github.com/mattn/go-oci8
./oci8.go:201:44: warning: passing 'char [9]' to parameter of type 'const oratext *' (aka 'const unsigned char *') converts between pointers to integer types with different sign [-Wpointer-sign]
/Users/zhangbob/go/src/instantclient_12_1/sdk/include/ociap.h:8549:56: note: passing argument to parameter 'name' here
# github.com/mattn/go-oci8
ld: library not found for -lclntsh
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mattn** [comment]
still problem of your environment.

>ld: library not found for -lclntsh

**Comment by cjbj** [comment]
Re linking, you need to use Oracle Instant Client 12.1 and force rpath to work with OS X's SIP changes.  Something like node-oracledb does: https://github.com/oracle/node-oracledb/blob/v1.11.0/binding.gyp#L54

**Comment by ahlzhang** [comment]
Already closed OS X'SIP

**Comment by ahlzhang** [comment]
ok
Present problem:
go-oci8$:go get github.com/mattn/go-oci8
# github.com/mattn/go-oci8
./oci8.go:201:44: warning: passing 'char [9]' to parameter of type 'const oratext *' (aka 'const unsigned char *') converts between pointers to integer types with different sign [-Wpointer-sign]
/usr/local/lib/instantclient_12_1/sdk/include/ociap.h:8549:56: note: passing argument to parameter 'name' here

Did the success?

**Comment by mattn** [comment]
maybe success if `echo $?` return 0.

**Comment by ahlzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/16819060/20784321/78bfe8b0-b7d4-11e6-9a8f-e069884f4013.png)

**Comment by ahlzhang** [comment]
I do "go get github.com/mattn/go-oci8" in go-oci8 it builds fine
but when I try to test an application that uses go-oci8 I get this:

_dyld: Library not loaded: @rpath/libclntsh.dylib.12.1
  Referenced from: /var/folders/cd/jfwb6lqd2yb4zjjn1mzgn95m0000gn/T/go-build179942163/command-line-arguments/_obj/exe/main
  Reason: image not found
signal: abort trap_

**Comment by mattn** [comment]
you can set LD_LIBRARY_PATH to the directory.

**Comment by ahlzhang** [comment]
yes,I'm set

![image](https://cloud.githubusercontent.com/assets/16819060/20788670/b3ca0d74-b7ec-11e6-95cf-f6ed5c3f9137.png)

**Comment by mattn** [comment]
Sorry, I don't have OSX. Anyone, could you please help?

**Comment by ahlzhang** [comment]
ok,thans your help!

**Comment by ahlzhang** [comment]
Thanks! I consider this issue resolved.

**Comment by mattn** [comment]
If you fixes with complexily way, please note on this issue for others.

**Comment by cjbj** [comment]
> you can set LD_LIBRARY_PATH to the directory.

This no longer works in current OS X versions due to SIP
