### ISSUE TITLE
ORA-01000: maximum open cursors exceeded

### ISSUE THREAD

**Issue by ClarksonCJ** [mattn/go-oci8#131]
When performing large numbers of inserts via db.Exec the above error is thrown after 298 executions (on Vagrant VM running Oracle XE 11.2)
Reproduction Code available [here](https://gist.github.com/ClarksonCJ/86f03e08f9298e8cad1edaed718a78ce)

**Comment by mattn** [comment]
Is this closable by #130 ?

**Comment by ClarksonCJ** [comment]
Yup. 130 should close the issue.

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Jan 6, 2017 at 4:48 PM +0000, "mattn" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this closable by #130<https://github.com/mattn/go-oci8/pull/130> ?

**Comment by Morlinest** [comment]
@mattn I still have this problem, 300+ selects:
ORA-01000: maximum open cursors exceeded

Using simple for loop, its same with Query() and Prepare()

I have latest version of go-oci8, sqlx, go version go1.8.1 windows/386, windows 10

**Comment by mattn** [comment]
please show me your code.

On 4/28/17, Morlinest <notifications@github.com> wrote:
> @mattn I still have this problem, 300+ selects:
> ORA-01000: maximum open cursors exceeded
>
> Using simple for loop, its same with Query() and Prepare()
>
> I have latest version of go-oci8, sqlx, go version go1.8.1 windows/386,
> windows 10
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/go-oci8/issues/131#issuecomment-297969173


-- 
- Yasuhiro Matsumoto

**Comment by Morlinest** [comment]
Sample code, replaced connection string
```
package main

import (
	"fmt"
	"log"
	"math/big"
	"time"

	"github.com/jmoiron/sqlx"
	_ "github.com/mattn/go-oci8"
)

func main() {
	db, errConnect := sqlx.Open("oci8", "<my_connection_string>")
	if errConnect != nil {
		fmt.Println(errConnect)
		return
	}
	defer db.Close()

	start := time.Now()
	r := new(big.Int)
	fmt.Println(r.Binomial(1000, 10))
	for i := 1; i <= 350; i++ {
		runSelect3(db, i)
	}
	elapsed := time.Since(start)
	log.Printf("Binomial took %s", elapsed)
}

func runSelect3(db *sqlx.DB, i int) {
	var c int
	stmt, err := db.Preparex("SELECT 1 FROM Dual")
	if err != nil {
		fmt.Printf("err prepare (%d): %s\n", i, err)
	}
	err = stmt.Get(&c)
	if err != nil {
		fmt.Printf("err (%d): %s\n", i, err)
	} else {
		fmt.Printf("Result: %+v\n", c)
	}
}
```

**Comment by ClarksonCJ** [comment]
@Morlinest your runSelect3 is not closing the prepared statement. add a ```defer stmt.close()``` after your statement instantiation

**Comment by Morlinest** [comment]
@ClarksonCJ thx, this works (also moving prepared section out of loop). But this is just one example (i was trying with Query, QueryRow, QueryRowx...), what about this functions (in `runSelect5` I am using stdlib database/sql):

```
func runSelect(db *sqlx.DB, i int) {
	var c int
	row := db.QueryRowx("SELECT 1 FROM Dual")

	err := row.Scan(&c)
	if err != nil {
		fmt.Printf("err (%d): %s\n", i, err)
	} else {
		fmt.Printf("Result: %+v\n", c)
	}
}

func runSelect5(db *sql.DB, i int) {
	var c int
	row := db.QueryRow("SELECT 1 FROM Dual")
	err := row.Scan(&c)
	if err != nil {
		fmt.Printf("err (%d): %s\n", i, err)
	} else {
		fmt.Printf("Result: %+v\n", c)
	}
}
```

Maybe I am doing something bad... Thx for help

**Comment by ClarksonCJ** [comment]
Prepare a statement and then execute the query, rather than just executing the query.

**Comment by mattn** [comment]
You didn't Close() stmt.

**Comment by Morlinest** [comment]
OK, thanks guys for help. I will be using only prepared statements, call stmt.Close() and it should be OK. Query methods do not work correctly.

**Comment by mattn** [comment]
What do you mean `do not work correctly` ? still have issue?

**Comment by Morlinest** [comment]
Yes, look at my `runSelect` (using sqlx) and `runSelect5` (using database/sql) functions. There is nothing to close and cant run them more than 299 times.
