### ISSUE TITLE
stmt resource   close  question

### ISSUE THREAD

**Issue by zhuyunsheng** [mattn/go-oci8#133]
func (c *OCI8Conn) Exec(query string, args []driver.Value) (driver.Result, error) {
	list := make([]namedValue, len(args))
	for i, v := range args {
		list[i] = namedValue{
			Ordinal: i + 1,
			Value:   v,
		}
	}
	return c.exec(context.Background(), query, list)
}

func (c *OCI8Conn) exec(ctx context.Context, query string, args []namedValue) (driver.Result, error) {
	s, err := c.prepare(ctx, query)
	if err != nil {
		return nil, err
	}
	res, err := s.(*OCI8Stmt).exec(ctx, args)
	if err != nil && err != driver.ErrSkip {
		s.Close()
		return nil, err
	}
	s.Close()
	return res, nil
}

The top of the exec method does not close the stmt resources, where I should perform the shutdown operation? Thanks!

**Comment by mattn** [comment]
It's closed by GC.

https://github.com/mattn/go-oci8/blob/master/oci8.go#L747

**Comment by MichaelS11** [comment]
@mattn 
Has this now been fixed?
