### ISSUE TITLE
Getting realtime messages from Logmnr

### ISSUE THREAD

**Issue by lovromazgon** [mattn/go-oci8#134]
I want to use a Go program to query the [LogMiner](https://docs.oracle.com/cd/B28359_01/server.111/b28319/logminer.htm#i1005553) and get changes in the database in real-time. The problem is, that I get results from v$logmnr_contents only after ~10 rows are added, which means it is not real-time anymore.
I suspect that it has something to do with the number of roundtrips and [fetch size](https://docs.oracle.com/cd/E11882_01/java.112/e16548/resltset.htm#JJDBC28621), since you have to set arraysize to 1 in sqlplus to be able to get notified about changes in real-time.

So is there any way to set the fetch size in the driver, or do you know another way to solve my problem? Thanks!

**Comment by mattn** [comment]
This is currently todo. https://github.com/mattn/go-oci8/blob/fa72a301ba78be408c8d4fd681d88cbb1feb9bbd/README.md#todo

**Comment by MichaelS11** [comment]
The link provided was for JDBC driver fetch size. Need to translate what that means in OCI driver.
Is fetch size the same as OCI_ATTR_PREFETCH_ROWS size?

https://docs.oracle.com/cd/A58617_01/server.804/a58234/vol2_han.htm#427637

If so, that can be set with `prefetch_rows`:

https://godoc.org/github.com/mattn/go-oci8#ParseDSN

**Comment by MichaelS11** [comment]
Think this is fixed, please let us know if it is not.
