### ISSUE TITLE
warning when compiling this package

### ISSUE THREAD

**Issue by devarsh** [mattn/go-oci8#135]
Getting this warning when I include oci8 driver, everything is working fine, but wanted to make sure if I messed up with the installation process, or is it a common warning, with this driver

```console
# github.com/mattn/go-oci8
../../mattn/go-oci8/oci8.go:201:44: warning: passing 'char [9]' to parameter of type 'const oratext *' (aka 'const unsigned char *') converts between pointers to integer types with different sign [-Wpointer-sign]
/Users/acuteinfo/instantclient_12_1/sdk/include/ociap.h:8549:56: note: passing argument to parameter 'name' here
```

**go version**: go1.7.4 darwin/amd64
**os** : OS X EL Capitan
**Oracle Driver**: instantclient_12_1

**Comment by mattn** [comment]
Related issue https://github.com/mattn/go-oci8/issues/72

**Comment by MichaelS11** [comment]
@mattn Close this?
