### ISSUE TITLE
Unable to install go-oci8 on windows 64 bits

### ISSUE THREAD

**Issue by mahaben** [mattn/go-oci8#137]
I get this errors:

```
# github.com/mattn/go-oci8
In file included from c:/oraclexe/app/oracle/product/11.2.0/server/oci/include/o
ci.h:537:0,
                 from ..\..\..\github.com\mattn\go-oci8\oci8.go:4:
c:/oraclexe/app/oracle/product/11.2.0/server/oci/include/oratypes.h:235:25: erro
r: expected '=', ',', ';', 'asm' or '__attribute__' before 'ubig_ora'
 typedef unsigned _int64 ubig_ora;
                         ^
c:/oraclexe/app/oracle/product/11.2.0/server/oci/include/oratypes.h:236:25: erro
r: expected '=', ',', ';', 'asm' or '__attribute__' before 'sbig_ora'
 typedef   signed _int64 sbig_ora;
                         ^
In file included from c:/oraclexe/app/oracle/product/11.2.0/server/oci/include/o
ci.h:3029:0,
                 from ..\..\..\github.com\mattn\go-oci8\oci8.go:4:
c:/oraclexe/app/oracle/product/11.2.0/server/oci/include/ociap.h:7452:40: error:
 unknown type name 'ubig_ora'
                         OraText *path, ubig_ora *lenp  );
                                        ^
c:/oraclexe/app/oracle/product/11.2.0/server/oci/include/ociap.h:7464:36: error:
 unknown type name 'ubig_ora'
                      uword origin, ubig_ora offset, sb1 dir );
                                    ^
c:/oraclexe/app/oracle/product/11.2.0/server/oci/include/ociap.h:8271:23: error:
 unknown type name 'sbig_ora'
                       sbig_ora bufferLength, sbig_ora *returnLength,
                       ^
c:/oraclexe/app/oracle/product/11.2.0/server/oci/include/ociap.h:8271:46: error:
 unknown type name 'sbig_ora'
                       sbig_ora bufferLength, sbig_ora *returnLength,
                                              
```

Any idea how to solve it?

Thanks in advance,

**Comment by mattn** [comment]
What compiler do you use? gcc? 32/64bit? And your OS.

**Comment by mahaben** [comment]
Thanks for your reply. I'm using TDM-GCC 64 bit and my OS is windows 7 64 bit. I've also installed oracle instant client 64 bit. Any idea?

Thanks,

**Comment by mattn** [comment]
Can you try this patch?

```c
diff --git a/oci8.go b/oci8.go
index 6b28b4b..20f3951 100644
--- a/oci8.go
+++ b/oci8.go
@@ -1,10 +1,10 @@
 package oci8
 
 /*
-#include <oci.h>
 #include <stdlib.h>
 #include <string.h>
 #include <stdint.h>
+#include <oci.h>
 
 #cgo pkg-config: oci8
 
```

**Comment by mahaben** [comment]
I applied the patch but still getting the same errors. Note that I installed it on linux and windows 32 and the installation went fine.

**Comment by mattn** [comment]
AFAICS, it seems compiler issue. your compiler seems not have `_int64`.

**Comment by mahaben** [comment]
I've tried many versions of TDM without no result. In this issue: https://github.com/mattn/go-oci8/issues/79

It is indicated that adding #define _int64 __int64 on oratypes.h may resolve the problem. But then i get the following error: c:/oraclexe/app/oracle/product/11.2.0/server/oci/lib/msvc/oci.lib: error adding
symbols: File in wrong format
collect2.exe: error: ld returned 1 exit status

**Comment by mattn** [comment]
I don't met this issue until now. I'm using gcc(mingw not msys) bundled in msys2

**Comment by julianzhu1117** [comment]
i have meet the same errors

**Comment by X3STeNLiTE** [comment]
`GCC` doesn't recognized msvc compiled library you have to convert to `.a` first

I'm just successes build on yesterday with this instruction

[Install go-oci8 on Windows 64](https://gist.github.com/X3STeNLiTE/8f60a1c431fb0623af59b2a1c6248786)

**Comment by hljlgj** [comment]
i have the same problem

**Comment by amiracam** [comment]
I'm getting the same issue using the compiler from msys2 as well, here's the stack:

# github.com/mattn/go-oci8
In file included from C:\instantclient_11_2\sdk\include/oci.h:541:0,
                 from C:\Users\amira\go\src\github.com\mattn\go-oci8\oci8.go:4:
C:\instantclient_11_2\sdk\include/oratypes.h:236:25: error: expected '=', ',', ';', 'asm' or '__attribut__' before 'ubig_ora'
 typedef unsigned _int64 ubig_ora;
                         ^~~~~~~~
C:\instantclient_11_2\sdk\include/oratypes.h:237:25: error: expected '=', ',', ';', 'asm' or '__attribut__' before 'sbig_ora'
 typedef   signed _int64 sbig_ora;
                         ^~~~~~~~
In file included from C:\instantclient_11_2\sdk\include/oci.h:3045:0,
                 from C:\Users\amira\go\src\github.com\mattn\go-oci8\oci8.go:4:
C:\instantclient_11_2\sdk\include/ociap.h:7459:40: error: unknown type name 'ubig_ora'
                         OraText *path, ubig_ora *lenp  );
                                        ^~~~~~~~
C:\instantclient_11_2\sdk\include/ociap.h:7471:36: error: unknown type name 'ubig_ora'
                      uword origin, ubig_ora offset, sb1 dir );
                                    ^~~~~~~~
C:\instantclient_11_2\sdk\include/ociap.h:8278:23: error: unknown type name 'sbig_ora'
                       sbig_ora bufferLength, sbig_ora *returnLength,
                       ^~~~~~~~
C:\instantclient_11_2\sdk\include/ociap.h:8278:46: error: unknown type name 'sbig_ora'
                       sbig_ora bufferLength, sbig_ora *returnLength,
                                              ^~~~~~~~

**Comment by mattn** [comment]
do you use mingw gcc instead of msys2 gcc?

**Comment by amiracam** [comment]
to be honest , now I'm all turned around, returned to my snapshot of Win 10 and repeated getting your driver

and I get the following:

amira@DESKTOP-H5LU9OV MINGW64 ~
$ go get -u -v github.com/mattn/go-oci8
github.com/mattn/go-oci8 (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
github.com/mattn/go-oci8
# github.com/mattn/go-oci8
C:\Users\amira\go\src\github.com\mattn\go-oci8\oci8.go:4:10: fatal error: oci.h: No such file or directory
 #include <oci.h>
          ^~~~~~~
compilation terminated.

with regards to GCC :
$ gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mattn** [comment]
did you put oci8.pc into your $PKG_CONFIG_PATH ? and did you modify your oci8.pc fit to your environment?

**Comment by MichaelS11** [comment]
@mattn Close this?
