### ISSUE TITLE
Unable to install go-oci8 on windows 64 bits again

### ISSUE THREAD

**Issue by ericgarcia38** [mattn/go-oci8#139]
Hello,

i m trying to install the package go-oci8 and always get the following message: become crazy.

thx for your help.

ericg

c:\go\work>go get github.com/mattn/go-oci8
# pkg-config --cflags oci8
pkg-config: exit status 3221225595

--- oci8.pc
prefix=/devel/target/XXXXXXXXXXXXXXXXXXXXXXXXXX
exec_prefix=${prefix}
libdir=C:/instantclient_12_1/sdk/lib/msvc
includedir=C:/instantclient_12_1/sdk/include
glib_genmarshal=glib-genmarshal
gobject_query=gobject-query
glib_mkenums=glib-mkenums
Name: oci8
Description: oci8 library
Libs: -L${libdir} -loci
Cflags: -I${includedir}
Version: 12.1

my configuration:

windows 10, Oracle client 64 b, GO 64
in PATH i have : C:\GO\BIN;C:\go\pkg-config-0.26\bin;C:\go\pkg-config-0.26\PKG_CONFIG_PATH;C:\go\TDM-GCC-64\bin

PKG_CONFIG_PATH=C:\go\pkg-config-0.26\PKG_CONFIG_PATH

**Comment by X3STeNLiTE** [comment]
May be this help
Click -> [How to install pkg config in windows?](https://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows)

**Comment by ShehabSunny** [comment]
This solution worked for me.
https://gist.github.com/mnadel/8678269

Note. gcc that comes with minwg64 worked perfectly for me. Download Minwg64 and gcc will come with it. Make sure you have gcc in path.

**Comment by MichaelS11** [comment]
Here is what I did:

Install and setup Go

Downloaded and install mingw64
https://mingw-w64.org/doku.php/download
I installed to: C:\app\mingw64\
Then added the path C:\app\mingw64\ to the Path environment variable

Then downloaded and installed Oracle instant client
https://www.oracle.com/technetwork/database/database-technologies/instant-client/downloads/index.html
I installed to: C:\app\instantclient_11_2_64
Then added the path C:\app\instantclient_11_2_64\ to the Path environment variable

Then create user in database:
```
CREATE USER scott IDENTIFIED BY tiger DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
GRANT connect, resource, create view, create synonym TO scott;
GRANT execute ON SYS.DBMS_LOCK TO scott;
create or replace function SCOTT.SLEEP_SECONDS (p_seconds number) return integer is
begin
  dbms_lock.sleep(p_seconds);
  return 1;
end SLEEP_SECONDS;
/
```

Then test:
```
set CGO_CFLAGS=-IC:\app\instantclient_11_2_64\sdk\include\ -static
set CGO_LDFLAGS=-LC:\app\instantclient_11_2_64\sdk\lib\msvc\ -lstdc++ -loci -static
go test -v github.com/mattn/go-oci8 -tags noPkgConfig -args -disableDatabase=false -hostValid replace_with_your_db_host -username scott -password tiger
```

**Comment by MichaelS11** [comment]
@mattn Close this?
