### ISSUE TITLE
go 1.8 Cancelable queries runs in the background on the database and not killed

### ISSUE THREAD

**Issue by devarsh** [mattn/go-oci8#142]
**Description**
Cancelable queries not killing session on the database
**Expected Behavior** 
When context is done, the underlying driver to kill sessions on the database too.

**os**  
Mac OS X El Capitan
**go version**  
1.8
**Oracle Driver**  
oracle instantclient 12_1

Following is my sample code
```go
package main

import (
	"context"
	"database/sql"
	"fmt"
	_ "github.com/mattn/go-oci8"
	"time"
)

func main() {
	db, err := sql.Open("oci8", "MySERVICE")
	checkErr(err)
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*2)
	go makeDbCall(db, ctx, cancel)
	select {
	case <-ctx.Done():
	}
	fmt.Println("done...")

}

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}

func makeDbCall(db *sql.DB, ctx context.Context, cancel context.CancelFunc) {
//large table with a million records, 
//go routine is terminated but query is running in the backend on the database.
	row := db.QueryRowContext(ctx, "select sum(amount) from main_trn")
	var sum []byte
	erro := row.Scan(&sum)
	fmt.Printf("%s\n", sum)
	checkErr(erro)
	cancel()
}

```

**Comment by mattn** [comment]
No, just cancel collecting record. Don't kill the session.

**Comment by devarsh** [comment]
Can that be possible anytime, or possible workarounds

**Comment by mattn** [comment]
See the doc. https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit#

>If the driver does support context the driver may choose to also cancel the query on the server rather than just closing the connection.

**Comment by devarsh** [comment]
Thanks for the info.

Sorry for bugging you, but I want to just understand what prevents the driver from implementing it, want to get some insights into limitations of the underlying OCILIB.

**Comment by MichaelS11** [comment]
@devarsh 

When a context is canceled on a statement, then OCIBreak is called, which does not kill the session.
https://docs.oracle.com/cd/B19306_01/appdev.102/b14250/oci16msc007.htm#i540487

Opening a new session in Oracle is kind of "expensive". Most of the time killing a session is not wanted. Plus the number of connections (sessions) is really handled by the Go SQL code, not so much the driver code.

If you wanted to kill the session, probably would need to run the query in a Go SQL transaction by calling begin.
https://golang.org/pkg/database/sql/#DB.Begin
Then run the query. When wanted, then cancel the context. Then run some kind of call to kill that session, maybe something like:
https://mikesmithers.wordpress.com/tag/users-killing-their-own-sessions/
Then close the Go SQL transaction.

**Comment by MichaelS11** [comment]
Close this?
