### ISSUE TITLE
No implementation method DecimalSize ()

### ISSUE THREAD

**Issue by saibing** [mattn/go-oci8#143]
The go1.8 database/sql has the follow method, but there is no implementation to fill precision, scale, precisionScale

```go
func (ci *ColumnType) DecimalSize() (precision, scale int64, ok bool) {
	return ci.precision, ci.scale, ci.hasPrecisionScale
}
```

**Comment by mattn** [comment]
This is already implemented.

**Comment by MichaelS11** [comment]
Note that this has not been implemented but don't think it needs to be because of how oci8 changes all numbers either into float64 or int64, so not going to get the normal database precision.
