### ISSUE TITLE
Support for macOS?

### ISSUE THREAD

**Issue by tkandal** [mattn/go-oci8#144]
Will it be possible to install and run this code on macOS?

**Comment by mattn** [comment]
Sorry, I don't have OSX but seems to be there are someone succeeded.

**Comment by devarsh** [comment]
I know i'm a bit late here to comment, but will keep it here as a reference for anyone coming from mac world to make this driver working

*oralce driver*
**Links**
https://gocodecloud.com/blog/2016/08/09/accessing-an-oracle-db-in-go/
https://github.com/d-smith/go-examples/tree/master/oracle
https://github.com/Centny/Centny/blob/master/Articles/How%20build%20github.com:mattn:go-oci8.md

**DIR STRUCTURE**
├── BASIC_README
├── adrci
├── genezi
├── libclntsh.dylib -> libclntsh.dylib.12.1
├── libclntsh.dylib.12.1
├── libclntshcore.dylib.12.1
├── libnnz12.dylib
├── libocci.dylib.12.1
├── libociei.dylib
├── libocijdbc12.dylib
├── libons.dylib
├── liboramysql12.dylib
├── oci8.pc
├── ojdbc6.jar
├── ojdbc7.jar
├── sdk
│   ├── SDK_README
│   ├── admin
│   │   └── oraaccess.xsd
│   ├── demo
│   │   ├── cdemo81.c
│   │   ├── demo.mk
│   │   ├── occidemo.sql
│   │   ├── occidemod.sql
│   │   ├── occidml.cpp
│   │   ├── occiobj.cpp
│   │   ├── occiobj.typ
│   │   ├── oraaccess.xml
│   │   └── setuporamysql.sh
│   ├── include
│   │   ├── ldap.h
│   │   ├── nzerror.h
│   │   ├── nzt.h
│   │   ├── occi.h
│   │   ├── occiAQ.h
│   │   ├── occiCommon.h
│   │   ├── occiControl.h
│   │   ├── occiData.h
│   │   ├── occiObjects.h
│   │   ├── oci.h
│   │   ├── oci1.h
│   │   ├── oci8dp.h
│   │   ├── ociap.h
│   │   ├── ociapr.h
│   │   ├── ocidef.h
│   │   ├── ocidem.h
│   │   ├── ocidfn.h
│   │   ├── ociextp.h
│   │   ├── ocikpr.h
│   │   ├── ocixmldb.h
│   │   ├── ocixstream.h
│   │   ├── odci.h
│   │   ├── oratypes.h
│   │   ├── ori.h
│   │   ├── orid.h
│   │   ├── orl.h
│   │   ├── oro.h
│   │   ├── ort.h
│   │   └── xa.h
│   ├── ott
│   └── ottclasses.zip
├── uidrvci
└── xstreams.jar

**ENV VARIABLES**
export DYLD_LIBRARY_PATH="/Users/acuteinfo/instantclient_12_1"
export PKG_CONFIG_PATH="/Users/acuteinfo/instantclient_12_1"
export LD_LIBRARY_PATH="/Users/acuteinfo/instantclient_12_1"


**file oci8.md content for Mac**
prefix=/Users/acuteinfo/instantclient_12_1
includedir=${prefix}/sdk/include
libdir=${prefix}

Name: oci8
Description: Oracle Instant Client
Version: 12.1
Cflags: -I${includedir}
Libs: -L${libdir} -lclntsh

**Comment by lnxbil** [comment]
I can confirm that it works, issue can be closed :-D
