### ISSUE TITLE
cannot find -lclntsh on win8 64bits

### ISSUE THREAD

**Issue by julianzhu1117** [mattn/go-oci8#145]
i meet this problem where run cmd go get github.com/mattn/go-oci8。i'v seen this issue in annother project,how can i solve this problem in this project,thanks!

https://github.com/tgulacsi/goracle/issues/11

**Comment by mattn** [comment]
Because we don't know where you did install oracle. If you MUST specify WHERE you did install oracle. For go-oci8, you can use oci8.pc file to specify the location. This mean we can't do `go get`. Please see README.md

**Comment by mattn** [comment]
If you mean the `-l` flag, you can modify oci8.pc to specify `-loci` instead.

**Comment by julianzhu1117** [comment]
thanks,i'v modify oci8.pc and solved this problem
