### ISSUE TITLE
Connection String

### ISSUE THREAD

**Issue by pfortin-urbn** [mattn/go-oci8#146]
I am trying to use a connection string in the form:

`
username/password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.1.1.12)(PORT=1521))(CONNECT_DATA=(SID=XE)(SERVER=POOLED)))
`

but this does seem to work, is this supported by this driver and can you provide a quick example of how to use it if it does.  Tks!

**Comment by djadala** [comment]
it should work, what are returned errors ?

**Comment by pfortin-urbn** [comment]
"invalid username/password; logon denied"

**Comment by geldabhojal** [comment]
Can you tell me how did you get it to work?
