### ISSUE TITLE
how to fix this problem

### ISSUE THREAD

**Issue by JackFong** [mattn/go-oci8#148]
![912a24f9-f08b-40b3-8e4e-a3bcf3f8942d](https://cloud.githubusercontent.com/assets/507627/25381026/d9de8aca-29e4-11e7-8759-fc172d1de412.png)

my environments:
CentOS 3.10.0-327.28.2.e17
server oracle 11g
client InstantClient 12
go 1.8

**Comment by mattn** [comment]
I can't figure out without codes.

**Comment by MichaelS11** [comment]
@mattn Close this?
