### ISSUE TITLE
Query extremely slow. 

### ISSUE THREAD

**Issue by peachyo** [mattn/go-oci8#149]
I wrote a simple go program running on windows and connecting to oracle database. The query is so slow even "select 1 from dual" took 800ms. But using sqldeveloper, it's only 50ms and a java jdbc program took 100ms. What could be the problem?

**Comment by mattn** [comment]
What is your code?

**Comment by peachyo** [comment]
Hi Matt, here is my code. 

	db, err := sql.Open("oci8", acctInfoDsn)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer db.Close()
	fmt.Println("connected to db")

	var fld1 []byte
	t := time.Now()
	err = db.QueryRow("select 1 from dual").Scan(&fld1)
	if err != nil {
		fmt.Println(err)
		panic(err)
	}
	fmt.Println(time.Since(t))

**Comment by mattn** [comment]
Which part do you get then benchmark?

**Comment by peachyo** [comment]
For the db.QueryRow statement. It took 800ms. When I use the SQL developer to run the same query, it takes 50ms. And the jdbc code I wrote, it took 100ms for "ResultSet rs=stmt.executeQuery("select 1 from dual");  " statement. 

I am prototyping microservice using go and grpc. But the db query is so slow, If I can't get it resolved, then I will have to go back to java.

**Comment by mattn** [comment]
go's driver may have connection pool. could you please try to call db.Ping before call QueryRow?

**Comment by peachyo** [comment]
Wow, I called db.Ping before QueryRow. Now it's 49ms. 

So should I always call db.Ping first?

**Comment by mattn** [comment]
>So should I always call db.Ping first?

If you want to have delay until the first connection, you've better not to call the ping. And if you want to get actual connection, you've better to call ping.

**Comment by peachyo** [comment]
Thanks so much for your help!
