### ISSUE TITLE
Library Crashes with Go 1.8

### ISSUE THREAD

**Issue by freedombird9** [mattn/go-oci8#150]
The program can start and run for some time. It can successfully query the database, although there're timeouts.  But after a while it will hit some segfault and exit.  The stack trace from the 1st Goroutine is:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f3d23f16d8f]
runtime stack:
runtime.throw(0x968c06, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db
goroutine 64816 [syscall, locked to thread]:
runtime.cgocall(0x85c0e0, 0xc4212c7048, 0xc421ffc0b0)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc4212c7000 sp=0xc4212c6fc0
github.com/mattn/go-oci8._Cfunc_calloc(0x3, 0x4, 0x0)
	github.com/mattn/go-oci8/_obj/_cgo_gotypes.go:902 +0x4e fp=0xc4212c7048 sp=0xc4212c7000
github.com/mattn/go-oci8.(*OCI8Stmt).query(0xc420d84420, 0x7f3d2005f878, 0xc420a70480, 0xc420d843f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/mattn/go-oci8/oci8.go:1079 +0x284 fp=0xc4212c71e0 sp=0xc4212c7048
github.com/mattn/go-oci8.(*OCI8Conn).query(0xc4216c3110, 0x7f3d2005f878, 0xc420a70480, 0x96f70a, 0x56, 0xc420d843f0, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/mattn/go-oci8/oci8.go:569 +0x102 fp=0xc4212c7270 sp=0xc4212c71e0
github.com/mattn/go-oci8.(*OCI8Conn).QueryContext(0xc4216c3110, 0xdcf620, 0xc420a70480, 0x96f70a, 0x56, 0xc420d843c0, 0x1, 0x1, 0x40b2de, 0x8a8f80, ...)
	/go/src/github.com/mattn/go-oci8/oci8_go18.go:22 +0x25b fp=0xc4212c7380 sp=0xc4212c7270
database/sql.ctxDriverQuery(0xdcf620, 0xc420a70480, 0x7f3d2005f828, 0xc4216c3110, 0x96f70a, 0x56, 0xc420d843c0, 0x1, 0x1, 0x42b70e, ...)
	/usr/local/go/src/database/sql/ctxutil.go:48 +0x28d fp=0xc4212c7408 sp=0xc4212c7380
database/sql.(*DB).queryConn.func1()
	/usr/local/go/src/database/sql/sql.go:1264 +0x99 fp=0xc4212c74a0 sp=0xc4212c7408
database/sql.withLock(0xdcc660, 0xc420457030, 0xc4212c75d0)
	/usr/local/go/src/database/sql/sql.go:2545 +0x65 fp=0xc4212c74c8 sp=0xc4212c74a0
database/sql.(*DB).queryConn(0xc42015c140, 0xdcf620, 0xc420a70480, 0xc420457030, 0xc42198c190, 0x96f70a, 0x56, 0xc4212c79c0, 0x1, 0x1, ...)
	/usr/local/go/src/database/sql/sql.go:1265 +0x671 fp=0xc4212c7640 sp=0xc4212c74c8
database/sql.(*DB).query(0xc42015c140, 0xdcf620, 0xc420a70480, 0x96f70a, 0x56, 0xc4212c79c0, 0x1, 0x1, 0x42b701, 0xc421960420, ...)
	/usr/local/go/src/database/sql/sql.go:1250 +0x12f fp=0xc4212c76c8 sp=0xc4212c7640
database/sql.(*DB).QueryContext(0xc42015c140, 0xdcf620, 0xc420a70480, 0x96f70a, 0x56, 0xc4212c79c0, 0x1, 0x1, 0xdd6580, 0x952200, ...)
	/usr/local/go/src/database/sql/sql.go:1227 +0xb8 fp=0xc4212c7758 sp=0xc4212c76c8
main.processMessage(0xc421b36000, 0x200)
	/go/src/gomq/consumers/AcctRecordNoSqlProcessor/main.go:300 +0x200 fp=0xc4212c7cb8 sp=0xc4212c7758
main.memcacheCallback(0xc42194c600, 0x2e7, 0x600, 0xc42194c600)
	/go/src/gomq/consumers/AcctRecordNoSqlProcessor/main.go:496 +0x2aa fp=0xc4212c7d78 sp=0xc4212c7cb8
go-jasperlib/kestrel.(*MemcacheReader).readerRoutine(0xc42009c2c0)
	/go/src/go-jasperlib/kestrel/reader.go:259 +0x4b8 fp=0xc4212c7fd8 sp=0xc4212c7d78
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4212c7fe0 sp=0xc4212c7fd8
created by go-jasperlib/kestrel.(*MemcacheReader).scaleReaders
	/go/src/go-jasperlib/kestrel/reader.go:623 +0x2c2
```

I double-checked my code and I don't think there's any possible memory leak, double frees or anything in my code.  The queries are not complex and have been working in Java all the time.  I moved the logic to Go to improve the performance.  An example:

```
ctx, cancel := context.WithTimeout(context.Background(), 10*time.Seconds)
defer cancel()
rows, err := initialedDb.QueryContext(ctx, "sql_query")
// error check and defer rows.Close()

```

This is just one error that I encountered.  I've also seen `ORA-21500: internal error code, arguments: [17114]`, which can be traced to `github.com/mattn/go-oci8._Cfunc_OCIHandleFree(0x24d3a20, 0x4, 0x0)`.  I'm not sure if these errors are related, but I can file another issue if they're separate.

My Go version is 1.8.1

**Comment by mattn** [comment]
Do you think this is a bug which is related on context/cancel?

**Comment by freedombird9** [comment]
Probably.  Before we didn't add timeout, thus there's no context in the query.  We didn't see any error.  We only see it after adding timeout.  But we certainly need to have timeouts for these queries.

**Comment by freedombird9** [comment]
So I deleted the `defer cancel()` call. But still got segfault.

**Comment by mattn** [comment]
Could you please show me the minimal code to reproduce?

**Comment by freedombird9** [comment]
Sure. Just involve the timeout context and issue any query concurrently. The queries are really simple, no loop involved. And I ported them over from Java code to improve the performance. They've been working well before 1.8 without context. I'm using the database/sql package.

```
ctx, _ := context.WithTimeout(context.Background(), 10*time.Second)
rows, err := pvgdb.QueryContext(ctx, "select scheduleid, newscheduleid from acctbillsettings where acctid=:acctid and rownum=1", acctId)
if err != nil {
    return -1, err
}
defer rows.Close()
```

**Comment by mattn** [comment]
Thank you. I'll look into it in later.

**Comment by freedombird9** [comment]
Sure. I think it has something to do with multi-threading.  When I tried with a single Goroutine, there's no issue at all, not even timeouts.

**Comment by mattn** [comment]
Ah, implementation of cancel on go-oci8 uses OCIBreak. OCIBreak stop all of execution for the connection.

**Comment by mattn** [comment]
I added TestTimeout. But don't reproduce it on my CentOS.

https://github.com/mattn/go-oci8/commit/5a0b527f3e1d03cc3adac1a77521eccbbe574c25

**Comment by freedombird9** [comment]
Yeah, it doesn't always happen.  Our program is like a MQ consumer that continuously polls messages from a queue and then makes some DB queries.  It can scale up to hundreds of goroutines depends on the latency.  It can usually run well for a while, and then this error will randomly pop out.  I don't think a unit test can catch this.  We only saw it during heavy load test in our lab.

**Comment by MichaelS11** [comment]
This may now be fixed, can you please test?

**Comment by MichaelS11** [comment]
@mattn Close this?
