### ISSUE TITLE
ORA-01000 error

### ISSUE THREAD

**Issue by linlexing** [mattn/go-oci8#151]
I fetch the last version source code,and startup my programe ,throw ORA-01000 error，and run test code:
```go
package main

import (
	"time"

	"database/sql"

	_ "github.com/mattn/go-oci8"
)

func main() {
	db, err := sql.Open("oci8", "***/***@localhost:1521/orcl")
	if err != nil {
		panic(err)
	}
	defer db.Close()
	for i := 0; i < 1000; i++ {
		var d int64
		strSQL := "select 1 from dual"
		if err := db.QueryRow(strSQL).Scan(&d); err != nil {
			panic(err)
		}
		println("1")
		time.Sleep(time.Second * 3)
	}
}
```
at sqlplus:
```sql
 select count(*) from v$open_cursor;
```
The number is increasing

but 2016-10-14 commit(1fcb1b316563ccc74d7372bb32319caecce11332),work fine.

go version go1.8.3 windows/amd64
Oracle Database 11g Enterprise Edition Release 11.2.0.1.0

**Comment by linlexing** [comment]
every one can help me

**Comment by mattn** [comment]
I'll look into it.

**Comment by mattn** [comment]
If you still have issue, please reopen this.

**Comment by linlexing** [comment]
at #120 ,you talk me to comment-out 
https://github.com/mattn/go-oci8/blob/master/oci8.go#L537-L546

that's is OCI8Conn.Query func,comment-out it,work fine at 122235c7d97e17f3b399402bbc96bd6ac15dac91

**Comment by linlexing** [comment]
So great，work fine！

**Comment by mattn** [comment]
Hmm, test failed.

https://travis-ci.org/mattn/go-oci8/builds/241026060?utm_source=email&utm_medium=notification

**Comment by mattn** [comment]
Sorry, I'll revert last change, and reopen this.

**Comment by mattn** [comment]
maybe fixed.
