### ISSUE TITLE
Cross Compile on OSX for linux fails

### ISSUE THREAD

**Issue by rafael-azevedo** [mattn/go-oci8#152]
Hello ,

I am trying to build the binaries on OSX 10.11.6 using GO 1.8.1 for linux amd64. When compiling i get the errors below. For OSX compile it works perfectly. 

```
GOOS=linux GOARCH=amd64 go build -v -o outageapi cmd/main.go
runtime/internal/sys
runtime/internal/atomic
runtime
errors
internal/race
math
sync/atomic
unicode/utf8
unicode
encoding
unicode/utf16
container/list
crypto/subtle
crypto/internal/cipherhw
sync
internal/nettrace
vendor/golang_org/x/crypto/curve25519
vendor/golang_org/x/crypto/poly1305
github.com/hashicorp/hcl/hcl/strconv
io
syscall
internal/singleflight
hash
crypto/cipher
hash/crc32
crypto/hmac
bytes
strings
bufio
vendor/golang_org/x/text/transform
golang.org/x/text/transform
path
html
github.com/pelletier/go-buffruneio
strconv
math/rand
internal/syscall/unix
golang.org/x/sys/unix
time
reflect
encoding/base64
crypto/aes
crypto
crypto/rc4
crypto/sha512
crypto/md5
crypto/sha1
crypto/sha256
os
fmt
sort
encoding/binary
encoding/pem
path/filepath
regexp/syntax
crypto/des
vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20
vendor/golang_org/x/crypto/chacha20poly1305
io/ioutil
github.com/spf13/afero/mem
encoding/json
context
compress/flate
math/big
encoding/hex
vendor/golang_org/x/net/http2/hpack
vendor/golang_org/x/net/idna
vendor/golang_org/x/text/unicode/norm
net
vendor/golang_org/x/text/width
log
mime
mime/quotedprintable
net/http/internal
net/url
regexp
database/sql/driver
compress/gzip
golang.org/x/net/context
encoding/csv
github.com/fsnotify/fsnotify
database/sql
github.com/hashicorp/hcl/hcl/token
github.com/hashicorp/hcl/hcl/ast
github.com/hashicorp/hcl/json/token
github.com/hashicorp/hcl/json/scanner
flag
github.com/hashicorp/hcl/json/parser
github.com/mitchellh/mapstructure
golang.org/x/text/unicode/norm
text/template/parse
github.com/hashicorp/hcl/hcl/scanner
github.com/hashicorp/hcl/hcl/parser
github.com/pelletier/go-toml
github.com/hashicorp/hcl
github.com/mattn/go-oci8
**# github.com/mattn/go-oci8
**../../mattn/go-oci8/oci8_go18.go:12:** undefined: OCI8Conn
**../../mattn/go-oci8/oci8_go18.go:17: undefined: OCI8Conn
**../../mattn/go-oci8/oci8_go18.go:18: undefined: namedValue
**../../mattn/go-oci8/oci8_go18.go:20: undefined: namedValue
**../../mattn/go-oci8/oci8_go18.go:26: undefined: OCI8Conn
**../../mattn/go-oci8/oci8_go18.go:27: undefined: namedValue
**../../mattn/go-oci8/oci8_go18.go:35: undefined: OCI8Conn
**../../mattn/go-oci8/oci8_go18.go:40: undefined: OCI8Conn
**../../mattn/go-oci8/oci8_go18.go:45: undefined: OCI8Stmt
**../../mattn/go-oci8/oci8_go18.go:54: undefined: OCI8Stmt
**../../mattn/go-oci8/oci8_go18.go:27: too many errors**
github.com/spf13/jwalterweatherman
gopkg.in/yaml.v2
os/exec
text/template
crypto/rand
crypto/elliptic
encoding/asn1
crypto/dsa
crypto/rsa
crypto/ecdsa
crypto/x509/pkix
html/template
github.com/spf13/cast
crypto/x509
vendor/golang_org/x/net/lex/httplex
net/textproto
github.com/spf13/pflag
mime/multipart
crypto/tls
net/http/httptrace
net/http
github.com/gorilla/mux
github.com/spf13/afero
github.com/magiconair/properties
github.com/rafael-azevedo/outageapi/logger
github.com/spf13/viper
github.com/rafael-azevedo/outageapi/utils
```

**Comment by mattn** [comment]
because you don't use cross-C compiler for linux.

**Comment by rafael-azevedo** [comment]
Hey sorry I lost track of this . What should I do to turn off the c-compiler when building this?

**Comment by mattn** [comment]
go-oci8 require oracle SDK so you need to install C compiler and SDK for the target OS.

**Comment by mejinke** [comment]
Is that settled? I have this problem, too

**Comment by vk1818** [comment]
hi i have cross c compiler mingw-w64 installed in my ubuntu machine but still i get oci8_go18.go:12:10: undefined: OCI8Conn

**Comment by vk1818** [comment]
i just enabled CGO_ENABLED now its a different error 
gcc: error: unrecognized command line option ‘-mthreads’

**Comment by mattn** [comment]
@vk1818 you should set environment variable CC to the cross-compiler.

**Comment by vk1818** [comment]
@mattn how do i set env for CC in ubuntu

**Comment by vk1818** [comment]
i had set to export CC=/usr/lib/gcc  but still same error
and for more info 
gcc -print-prog-name=cc1
/usr/lib/gcc/x86_64-linux-gnu/4.8/cc1

**Comment by mattn** [comment]
set CC to cross-compiler not host-compiler.

**Comment by vk1818** [comment]
you mean mingw path

**Comment by vk1818** [comment]
@mattn please help for this issue

**Comment by mattn** [comment]
please show me output of following command:

```
echo $CC
```

```
go env
```

And path to the oracle instant client SDK for Windows.

**Comment by vk1818** [comment]
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vijay/searchblox"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="/usr/x86_64-w64-mingw32/"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

echo $CC
/usr/x86_64-w64-mingw32/

**Comment by mattn** [comment]
You don't set GOOS and GOARCH for the build target.

**Comment by vk1818** [comment]
i am using lite ide tool for coding so if i select cross-win64 in IDE then it shows
Current environment change id "cross-win64"
/usr/local/go/bin/go env [/usr/local/go]
GOARCH="amd64"
GOBIN=""
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="windows"
GOPATH="/home/vijay/searchblox"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="/usr/x86_64-w64-mingw32/"
GOGCCFLAGS="-m64 -mthreads -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
Command exited with code 0.

**Comment by mattn** [comment]
And what error do you get?

**Comment by vk1818** [comment]
basically i am confused which path i need to set for CC now with above CC path i get 
# runtime/cgo
fork/exec /usr/x86_64-w64-mingw32/: permission denied
with following images please suggest which path i need to set for CC
![image](https://user-images.githubusercontent.com/31547727/30051574-2a72b894-9240-11e7-90c6-a889a8b141ef.png)
![image](https://user-images.githubusercontent.com/31547727/30051596-4124ac14-9240-11e7-83d1-60e3e737d7ef.png)
![image](https://user-images.githubusercontent.com/31547727/30051643-6afbccde-9240-11e7-94b8-6227e8925165.png)
![image](https://user-images.githubusercontent.com/31547727/30051659-7be792da-9240-11e7-9730-d40a9c03db6c.png)
i tried for /opt/bin also same permission denied error

**Comment by mattn** [comment]
export CC=x86_64-w64-mingw32-gcc

**Comment by vk1818** [comment]
@mattn  after setting CC as you said now its a different error
# github.com/mattn/go-oci8
/usr/bin/x86_64-w64-mingw32-ld: cannot find -lclntsh
collect2: error: ld returned 1 exit status

**Comment by mattn** [comment]
https://github.com/mattn/go-oci8/issues/172

**Comment by bensinos** [comment]
Fix it? @rafael-azevedo

**Comment by MichaelS11** [comment]
Maybe look at:
https://github.com/mattn/go-oci8/issues/84

@mattn ,
Can this be closed?
