### ISSUE TITLE
no values returned when cols met a null value

### ISSUE THREAD

**Issue by arashicage** [mattn/go-oci8#154]
hi，mattn,

when i query with a sql like
select col1,col2,col3,col4.. from some_table,
and when some col such as col2 get a null value,then col3,col4,and on give null too.

for example 
`select
  1,
  2,
  null,
  4,
  5
	from dual
	`
codes 
```
rows.Scan(&f1 ,&f2 ,&f3 ,&f4 ,&f5)
fmt.Println(f1,"-",f2,"-",f3,"-",f4,"-",f5,"-")
```
gives 
```
1 - 2 -  -  -  -
```
but
``` 
1 - 2 -  - 4 - 5 - 
```

**Comment by arashicage** [comment]
sorry, the exactly describe is,when the some colA met a null value ,the cols behidn colA return null too。for example 

sql_ := `select
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  null,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1
	from dual
	`
when  fmt.Println(f15,"-",f16,"-",f17,"-",f18,"-",f19,"-") gives

**Comment by mickefilen** [comment]
I've also bumped in to this problem. I can provide additional example if necessary. Would be super nice if this as fixed. As it is now one needs to nvl all cols that can be null.

**Comment by mattn** [comment]
What type of variables did you use? Maybe you use string. And database/sql can't handle string for null. This is a spec of go. And maybe, you don't check err returned from rows.Scan().

```go
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/mattn/go-oci8"
)

func main() {
	db, err := sql.Open("oci8", "scott/tiger@XE")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	rows, err := db.Query("select 1, 2, null, 4, 5 from dual")
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()
	for rows.Next() {
		var f1, f2, f3, f4, f5 string
		err = rows.Scan(&f1, &f2, &f3, &f4, &f5)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(f1, "-", f2, "-", f3, "-", f4, "-", f5, "-")
	}
}
```
![6821219e38509fd9](https://cloud.githubusercontent.com/assets/10111/26412096/995b072a-40e2-11e7-8b8c-abafb5a860dc.png)

**Comment by mattn** [comment]
FYI, you shoud use `sql.NullString` instead of string.

```go
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/mattn/go-oci8"
)

func main() {
	db, err := sql.Open("oci8", "scott/tiger@XE")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	rows, err := db.Query("select 1, 2, null, 4, 5 from dual")
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()
	for rows.Next() {
		var f1, f2, f3, f4, f5 sql.NullString
		err = rows.Scan(&f1, &f2, &f3, &f4, &f5)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(f1.String, "-", f2.String, "-", f3.String, "-", f4.String, "-", f5.String, "-")
	}
}
```
