### ISSUE TITLE
Using ODPI-C

### ISSUE THREAD

**Issue by cjbj** [mattn/go-oci8#157]
@mattn and others, you might want to weigh in on https://github.com/oracle/odpi/issues/12#issuecomment-306406040 about Oracle involvement with Go and how/whether to use [ODPI-C](https://github.com/oracle/odpi).

**Comment by MichaelS11** [comment]
@mattn 
Close this?

**Comment by mattn** [comment]
I want to consider whether we can add this.

**Comment by mattn** [comment]
Sorry, I don't know what differ from goracle since I didn't use it.

**Comment by cjbj** [comment]
It also exposes database/sql.

**Comment by MichaelS11** [comment]
If goracle already uses ODPI-C, why would go-oci8 want to change to ODPI-C? Wouldn't that be having two drivers doing the same thing. Seems unwanted.

Plus, personally I think go-oci8 is good using the Oracle C driver. The only thing that would be better is if there was a pure Go Oracle driver, without needing C or the Oracle C driver.

**Comment by MichaelS11** [comment]
@mattn Can we close this?
