### ISSUE TITLE
today's checkin fail compile on windows10 x64, the log is below

### ISSUE THREAD

**Issue by wushifeng** [mattn/go-oci8#159]
E:\gogo\2>go get -v  -x github.com/mattn/go-oci8
        WORK=C:\Users\WUSHIF~1\AppData\Local\Temp\go-build587263662
        golang.org/x/net/context
        mkdir -p $WORK\golang.org\x\net\context\_obj\
        mkdir -p $WORK\golang.org\x\net\
        cd e:\gogo\2\src\golang.org\x\net\context
        "C:\\tool\\go\\pkg\\tool\\windows_amd64\\compile.exe" -o "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\golang.org\\x\\net\\context.a" -trimpath "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662" -p golang.org/x/net/context -complete -buildid 5a74cf2d8214d446568d0757c834ff4a8c6faad5 -D _/e_/gogo/2/src/golang.org/x/net/context -I "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662" -pack "e:\\gogo\\2\\src\\golang.org\\x\\net\\context\\context.go" "e:\\gogo\\2\\src\\golang.org\\x\\net\\context\\go17.go"
        mkdir -p e:\gogo\2\pkg\windows_amd64\golang.org\x\net\
        cp $WORK\golang.org\x\net\context.a e:\gogo\2\pkg\windows_amd64\golang.org\x\net\context.a
        github.com/mattn/go-oci8
        mkdir -p $WORK\github.com\mattn\go-oci8\_obj\
        mkdir -p $WORK\github.com\mattn\
        cd e:\gogo\2\src\github.com\mattn\go-oci8
        pkg-config --cflags oci8
        pkg-config --libs oci8
        CGO_LDFLAGS="-g" "-O2" "-LC:/instantclient_12_2" 
        cd $WORK"-loci" "C:\\tool\\go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\" -importpath github.com/mattn/go-oci8 -- -IC:/instantclient_12_2/sdk/include/ -I "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\" -g -O2 oci8.go
        gcc -fdebug-prefix-map=a=b -c trivial.c
        gcc -gno-record-gcc-switches -c trivial.c
        cd e:\gogo\2\src\github.com\mattn\go-oci8
        gcc -I "e:\\gogo\\2\\src\\github.com\\mattn\\go-oci8" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662=/tmp/go-build" -gno-record-gcc-switches -IC:/instantclient_12_2/sdk/include/ -I "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\" -g -O2 -o "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\_cgo_export.o" -c "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\_cgo_export.c"
        gcc -I "e:\\gogo\\2\\src\\github.com\\mattn\\go-oci8" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662=/tmp/go-build" -gno-record-gcc-switches -IC:/instantclient_12_2/sdk/include/ -I "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\" -g -O2 -o "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\oci8.cgo2.o" -c "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\oci8.cgo2.c"
        gcc -I "e:\\gogo\\2\\src\\github.com\\mattn\\go-oci8" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662=/tmp/go-build" -gno-record-gcc-switches -IC:/instantclient_12_2/sdk/include/ -I "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\" -g -O2 -o "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\_cgo_main.o" -c "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\_cgo_main.c"
        gcc -I "e:\\gogo\\2\\src\\github.com\\mattn\\go-oci8" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662=/tmp/go-build" -gno-record-gcc-switches -o "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\_cgo_.o" "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\_cgo_main.o" "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\_cgo_export.o" "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\oci8.cgo2.o" -g -O2 -LC:/instantclient_12_2 -loci
        "C:\\tool\\go\\pkg\\tool\\windows_amd64\\cgo.exe" -dynpackage oci8 -dynimport "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\_cgo_.o" -dynout "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\_cgo_import.go"
        cd $WORK
        gcc -no-pie -c trivial.c
        cd e:\gogo\2\src\github.com\mattn\go-oci8
        gcc -I "e:\\gogo\\2\\src\\github.com\\mattn\\go-oci8" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662=/tmp/go-build" -gno-record-gcc-switches -o "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\_all.o" "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\_cgo_export.o" "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\oci8.cgo2.o" -g -O2 -LC:/instantclient_12_2 -Wl,-r -nostdlib -no-pie
        "C:\\tool\\go\\pkg\\tool\\windows_amd64\\compile.exe" -o "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8.a" -trimpath "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662" -p github.com/mattn/go-oci8 -buildid e0ef83db2f93aacc02eadf585ee750903032a6bc -D _/e_/gogo/2/src/github.com/mattn/go-oci8 -I "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662" -I "e:\\gogo\\2\\pkg\\windows_amd64" -pack "e:\\gogo\\2\\src\\github.com\\mattn\\go-oci8\\dsn.go" "e:\\gogo\\2\\src\\github.com\\mattn\\go-oci8\\oci8_go18.go" "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\_cgo_gotypes.go" "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\oci8.cgo1.go" "C:\\Users\\WUSHIF~1\\AppData\\Local\\Temp\\go-build587263662\\github.com\\mattn\\go-oci8\\_obj\\_cgo_import.go"
        # github.com/mattn/go-oci8
        ****src\github.com\mattn\go-oci8\oci8_go18.go:19: undefined: sql.Out
        **src\github.com\mattn\go-oci8\oci8_go18.go:75: undefined: sql.Out******

**Comment by mattn** [comment]
Sorry, reverted output parameters.
