### ISSUE TITLE
Placeholder syntax for prepared statements

### ISSUE THREAD

**Issue by fredcy** [mattn/go-oci8#16]
The database/sql documentation uses `?` for the placeholder(s) in prepared statements but I can't get that to work in go-oci8. It seems that I have to use `:1`, `:2`, etc as placeholders instead. Is that intentional?

**Comment by mattn** [comment]
Which placeholder is used is depend on RDBMS, I think.
(if i don't implement SQL parser)

**Comment by pamelamei** [comment]
it's :val$n for Oracle instead.
