### ISSUE TITLE
Whether batch insert is supported

### ISSUE THREAD

**Issue by joyhope** [mattn/go-oci8#163]
I read the sample code, but I did not find the batch insert demo.  Whether the driver support batch insert?

**Comment by mattn** [comment]
what is batch insert? do you mean bulk insert?

**Comment by joyhope** [comment]
Insert with multi records.  e.g I have 10K recorders, I try to insert records to oracle as quick as possible.

**Comment by mattn** [comment]
did you try conn.Begin()?

**Comment by joyhope** [comment]
whether you means

`tx, err :=conn.Begin()
for loop {
	_, err := tx.Exec()
}
err = tx.Commit()
`
I am reading the oci8 code, and try to confirm whether this is a possible solution.  (Sorry for my oracle test environment has not ready. )

**Comment by mattn** [comment]
no prob.

**Comment by djadala** [comment]
Hi,
You can achieve good insert performance using `insert all` on temporary table.
if you want to insert in table ttt:
```
-- only first time
create global temporary table tmp_ttt on commit preserve rows  as ( select * from ttt where 1=0);

truncate table tmp_ttt

-- in loop (and transaction)execute:
insert all
    into tmp_ttt ( a, b, ..) values( :1, :2:, ...)
    into tmp_ttt ( a, b, ..) values( :K, :K+1, ...)
    ...... x100 times
    into tmp_ttt ( a, b, ..) values( :K*100, :K*100+1, ...)
select * from dual;


-- and finally:
insert into ttt select(*) from tmp_ttt
```

**Comment by joyhope** [comment]
My data are all from an external resource, so the temporary table won't  solve my problem.

I success use `tx, err :=conn.Begin() for loop { _, err := tx.Exec() } err = tx.Commit()` .   

It works as Matt told.  Thank you

**Comment by MichaelS11** [comment]
@mattn Close this?
