### ISSUE TITLE
how to connect to oracle when my password has @

### ISSUE THREAD

**Issue by shanquanqiang** [mattn/go-oci8#165]
pasword  1qaz@WSX
 data source name  is 'username/"1qaz@WSX"'@192.168.1.1/orcl
the error is ORA-12154

**Comment by djadala** [comment]
may be `go get -u github.com/mattn/go-oci8` ?

**Comment by djadala** [comment]
also 
` 'username/1qaz@WSX@192.168.1.1/orcl'`
 ?

**Comment by shanquanqiang** [comment]
I have use github.com/mattn/go-oci8 and data source name is 'username/"1qaz@WSX"'@192.168.1.1/orcl ,but still have the error ORA-12154 @djadala

**Comment by djadala** [comment]
writing "may be go get -u github.com/mattn/go-oci8 ?" i mean does you ise last version of go-oci8 ?
and by 'username/1qaz@WSX@192.168.1.1/orcl' i mean try to remove those quotation marks(double & single).

**Comment by shanquanqiang** [comment]
go-oci8 is the latest
remove those quotation marks still have the error
and by i do not understand why dsn.go split function use strings.index instand of strings.lastindex

**Comment by djadala** [comment]
splitRight use strings.lastindex,
and if you don't see this function in dsn.go(just after split), then your go-oci8 is not latest.

**Comment by Keleir** [comment]
Alert user system with password contains character `@` then occurs an error as follow:
```
ERRO[2579] Error pinging oracle: ORA-12154: TNS:could not resolve the connect identifier specified
```

**Comment by MichaelS11** [comment]
Should be able to use @ in a password in most, if not all, cases because the code uses splitRight.

https://github.com/mattn/go-oci8/blob/1f7acaa9c28e56bd967f6d5930890947488e85bd/oci8.go#L50

Is this still an issue? Can this be closed?

**Comment by MichaelS11** [comment]
@mattn Close this?
