### ISSUE TITLE
Can't build usable .exe without VSCode

### ISSUE THREAD

**Issue by delaneyj** [mattn/go-oci8#166]
I have a strange situation where if I debug some code using the go-oci8 library there are no issues.  However if I just do a `go build` in the same place I get the following.

```go
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 19 [chan receive]:
database/sql.(*DB).connectionOpener(0xc042044640)
        C:/Go/src/database/sql/sql.go:837 +0x51
created by database/sql.Open
        C:/Go/src/database/sql/sql.go:582 +0x219
rax     0x0
rbx     0xc04208a920
rcx     0xa0fd08
rdi     0xa0fd10
rsi     0x0
rbp     0xc04208c000
rsp     0xa0fca8
r8      0x0
r9      0x0
r10     0xac5fbf
r11     0xa0fc30
r12     0x1
r13     0x0
r14     0x0
r15     0xf2
rip     0x7b8270
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b
```

Note if I `mv debug myapp.exe` the same code runs fine.  How do I figure out what is going on to be able to make reproducible builds without vscode.  This is on a Windows 10 x64 system.

**Comment by MichaelS11** [comment]
Is this still an issue?

**Comment by delaneyj** [comment]
Sorry I'm off that project, and difficult to test, I'll close this for now.
