### ISSUE TITLE
What's the problem, how to fix 

### ISSUE THREAD

**Issue by gftao** [mattn/go-oci8#167]
D:\>go get github.com/mattn/go-oci8
# github.com/mattn/go-oci8
c:/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-
mingw32/bin/ld.exe: skipping incompatible D:\Mysoft\Oracle\instantclient_12_2\sd
k\lib\msvc/oci.lib when searching for -loci
c:/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-
mingw32/bin/ld.exe: cannot find -loci
collect2.exe: error: ld returned 1 exit status

**Comment by mattn** [comment]
show me your `where gcc`

**Comment by gftao** [comment]
D:\>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/mingw/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/4.8.2
/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-4.8.2/configure --host=x86_64-w64-mingw32 --bu
ild=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysr
oot=/c/mingw482/x86_64-482-posix-seh-rt_v3-r2/mingw64 --with-gxx-include-dir=/mi
ngw64/x86_64-w64-mingw32/include/c++ --enable-shared --enable-static --disable-m
ultilib --enable-languages=ada,c,c++,fortran,objc,obj-c++,lto --enable-libstdcxx
-time=yes --enable-threads=posix --enable-libgomp --enable-lto --enable-graphite
 --enable-checking=release --enable-fully-dynamic-string --enable-version-specif
ic-runtime-libs --disable-isl-version-check --disable-cloog-version-check --disa
ble-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath -
-disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-
gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with
-system-zlib --with-gmp=/c/mingw482/prerequisites/x86_64-w64-mingw32-static --wi
th-mpfr=/c/mingw482/prerequisites/x86_64-w64-mingw32-static --with-mpc=/c/mingw4
82/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/mingw482/prerequisites/
x86_64-w64-mingw32-static --with-cloog=/c/mingw482/prerequisites/x86_64-w64-ming
w32-static --enable-cloog-backend=isl --with-pkgversion='x86_64-posix-seh, Built
 by MinGW-W64 project' --with-bugurl=http://sourceforge.net/projects/mingw-w64 C
FLAGS='-O2 -pipe -I/c/mingw482/x86_64-482-posix-seh-rt_v3-r2/mingw64/opt/include
 -I/c/mingw482/prerequisites/x86_64-zlib-static/include -I/c/mingw482/prerequisi
tes/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -I/c/mingw482/x86_64-
482-posix-seh-rt_v3-r2/mingw64/opt/include -I/c/mingw482/prerequisites/x86_64-zl
ib-static/include -I/c/mingw482/prerequisites/x86_64-w64-mingw32-static/include'
 CPPFLAGS= LDFLAGS='-pipe -L/c/mingw482/x86_64-482-posix-seh-rt_v3-r2/mingw64/op
t/lib -L/c/mingw482/prerequisites/x86_64-zlib-static/lib -L/c/mingw482/prerequis
ites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 4.8.2 (x86_64-posix-seh, Built by MinGW-W64 project)

**Comment by mattn** [comment]
please type `where gcc` in cmd.exe

**Comment by gftao** [comment]
D:\>where gcc
C:\MinGW\mingw64\bin\gcc.exe

**Comment by mattn** [comment]
Did you install oracle client 64bit ? Your compiler find the library but skipped it. I don't reproduce this.

```
skipping incompatible D:\Mysoft\Oracle\instantclient_12_2\sdk\lib\msvc/oci.lib
```

**Comment by gftao** [comment]
`import (
	"database/sql"
	"fmt"

	_ "github.com/mattn/go-oci8"
)

func main() {
	fmt.Println("-------1-----------")
	db, err := sql.Open("oci8", "APSMGM/APSMGM@192.168.20.12:1521/tfrbke")

	defer db.Close()
	if err != nil {
		//log.Fatal(err)
		fmt.Println(err)
	}
	fmt.Println("-------2-----------")
	err = db.Ping()
	fmt.Println("--------3----------")
	if err != nil {
		fmt.Println(err)
	}
}`

-------1-----------
-------2-----------
Exception 0xc0000005 0x0 0xffffffffffffffff 0x5a1988
PC=0x5a1988
signal arrived during external code execution

github.com/mattn/go-oci8._Cfunc_WrapOCIEnvCreate(0x1, 0x0, 0x0, 0x0, 0x0)
        github.com/mattn/go-oci8/_obj/_cgo_gotypes.go:796 +0x67
github.com/mattn/go-oci8.(*OCI8Driver).Open(0x5d71f0, 0x52cb20, 0x27, 0x0, 0x0,
0x0, 0x0)
        github.com/mattn/go-oci8/_obj/oci8.cgo1.go:393 +0xf8
database/sql.(*DB).conn(0xc0420381e0, 0x5a60c0, 0xc04200e240, 0xc04202fd01, 0xc0
4202fd80, 0x461019, 0x5b3620)
        C:/Go/src/database/sql/sql.go:999 +0x14d
database/sql.(*DB).query(0xc0420381e0, 0x5a60c0, 0xc04200e240, 0x52a0ff, 0x19, 0
x0, 0x0, 0x0, 0xc042060001, 0xc0420027a0, ...)
        C:/Go/src/database/sql/sql.go:1299 +0x6d
database/sql.(*DB).QueryContext(0xc0420381e0, 0x5a60c0, 0xc04200e240, 0x52a0ff,
0x19, 0x0, 0x0, 0x0, 0x14, 0x0, ...)
        C:/Go/src/database/sql/sql.go:1281 +0xbf
database/sql.(*DB).Query(0xc0420381e0, 0x52a0ff, 0x19, 0x0, 0x0, 0x0, 0x0, 0xc04
20482d0, 0xc04202fee8)
        C:/Go/src/database/sql/sql.go:1295 +0x89
main.main()
        E:/go/src/gooci/main.go:27 +0x25f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:2184 +0x1

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc0420381e0)
        C:/Go/src/database/sql/sql.go:871 +0x51
created by database/sql.Open
        C:/Go/src/database/sql/sql.go:609 +0x219
rax     0x22fcd0
rbx     0xc04202fa48
rcx     0x22fcd0
rdi     0xc04202fa48
rsi     0x5bd1a0
rbp     0x22fd00
rsp     0x22fc78
r8      0x0
r9      0x0
r10     0xffff
r11     0x22fc00
r12     0x0
r13     0x6
r14     0x0
r15     0xfb
rip     0x5a1988
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

**Comment by mattn** [comment]
Well, did you install Oracle SDK 64bit ?

**Comment by sumiet** [comment]
I am facing similar issue. My debain packages are:

  - oracle-instantclient12.1-basic
  - oracle-instantclient12.1-devel
and they installed via dockers during compilation. How do I make sure it is 64bit SDK?

I also checked similar reported issue where you mentioned setting NLS_LANG path. How do i do that in linux and macos and which path to use?

**Comment by mattn** [comment]
>How do I make sure it is 64bit SDK?

I don't make sure but if you use 64bit OS, and you didn't install package without `:i386` suffix, probably it should be a 64bit package.

**Comment by cjbj** [comment]
On 64-bit Linux with 64-bit Instant Client:
```
$ file libclntsh.so.12.1 
libclntsh.so.12.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=068dc0a57c8b0310180f2a659b71de4115ba9020, not stripped
```
Note the x86-64 means it is a 64-bit Instant Client

**Comment by MichaelS11** [comment]
@mattn Close this?
