### ISSUE TITLE
fatal error: oci.h: No such file or directory

### ISSUE THREAD

**Issue by Keleir** [mattn/go-oci8#168]
There was a fatal error occurs when I executed `go get github.com/mattn/go-oci8` and copy `oci8.pc` file and then go get as follow:
```
go get -u github.com/iamseth/oracledb_exporter
```
The error details is: 
```
# github.com/iamseth/oracledb_exporter/vendor/github.com/mattn/go-oci8
/usr/local/golang/src/github.com/iamseth/oracledb_exporter/vendor/github.com/mattn/
go-oci8/oci8.go:4:17: fatal error: oci.h: No such file or directory
 #include <oci.h>
                 ^
compilation terminated.
```
And my go env is:
```
go version go1.6 linux/amd64
```

**Comment by Keleir** [comment]
Refer to: iamseth/oracledb_exporter#5

**Comment by mattn** [comment]
Did you install oracle client sdk?

**Comment by Keleir** [comment]
@mattn     I reinstall those oracle instant client with rpm pkg: 
```
oracle-instantclient-12.1-10.el7.cern.x86_64.rpm           
oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm     
oracle-instantclient12.1-meta-12.1-10.el7.cern.x86_64.rpm  
oracle-instantclient12.1-sqlplus-12.1.0.2.0-1.x86_64.rpm   
oracle-instantclient-tnsnames.ora-12.1-2.el7.cern.noarch.rpm
oracle-instantclient-basic-12.1-10.el7.cern.x86_64.rpm
oracle-instantclient-sqlplus-12.1-10.el7.cern.x86_64.rpm
oracle-instantclient-devel-12.1-10.el7.cern.x86_64.rpm
```
Package can be found at [here!](http://ftp.riken.jp/Linux/cern/centos/7/cernonly/x86_64/Packages/)

And then I re go get the `oracledb_exporter` it occurs this:
```
# github.com/iamseth/oracledb_exporter/vendor/github.com/mattn/go-oci8
/bin/ld: cannot find -lclntsh
collect2: error: ld returned 1 exit status
```
How to fix it ? Thanks!

**Comment by mattn** [comment]
Did you modify oci8.pc with your environment?

**Comment by Keleir** [comment]
I put it into `/usr/share/pkgconfig` and the content is：
```
prefix=/usr
includedir=${prefix}/include/oracle/12.1/client64
libdir=${prefix}/lib/oracle/12.1/client64/lib

Name: oci8
Description: Oracle Instant Client
Version: 12.1
Cflags: -I${includedir}
Libs: -L${libdir} -lclntsh
```
I didn't know what to change of `oci8.pc`.
My os is `el7.x86_64`

**Comment by mattn** [comment]
what you can see with `pkg-config --cflags --libs oci8` ? You can modify the includedir/libdir as match as your environment.

**Comment by Keleir** [comment]
$ pkg-config --cflags --libs oci8
```
-I/usr/include/oracle/12.1/client64  -L/usr/lib/oracle/12.1/client64/lib -lclntsh  
```
The output is as above.

**Comment by mattn** [comment]
you can find `/usr/lib/oracle/12.1/client64/lib/libclntsh*` ?

**Comment by mattn** [comment]
If not, please modify as match as your environment.

**Comment by Keleir** [comment]
@mattn  Thanks for your patience and help ! 
I have a try to install those rpm pkg and it works:
```
oracle-instantclient12.1-tools-12.1.0.2.0-1.x86_64.rpm 
oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
```
`rpm -ivh oracle-instantclient12.1-tools-12.1.0.2.0-1.x86_64.rpm oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm`

And then I look at the dir of `/usr/lib/oracle/12.1/client64/lib`, the `libclntsh.so` is here now:
```
libclntsh.so -> libclntsh.so.12.1
libclntshcore.so -> libclntshcore.so.12.1
```
Due to this, I `go get -u github.com/iamseth/oracledb_exporter` successed!
Thanks again ! :+1:
