### ISSUE TITLE
fatal error: oci.h: No such file or directory  #include <oci.h>

### ISSUE THREAD

**Issue by vijayks040** [mattn/go-oci8#171]
i tried getting the oracle library for go by typing 
go get github.com/mattn/go-oci8
Result: 
fatal error: oci.h: No such file or directory
 #include <oci.h>
          ^~~~~~~
compilation terminated.
go version go1.8.1 windows/amd64
i installed oracle instant client also
![image](https://user-images.githubusercontent.com/10988777/29965960-65a57598-8f2d-11e7-8270-8cbca7ae075d.png)
both sdk and basic
instantclient-basic-windows.x64-12.2.0.1.0.zip
instantclient-sdk-windows.x64-12.2.0.1.0.zip 
--

**Comment by vijayks040** [comment]
what may be going wrong...

**Comment by mattn** [comment]
please modify oci8.pc in $PKG_CONFIG_PATH to fit to your environment.

**Comment by vijayks040** [comment]
oci8.pc
prefix=/devel/target/1.0
exec_prefix=${prefix}
oralib=C:\instantclient_12_2\sdk\lib\msvc
orainclude=C:\instantclient_12_2\sdk\include
gcclib=C:\mingw64\lib
gccinclude=C:\mingw64\include
glib_genmarshal=glib-genmarshal
gobject_query=gobject-query
glib_mkenums=glib-mkenums

Name: oci8
Version: 12.2
Description: oci8 library
Libs: -L${oralib} -L${gcclib} -loci
Libs.private: 
Cflags: -I${orainclude} -I${gccinclude}
in image you can see i have set oci8.pc path as env variable, path is right
![image](https://user-images.githubusercontent.com/10988777/30012965-2573a306-9161-11e7-8c32-7489e2895e06.png)

**Comment by viper2pt0** [comment]
Any updates on this?  I'm having the exact same issue.  From what I can tell my oci8.pc and environment variables are all set appropriately.

**Comment by vijayks040** [comment]
set ldflags in your environment variables

**Comment by MichaelS11** [comment]
@mattn Close this?

**Comment by mattn** [comment]
If you still have this issue, please reopen this.
