### ISSUE TITLE
go-oci8 /usr/bin/ld: cannot find -lclntsh

### ISSUE THREAD

**Issue by vk1818** [mattn/go-oci8#172]
go get github.com/mattn/go-oci8
returns 
**go-oci8
/usr/bin/ld: cannot find -lclntsh
collect2: error: ld returned 1 exit status**
and my oci8.pc is 
`prefix=/devel/target/XXXXXXXXXXXXXXXXXXXXXXXXXX
exec_prefix=${prefix}
libdir=/usr/lib/oracle/12.2/client64/lib
includedir=/usr/include/oracle/12.2/client64

glib_genmarshal=glib-genmarshal
gobject_query=gobject-query
glib_mkenums=glib-mkenums

Name: oci8
Description: oci8 library
Libs: -L${libdir} -lclntsh
Cflags: -I${includedir}
Version: 12.2`
and go version is 
go version go1.6.2 linux/amd64

**Comment by vk1818** [comment]
-lclntsh is mentioned in oci8.pc

**Comment by mattn** [comment]
If you use oracle instant sdk, try `-loci` instead of `-lclntsh`. If you use oracle11, it should work with `-lclntsh`.

**Comment by vk1818** [comment]
@mattn 
i changed lclntsh to loci in oci8.pc but still it says
# github.com/mattn/go-oci8
/usr/bin/x86_64-w64-mingw32-ld: cannot find -lclntsh
collect2: error: ld returned 1 exit status

**Comment by mattn** [comment]
No. I mean `-loci`

**Comment by vk1818** [comment]
@mattn yes it says
/usr/bin/x86_64-w64-mingw32-ld: cannot find -loci

**Comment by vk1818** [comment]
@mattn is there anything else that i need to make changes in oci8.pc or in setting paths

**Comment by vk1818** [comment]
@mattn 
i really need this to be complete i appreciate your patience please help

**Comment by mattn** [comment]
Where you installed oracle instance SDK?

```
includedir=/usr/include/oracle/12.2/client64
```
This may be Linux version. You need to add Windows version.

**Comment by vk1818** [comment]
you mean  
![image](https://user-images.githubusercontent.com/31547727/30055670-d07f501e-924d-11e7-8d50-fc569c5317af.png)
oracle instant client for windows i should add in linux. Am i correct, please correct me if i am wrong

**Comment by vk1818** [comment]
@mattn  i followed https://help.ubuntu.com/community/Oracle%20Instant%20Client#Install_RPMs this link to install instant client for ubuntu

**Comment by mattn** [comment]
No! As I said in above, you MUST install Windows version NOT Linux version.

**Comment by vk1818** [comment]
@mattn but is it possible to install windows version in linux

**Comment by mattn** [comment]
Then please show me file list of Oracle instant client SDK for Windows which you installed on Ubuntu.

**Comment by vk1818** [comment]
@mattn  ohhh i could not find it, so now i will download sdk client for windows in my ubuntu system and will add path into oci8.pc, is this correct?

**Comment by mattn** [comment]
yep

**Comment by vk1818** [comment]
@mattn see following is my oci8.pc
#ckage Information for pkg-config

prefix=/devel/target/XXXXXXXXXXXXXXXXXXXXXXXXXX
exec_prefix=${prefix}
libdir=/usr/lib/oracle/12.2/client64/lib
includedir=/usr/include/oracle/12.2/client64

glib_genmarshal=glib-genmarshal
gobject_query=gobject-query
glib_mkenums=glib-mkenums

Name: oci8
Description: oci8 library
Libs: -L${libdir} -loci
Cflags: -I${includedir}
Version: 12.2
and now i have instantclient for windows in /usr/instantclient_12_2 both basic and sdk now what next need to be added in oci8.pc and ENV path

**Comment by mattn** [comment]
you must fix libdir, includedir, Libs in oci8.pc to point location to Oracle Instant SDK.

**Comment by mattn** [comment]
BTW, you don't need to install Oracle Instant Client SDK for Linux.

**Comment by vk1818** [comment]
@mattn man you saved my life, compilation successful i changed oci8.pc to point windows sdk file. cores of thanks and moreover thanks for your support and patience. Thanks for the help

**Comment by vk1818** [comment]
last one more thing please when i run my exe file in windows it crashed
telling PC=0x61fcc0
signal arrived during external code execution

github.com/mattn/go-oci8._Cfunc_WrapOCIEnvCreate(0xc000000001, 0x0, 0x0, 0x0, 0x0)
        github.com/mattn/go-oci8/_obj/_cgo_gotypes.go:796 +0x67

**Comment by mattn** [comment]
Your cross compiler is 32bit compiler. So you must install Oracle Instant Client SDK for Windows 32bit. Did you install 64bit version?

**Comment by vk1818** [comment]
@mattn  yes i installed 64 bit version

**Comment by vk1818** [comment]
@mattn  but my cross compiler is also 64 bit version and instant client also

**Comment by mattn** [comment]
I don't have enough time to answer for each your small questions.

**Comment by happilymarrieddad** [comment]
export LD_LIBRARY_PATH=/usr/lib/oracle/12.2/client64/lib
sudo apt install libaio

**Comment by ynishi** [comment]
Thanks about install issue, I'v made Dockerfile based on official golang image(debian:stretch).
https://github.com/ynishi/goora

**Comment by MichaelS11** [comment]
@mattn ,

Close this?
