### ISSUE TITLE
Switch-Case In ColumnTypeScanType() Always Returns Default []string

### ISSUE THREAD

**Issue by relloyd** [mattn/go-oci8#181]
If I try to dump the column types for a given SQL query using the `database/sql` approach below, the output of `ScanType()` is always `[]string`, when it should be more specific for NUMBERs and DATEs etc.

### Sample Code To Reproduce The Issue
```
...
res, err := db.Query(`select 1 as myint, 'text' as mystring, sysdate as mydate from dual`)
if err != nil {
	panic("Oops, borked with SQL error:", err)
}
colTypes, err := res.ColumnTypes()
if err != nil {
	panic("Oops, borked getting column types.", err)
}
for idx := 0; idx < len(colTypes); idx++ {
	fmt.Println("col idx=", idx, "; DatabaseTypeName=", colTypes[idx].DatabaseTypeName(), "; ScanTypeName=", colTypes[idx].ScanType())

}
```

### Possible Fix For The Issue

It appears that the default switch-case is always followed in `oci8.go` function `ColumnTypeScanType()`.

I found the following code snippet in ColumnTypeDatabaseTypeName() that can be added to ColumnTypeScanType() before `tpr` is created:

```
// New code...
rp := C.WrapOCIParamGet(rc.s.s, C.OCI_HTYPE_STMT, (*C.OCIError)(rc.s.c.err), C.ub4(i+1))
if rp.rv == C.OCI_SUCCESS {
	p = rp.ptr
}
// End new code.
tpr := C.WrapOCIAttrGetUb2(p, C.OCI_DTYPE_PARAM, C.OCI_ATTR_DATA_TYPE, (*C.OCIError)(rc.s.c.err))
...
```

**Comment by relloyd** [comment]
I'm happy to submit a PR to try and fix this, but I'm not entirely clear if the suggested call to `C.WrapOCIParamGet()` will break anything else.

**Comment by mattn** [comment]
Could you please send me pull-request.

**Comment by relloyd** [comment]
Hi, hope you're well.

Can you give my user 'relloyd' privs to create a branch?

$ git push --set-upstream origin column-type-scan-type-fix-issue-181
remote: Permission to mattn/go-oci8.git denied to relloyd.


Cheers,
Richard





On Tue, 3 Oct 2017, at 01:45, mattn wrote:
> Could you please send me pull-request.


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/mattn/go-oci8/issues/181#issuecomment-333706072

**Comment by relloyd** [comment]
This looks like it's resolved now.  Many thanks for picking it up.
