### ISSUE TITLE
Golang 1.9 Darwin can not build when importing go-oci8

### ISSUE THREAD

**Issue by hurrycaine** [mattn/go-oci8#183]
This was working with 1.7 and 1.8
    
    import(
         _ "github.com/mattn/go-oci8"
    )

Using homebrew to upgrade to 1.9, not experiencing any other issues. The postgres (pq) I am using the same way and I am not experiencing any errors.

Anyone using go-oci8 with 1.9 ?

```/usr/local/Cellar/go/1.9/libexec/pkg/tool/darwin_amd64/link: /usr/local/Cellar/go/1.9/libexec/pkg/tool/darwin_amd64/link: running dsymutil failed: signal: abort trap
error: invalid abbreviation code [110] for DIE at 0x000bf61e in '/var/folders/r1/m9b16lj133v0x_t6y4l8cl_rsc0ff7/T/go-link-053359544/go.o'
Assertion failed: (ref_addr_die != NULL), function AppendDependants, file /SourceCache/dwarf_utilities/dwarf_utilities-121.1/source/DWARFDebugInfoEntry.cpp, line 375.
```

Thanks

**Comment by pvelder** [comment]
I'm using go-oci8 with go 1.9. 

    $ go version 
    go1.9 darwin/amd64

Installed it with homebrew as well. 

    $ brew list go
    /usr/local/Cellar/go/1.9/bin/go
    /usr/local/Cellar/go/1.9/bin/godoc
    /usr/local/Cellar/go/1.9/bin/gofmt
    /usr/local/Cellar/go/1.9/libexec/api/ (13 files)
    /usr/local/Cellar/go/1.9/libexec/bin/ (3 files)
    /usr/local/Cellar/go/1.9/libexec/doc/ (152 files)
    /usr/local/Cellar/go/1.9/libexec/lib/ (3 files)
    /usr/local/Cellar/go/1.9/libexec/misc/ (325 files)
    /usr/local/Cellar/go/1.9/libexec/pkg/ (938 files)
    /usr/local/Cellar/go/1.9/libexec/src/ (4491 files)
    /usr/local/Cellar/go/1.9/libexec/test/ (1700 files)
    /usr/local/Cellar/go/1.9/libexec/ (6 files)

I don't have any issues.

I'm still on OS X ElCapitan 10.11.6

Xcode version: 

    $ xcrun --version
    xcrun version 31.

May be this link can help ? 
https://stackoverflow.com/questions/22342224/unity-4-3-4f1-and-xcode-5-1#22539806

**Comment by hurrycaine** [comment]
Thanks @pvelder 

I am on Yosemite (really need to upgrade) and xcode version 23 (AKA 6.4).
My brew list is identical to yours.

I update xcode to the highest it can go for OSX 10.10, which I think is Xcode 7.2 (AKA version 28) ( from the developer's site. 

Luckily, this resolved my issue! 

Thanks!
