### ISSUE TITLE
No rows as select * from V$RECOVERY_FILE_DEST

### ISSUE THREAD

**Issue by ampcode666** [mattn/go-oci8#184]
With user which have all needed privileges select * from V$RECOVERY_FILE_DEST; returns no results
While the same user from Oracle SQL Develeoper or sqlplus64 provide a row.
The same situation with (also connected with FRA) view v$flash_recovery_area_usage.
Other oracle built in views work.

**Comment by mattn** [comment]
What do you mean no rows? I cound select the query.

```go
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/mattn/go-oci8"
)

func main() {
	db, err := sql.Open("oci8", "scott/tiger@XE")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	var v1, v2, v3, v4 float64
	err = db.QueryRow(`
	select space_limit, space_used, space_reclaimable, number_of_files from V$RECOVERY_FILE_DEST
	`).Scan(&v1, &v2, &v3, &v4)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(v1, v2, v3, v4)
}
```

**Comment by ampcode666** [comment]
I'm terribly sorry, I used outdated version. It works fine thank you very much.
