### ISSUE TITLE
Support sql.Out for stored procedures

### ISSUE THREAD

**Issue by veqryn** [mattn/go-oci8#188]
I have a stored procedure that requires an 'out' parameter.
I am attempting to access it like so:
```go
	var outVar interface{}
	result, err := conn.Exec("begin myuser.get_regexs(:v1); end;", sql.Out{Dest: &outVar})
```

This gives me the following error: `sql: converting argument $1 type: unsupported type sql.Out, a struct`

The stored procedure looks approximately like this:
```sql
PROCEDURE get_regexs( o_csr OUT o_as_cur) IS
BEGIN
  IF (o_csr%ISOPEN) THEN
    CLOSE o_csr;
  END IF;
  OPEN o_csr FOR
    SELECT
      t1.regexp_id,
      t1.regexp,
      t1.other_id,
      t1.regexp_match_type
    FROM
      my_regexp_t t1
    WHERE
     t1.status = 1;;
END;
```

And here is approximately the perl code I am trying to migrate to golang:
```perl
        my $regex_sth = $dbh->prepare(
            'begin myuser.get_regexs(:v1); end;'
        );
        $regex_sth->bind_param_inout(':v1', \$csr, 0, { ora_type => ORA_RSET });
        $regex_sth->execute();
        while ( my @rx_info = $csr->fetchrow_array() ) {
            # stuff...
        }
        $regex_sth->finish();
```

If this driver already supports this, can you please tell me what I am doing wrong, and how I should access the info once it is in outVar (and what type outVar should be)?
If not, then can support be added for this?

**Comment by brianmoran** [comment]
Just curious, how are you preparing the statement?

**Comment by veqryn** [comment]
Not sure exactly what you mean, but we have a whole ton of stored procedures created by our DBA.  They already exist in our Oracle instance.

**Comment by brianmoran** [comment]
https://golang.org/pkg/database/sql/#DB.Prepare

I use the Prepare function to define my stored procedure initially and then when I want to execute it, I just used the Exec function. I have not used this with stored functions that return out params yet. 

Have you tried just passing in another type as your return instead of the sql.Out{}?

**Comment by 242617** [comment]
@veqryn , have you found the solution?
I have the same issue.

**Comment by veqryn** [comment]
The solution so far has been to switch to https://github.com/go-goracle/goracle
It supports golang 1.9 database mechanisms for out parameters.

**Comment by mattn** [comment]
go-oci8 already support Out parameter.

**Comment by mattn** [comment]
Sorry, I forgot to enable Out parameter on release of go18.

Now enabled. https://github.com/mattn/go-oci8/commit/c9d060fecdb25c51e273e649f6e84225f1b99733

**Comment by 242617** [comment]
@mattn, the new version doesn't return anything in my case. Whereas goracle does.
My query is something like this:
```
BEGIN
	DEV.MESSAGES.UPDATE(
		PI_PRS_ID   => :1,
		PI_FW_ID    => :2,
		PI_TRM_IDS  => DEV.IDS_TAB(:3),
		PO_CNT      => :4 -- output
	);
END;
```
And code is:
```
var count int
res, err = model.DevExec(query, prsID, fwID, trmID, sql.Out{Dest: &count})
```

goracle makes _count_ to be 1 (wich is expected). And go-oci8 make no change to count in my case.

**Comment by mattn** [comment]
Currently, go-oci8 require sql.Named for Out parameter.

**Comment by mattn** [comment]
I updated code. Could you please try in latest. I added example using dbms_output.

**Comment by mattn** [comment]
Sorry, still wrong. Will fox.

**Comment by mattn** [comment]
Also fixed to be no-required sql.Named for Out parameter.

**Comment by 242617** [comment]
Works fine! Thank you! :thumbsup:

**Comment by 242617** [comment]
I've found another bug.
I have got query:
```
DECLARE
	PRS_ID NUMBER;
	AGT_ID NUMBER;
BEGIN
	PRS_ID := :1;
	AGT_ID := :2;
	INSERT INTO NAVIGATE (PRS_ID, AGT_ID) VALUES (P_PRS_ID, P_AGT_ID) RETURNING UIN_ID INTO :3;
END;
```
And code
```
var id uint64
_, err = StatExec(query, 123, 321, sql.Out{Dest: &id})
```
doen't change the id (_goracle_ changes). But if _id_ is _int_ it's changed!
So it's likely there is a casting error.

**Comment by MichaelS11** [comment]
Is this still an issue?

**Comment by MichaelS11** [comment]
@mattn Close this?

**Comment by mattn** [comment]
#201 #206 is closed. Please reopen you still have issue and it is related on go-oci8.

**Comment by dbalamo** [comment]
Hello, 
I'm still experiencing the same issue described above, using Oracle 12.
I have this stored Procedure, which returns a sys_refcursor : 

```
create or replace PROCEDURE PROCSELECTDIPCURSOR2
( 
  outcur OUT SYS_REFCURSOR
) AS
    
BEGIN            
    OPEN outcur FOR SELECT PERSON_ID, FIRST_NAME,LAST_NAME from DIPENDENTI where LAST_NAME LIKE 'T%';    
END PROCSELECTDIPCURSOR2;
```

and the GO code calling the stored procedure is this : 

```
func main() {
	db, err := sql.Open("oci8", "user/password@localhost:1521/orclsid")
	if err != nil {
		log.Fatal(fmt.Errorf("ERROR OPEN - %w", err))
	}
	defer db.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		log.Fatal(fmt.Errorf("ERROR BeginTx - %w", err))
		log.Fatal(err)
	}
	defer tx.Commit()

	var dr interface{}
	qry := "BEGIN PROCSELECTDIPCURSOR2(:outcur); END;"

	_, sqlErr := tx.ExecContext(ctx, qry, sql.Out{Dest: &dr})
	if sqlErr != nil {
		log.Fatal(sqlErr)
	} else {
		fmt.Println("Went OK")
	}
}
```

I've tried using interface, sql.Rows and driver.Rows as return variable for the sys_refcursor, but no luck , it keeps saying

**PLS-00306: wrong number or types of arguments in call to 'PROCSELECTDIPCURSOR2'** .

The code above works ok if I call a stored procedure returning base types (a number, for example).
Is the sql.Out support still missing something about cursors, or it's my fault?

Thanks
