### ISSUE TITLE
Upgrading to go1.9 causes build failure on windows.

### ISSUE THREAD

**Issue by delaneyj** [mattn/go-oci8#191]
Working environment with Windows 10 pro and MinGW + oci.  When moving from go 1.8 to 1.9 get build failures starting with `Exception go-oci8._Cfunc_WrapOCIEnvCreate`.  Did something get deprecated?

**Comment by mattn** [comment]
I don't get fail on go1.9 and go/master.

**Comment by MichaelS11** [comment]
@mattn 
Close this?

**Comment by mattn** [comment]
Please reopen this if you still have issue on go1.9 or later.
