### ISSUE TITLE
Not able to use oracle db with golang

### ISSUE THREAD

**Issue by AmanPatelcubastion** [mattn/go-oci8#192]
I have installed MinGW , pkg-config and oracle instant client , I have also set the environment variables . I am getting this error when i run a program using the go-oci8 package . 

# github.com/mattn/go-oci8
C:/oracle_instantclient_12.1/sdk/lib/msvc/oci.lib: error adding symbols: File in wrong format
collect2.exe: error: ld returned 1 exit status

Kindly Help

**Comment by mattn** [comment]
please find your issue from https://github.com/mattn/go-oci8/search?q=File+in+wrong+format&type=Issues&utf8=%E2%9C%93

**Comment by MichaelS11** [comment]
@mattn Close this?
