### ISSUE TITLE
Getting /usr/lib/ld: cannot find -loci while building project

### ISSUE THREAD

**Issue by teros0** [mattn/go-oci8#193]
Hi.
I'm aware of [this](https://github.com/mattn/go-oci8/issues/172) issue, but answers provided there don't help to fix my situation.
Trying to build a program with go-oci8, getting this error. I've installed oracle instant client and sdk for windows64 and referenced it in oci8.pc: 

**/usr/lib/pkgconfig/oci.pc**
prefix=/home/compile/instantclient_12_2_64
libdir=${prefix}/sdk/lib/msvc
includedir=${prefix}/sdk/include
Name: OCI
Description: Oracle database engine
Version: 12.2
Libs: -L${libdir} -loci
Libs.private:
Cflags: -I${includedir}

**Output of pkg-config:**
$ pkg-config --cflags oci8
-I/home/compile/instantclient_12_2_64/sdk/include
$ pkg-config --libs oci8
-L/home/compile/instantclient_12_2_64/sdk/lib/msvc -loci

**Content of lib/msvc**
$ ls $ORACLE_HOME/lib/msvc
oci.lib  ociw32.lib  oramysql12.lib  oraocci12d.lib  oraocci12.lib  vc14

**Output of go get -x github.com/mattn/go-oci8:**
$ go get -x github.com/mattn/go-oci8
WORK=/tmp/go-build392069997
mkdir -p $WORK/github.com/mattn/go-oci8/_obj/
mkdir -p $WORK/github.com/mattn/
cd /home/compile/go/src/github.com/mattn/go-oci8
pkg-config --cflags oci8
pkg-config --libs oci8
CGO_LDFLAGS="-g" "-O2" "-L/home/compile/instantclient_12_2_64/sdk/lib/msvc" "-loci" /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/github.com/mattn/go-oci8/_obj/ -importpath github.com/mattn/go-oci8 -- -I/home/compile/instantclient_12_2_64/sdk/include -I $WORK/github.com/mattn/go-oci8/_obj/ -g -O2 oci8.go
cd $WORK
gcc -fdebug-prefix-map=a=b -c trivial.c
gcc -gno-record-gcc-switches -c trivial.c
cd $WORK/github.com/mattn/go-oci8/_obj
gcc -I /home/compile/go/src/github.com/mattn/go-oci8 -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -I/home/compile/instantclient_12_2_64/sdk/include -I ./ -g -O2 -o ./_cgo_export.o -c _cgo_export.c
gcc -I /home/compile/go/src/github.com/mattn/go-oci8 -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -I/home/compile/instantclient_12_2_64/sdk/include -I ./ -g -O2 -o ./oci8.cgo2.o -c oci8.cgo2.c
gcc -I /home/compile/go/src/github.com/mattn/go-oci8 -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -I/home/compile/instantclient_12_2_64/sdk/include -I ./ -g -O2 -o ./_cgo_main.o -c _cgo_main.c
cd /home/compile/go/src/github.com/mattn/go-oci8
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -o $WORK/github.com/mattn/go-oci8/_obj/_cgo_.o $WORK/github.com/mattn/go-oci8/_obj/_cgo_main.o $WORK/github.com/mattn/go-oci8/_obj/_cgo_export.o $WORK/github.com/mattn/go-oci8/_obj/oci8.cgo2.o -g -O2 -L/home/compile/instantclient_12_2_64/sdk/lib/msvc -loci
# github.com/mattn/go-oci8
/usr/bin/ld: cannot find -loci
collect2: error: ld returned 1 exit status

What am I missing?
Thanks.

**Comment by majijia505** [comment]
if your os is unix/linux ,please fix -loci to  -lclntsh -lnnz11
my oci8.pc is like that:
libdir=XXXX
includedir=XXX

glib_genmarshal=glib-genmarshal
gobject_query=gobject-query
glib_mkenums=glib-mkenums

Name: oci8
Description: oci8 library
Libs: -L${libdir} -lclntsh -lnnz11
Cflags: -I${includedir}
Version: 11.2

**Comment by teros0** [comment]
Tried your suggestion, but still can't get builder to find libs.
~/go/src/ora$ **go build**
# github.com/mattn/go-oci8
/usr/bin/ld: cannot find -lclntsh
/usr/bin/ld: cannot find -lnnz11
collect2: error: ld returned 1 exit status

**go get -x github.com/mattn/go-oci8**
WORK=/tmp/go-build750998062
mkdir -p $WORK/github.com/mattn/go-oci8/_obj/
mkdir -p $WORK/github.com/mattn/
cd /home/compile/go/src/github.com/mattn/go-oci8
pkg-config --cflags oci8
pkg-config --libs oci8
CGO_LDFLAGS="-g" "-O2" "-L/home/compile/instantclient_12_2_64/sdk/lib/msvc" "-lclntsh" "-lnnz11" /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/github.com/mattn/go-oci8/_obj/ -importpath github.com/mattn/go-oci8 -- -I/home/compile/instantclient_12_2_64/sdk/include -I $WORK/github.com/mattn/go-oci8/_obj/ -g -O2 oci8.go
cd $WORK
gcc -fdebug-prefix-map=a=b -c trivial.c
gcc -gno-record-gcc-switches -c trivial.c
cd $WORK/github.com/mattn/go-oci8/_obj
gcc -I /home/compile/go/src/github.com/mattn/go-oci8 -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -I/home/compile/instantclient_12_2_64/sdk/include -I ./ -g -O2 -o ./_cgo_export.o -c _cgo_export.c
gcc -I /home/compile/go/src/github.com/mattn/go-oci8 -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -I/home/compile/instantclient_12_2_64/sdk/include -I ./ -g -O2 -o ./oci8.cgo2.o -c oci8.cgo2.c
gcc -I /home/compile/go/src/github.com/mattn/go-oci8 -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -I/home/compile/instantclient_12_2_64/sdk/include -I ./ -g -O2 -o ./_cgo_main.o -c _cgo_main.c
cd /home/compile/go/src/github.com/mattn/go-oci8
gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -o $WORK/github.com/mattn/go-oci8/_obj/_cgo_.o $WORK/github.com/mattn/go-oci8/_obj/_cgo_main.o $WORK/github.com/mattn/go-oci8/_obj/_cgo_export.o $WORK/github.com/mattn/go-oci8/_obj/oci8.cgo2.o -g -O2 -L/home/compile/instantclient_12_2_64/sdk/lib/msvc -lclntsh -lnnz11
# github.com/mattn/go-oci8
/usr/bin/ld: cannot find -lclntsh
/usr/bin/ld: cannot find -lnnz11
collect2: error: ld returned 1 exit status

**Comment by majijia505** [comment]
if your oracle instant client is 11.1 or later 
you can find a file libclntsh.so.11.1 like this  in you oracle instant client directory,  
ln -s libclntsh.so.11.1 libclntsh.so
you may find it in /home/compile/instantclient_12_2_64/sdk/lib/msvc 

if you instant client is 10.X ,remove -lnnz11
you can try it again ~~

my oracle instant client like this (redhat-linux 6.5)
.
├── adrci
├── BASIC_README
├── genezi
├── libclntsh.a
├── libclntsh.so -> /data/infpush/majj/oracle_client/libclntsh.so.11.1
├── libclntsh.so.11.1
├── libnnz11.so
├── libocci.so.11.1
├── libociei.so
├── libocijdbc11.so
├── ojdbc5.jar
├── ojdbc6.jar
├── sdk
│   ├── demo
│   │   ├── cdemo81.c
│   │   ├── demo.mk
│   │   ├── occidemod.sql
│   │   ├── occidemo.sql
│   │   ├── occidml.cpp
│   │   ├── occiobj.cpp
│   │   └── occiobj.typ
│   ├── include
│   │   ├── ldap.h
│   │   ├── nzerror.h
│   │   ├── nzt.h
│   │   ├── occiAQ.h
│   │   ├── occiCommon.h
│   │   ├── occiControl.h
│   │   ├── occiData.h
│   │   ├── occi.h
│   │   ├── occiObjects.h
│   │   ├── oci1.h
│   │   ├── oci8dp.h
│   │   ├── ociap.h
│   │   ├── ociapr.h
│   │   ├── ocidef.h
│   │   ├── ocidem.h
│   │   ├── ocidfn.h
│   │   ├── ociextp.h
│   │   ├── oci.h
│   │   ├── ocikpr.h
│   │   ├── ocixmldb.h
│   │   ├── ocixstream.h
│   │   ├── odci.h
│   │   ├── oratypes.h
│   │   ├── orid.h
│   │   ├── ori.h
│   │   ├── orl.h
│   │   ├── oro.h
│   │   ├── ort.h
│   │   └── xa.h
│   ├── ott
│   ├── ottclasses.zip
│   └── SDK_README
├── uidrvci
└── xstreams.jar

**Comment by teros0** [comment]
Woah, thank you so much.
I've completely misread the issue referenced at the beginning of this thread: thought that you should use windows oracle instant client even when compiling for linux. Changed client, linked .so files to /usr/lib and finally build test project.

If you don't mind, I have one more question.
Running binary successfully requires libclntsh.so.* file. On Windows, I've simply put required .dll to the folder, where the executable lied, but on Linux it didn't work, so I've exported LD_LIBRARY_PATH env variable to point to the instant client and it worked.
So the question is, is it possible to run Linux binaries without editing LD_LIBRARY_PATH, just by putting .so file next to the binary?

**Comment by majijia505** [comment]
i guess the program On Windows will find dll files in the current directory by default ,Linux will not do this 
if you set "export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH" may be it can works.

**Comment by teros0** [comment]
Yes, I suppose it's the only way.
You've helped me a lot, thanks.
