### ISSUE TITLE
windows7 build fail

### ISSUE THREAD

**Issue by jicg** [mattn/go-oci8#195]
When I use "github.com/andlabs/ui", compile error. However, I do not use "github.com/andlabs/ui", compiled through.
```go
C:\app\go\goroot\pkg\tool\windows_386\link.exe: running g++ failed: exit status 1
C:/app/mingw-w64/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -loci
collect2.exe: error: ld returned 1 exit status
 
```

**Comment by mattn** [comment]
You need to fix oci8.pc

**Comment by jicg** [comment]
Thanks, how can I fix it ？

**Comment by mattn** [comment]
Please modify below to match as your environment.

```
Libs: -L${libdir} -lclntsh
Cflags: -I${includedir}
```

**Comment by jicg** [comment]
Thanks, it does not work, I can not find the reason, so I plan to use "github.com/lxn/walk/".

**Comment by mattn** [comment]
What? walk is GUI library not database driver.

**Comment by jicg** [comment]
My point is: when I use gui "github.com/andlabs/ui", I reference go-oci8 compilation errors, but I use other gui libraries (eg "github.com/lxn/walk","github.com/ zserge / webview "), quoted go-oci8 compiler passed. This question is so weird

**Comment by robinsoon** [comment]
github.com/jzaikovs/ora   
This is written by pure go. It works well at present.

**Comment by MichaelS11** [comment]
It is not pure Go, it is cgo. It is using https://github.com/rainycape/dl which loads the Oracle instant client which is written in C

**Comment by robinsoon** [comment]
It using package syscall.  
syscall.NewLazyDLL("oci.dll")

**Comment by mattn** [comment]
https://github.com/rainycape/dl/blob/1b01514224a1a60a6bcbb0b6b9d3a00ec14ae17f/dl.go#L6

**Comment by MichaelS11** [comment]
@mattn Can you lock this thread?
