### ISSUE TITLE
"driver: bad connection" when running on windows  (not on macos)

### ISSUE THREAD

**Issue by pvelder** [mattn/go-oci8#196]
While running code:

    package main
    
    import (
    	"database/sql"
    	"fmt"
    	"log"
    
    	_ "github.com/mattn/go-oci8"
    )
    
    func main() {
    	db, err := sql.Open("oci8", "myuser/mypassword@//host.on.domain:1521/SID")
    	if err != nil {
    		log.Println("error in Open")
    		log.Fatal(err)
    	}
    	defer db.Close()
    
    	row := db.QueryRow("select 'test' from dual")
    	fmt.Printf("row: %v\n", row)
    
    	var result string
    	err = row.Scan(&result)
    	if err != nil {
    		log.Fatalf("Scan fails, err: %v", err)
    	}
    	fmt.Printf("result: %v\n", result)
    
    }

On my macbook, it runs fine: 

    $ go run main.go
    row: &{<nil> 0xc4200b8080}
    result: test

But running on windows, the same code fails as follows: 

    Z:\dev\src\github.com\pvelder\testosdb>go run main
    row: &{0xc0420461e0 <nil>}
    2018/02/20 15:25:38 Scan fails, err: driver: bad connection

Compilation works fine on both platforms: 

    Z:\dev\src\github.com\pvelder\testosdb>go build

    Z:\dev\src\github.com\pvelder\testosdb>dir
     Volume in drive Z is Shared Folders
     Volume Serial Number is 0000-0064

     Directory of Z:\dev\src\github.com\pvelder\testosdb

    02/20/2018  03:35 PM    <DIR>          .
    02/20/2018  01:50 PM    <DIR>          ..
    02/20/2018  03:20 PM               610 main.go
    02/20/2018  03:35 PM         3,538,865 testosdb.exe
                   2 File(s)      3,541,447 bytes

Already tried to upgrade to go 1.10. Same problem...

Any idea ?

**Comment by mattn** [comment]
Can you try to login via sqlplus on Windows?

**Comment by pvelder** [comment]
Thanks @mattn 

sqlplus on windows was indeed not accepting the  [EZCONNECT](http://www.orafaq.com/wiki/EZCONNECT) syntax for the connect string: 

    F:\transport>sqlplus orastudio/orastudio@//is001s020.ilias.local:1521/HADES
    
    SQL*Plus: Release 11.1.0.7.0 - Production on Wed Feb 21 07:15:27 2018
    
    Copyright (c) 1982, 2008, Oracle.  All rights reserved.
    
    ERROR:
    ORA-12154: TNS:could not resolve the connect identifier specified
    
    
    Enter user-name:
    ERROR:
    ORA-12560: TNS:protocol adapter error

So I modified sqlnet.ora to accept EZCONNECT as well: 

    NAMES.DIRECTORY_PATH= (EZCONNECT,TNSNAMES)

Which made the sqlplus connection work on windows as well: 

I reworked the test program ([as shown in this gist](https://gist.githubusercontent.com/pvelder/b8c0cd045719c04630e351b6bbf5e813/raw/90fd3872b62245789ce30c9448da9bbb65930c26/main.go)) with different kinds of connectstrings (with and without tnsentry, and with and without ezconnect syntax).

Running the test program initially failed for the ezconnect syntaxes:

    F:\transport>testosdb.exe
    WORKS connecting as 'orastudio/orastudio@(description=(address_list=(address=(protocol=TCP)(host=is001s020.ilias.local)(port=1521)    ))(connect_data=(service_name=HADES)))'
    WORKS connecting as 'orastudio/orastudio@HADES'
    FAILS connecting as 'orastudio/orastudio@//is001s020.ilias.local:1521/HADES' with error 'ping failed'
    FAILS connecting as 'orastudio/orastudio@is001s020.ilias.local:1521/HADES' with error 'ping failed'
   
But after pointing the TNS_ADMIN environment variable to the sqlnet.ora folder, all went fine:
 
    F:\transport>set TNS_ADMIN=D:\OFM
    F:\transport>testosdb.exe
    WORKS connecting as 'orastudio/orastudio@(description=(address_list=(address=(protocol=TCP)(host=is001s020.ilias.local)(port=1521)    ))(connect_data=(service_name=HADES)))'
    WORKS connecting as 'orastudio/orastudio@HADES'
    WORKS connecting as 'orastudio/orastudio@//is001s020.ilias.local:1521/HADES'
    WORKS connecting as 'orastudio/orastudio@is001s020.ilias.local:1521/HADES'

Thanks again for pointing me in the right direction. 
And thanks for enabling [Out parameter](https://github.com/mattn/go-oci8/commit/c9d060fecdb25c51e273e649f6e84225f1b99733).  Using it already ;-)
