### ISSUE TITLE
go 1.10 with go-oci8 crash on Windows

### ISSUE THREAD

**Issue by pvelder** [mattn/go-oci8#197]
After compiling one of our utilities using go-oci8 on windows using a go1.9.4.windows-amd64.msi installation, I can run the code successfully: 

    F:\transport>transport-go1.9.4.exe -config F:\transport\config.yaml
    TNS_ADMIN=D:/ofm
    ------ Queried projectname: Ilias 22 for ID 1065
    ---- vc_util.releasecontext result: {0xc042316e00 0xc0420309c0}
    --- 11:37:09 deferred orastudioDb.Close()

After compiling the exact same code using go1.10.windows-amd64.msi, the code crashes with following dump: 

    F:\transport>transport-go1.10.0.exe -config F:\transport\config.yaml
    TNS_ADMIN=D:/ofm
    ------ Queried projectname: Ilias 22 for ID 1065
    ---- vc_util.releasecontext result: {0xc042115380 0xc042392300}
    --- 11:35:12 deferred orastudioDb.Close()
    Exception 0xc0000005 0x0 0x1602438 0x41b457a
    PC=0x41b457a
    
    runtime: unknown pc 0x41b457a
    stack: frame={sp:0x377fa60, fp:0x0} stack=[0x3581ed0,0x377fed0)
    000000000377f960:  0000000000000000  0000000000000000
    000000000377f970:  000005c0fffffb30  000004d0fffffb30
    000000000377f980:  00000000000000f0  0000000000000000
    000000000377f990:  00000000c0000005  0000000000000000
    000000000377f9a0:  00000000041b457a  0000000000000002
    000000000377f9b0:  0000000000000000  0000000001602438
    000000000377f9c0:  0000000000000000  0000000000000000
    000000000377f9d0:  0000000000000000  0000000000000000
    000000000377f9e0:  0000000000000000  0000000000000000
    000000000377f9f0:  0000000000000000  0000000000000000
    000000000377fa00:  0000000000000000  0000000000000000
    000000000377fa10:  0000000000000000  0000000000000000
    000000000377fa20:  0000000000000000  0000000000000000
    000000000377fa30:  00000000041b457a  0000000000000000
    000000000377fa40:  0000000000000000  000000000377fa60
    000000000377fa50:  0000000000000000  0000000000000000
    000000000377fa60: <0000000000000000  0000000000000000
    000000000377fa70:  0000000000000000  0000000000000000
    000000000377fa80:  0000000000000000  0000000000000000
    000000000377fa90:  0000000001602438  0000000000000000
    000000000377faa0:  0000000000000000  0000000000000000
    000000000377fab0:  0000000000000000  0000000000000000
    000000000377fac0:  0000000000000000  000007fefd02133c
    000000000377fad0:  0000000000000000  0000000000000000
    000000000377fae0:  0000000000000000  0000000000000000
    000000000377faf0:  0000000000003000  0000000000458a1e <runtime.asmstdcall+94>
    000000000377fb00:  0000000000000000  0000000000458a1e <runtime.asmstdcall+94>
    000000000377fb10:  0000000002dc0000  0000000000010000
    000000000377fb20:  0000000000000000  0000000000000000
    000000000377fb30:  0000000000000000  0000000000000000
    000000000377fb40:  0000000000000000  0000000000000000
    000000000377fb50:  0000000000000000  0000000000000000
    runtime: unknown pc 0x41b457a
    stack: frame={sp:0x377fa60, fp:0x0} stack=[0x3581ed0,0x377fed0)
    000000000377f960:  0000000000000000  0000000000000000
    000000000377f970:  000005c0fffffb30  000004d0fffffb30
    000000000377f980:  00000000000000f0  0000000000000000
    000000000377f990:  00000000c0000005  0000000000000000
    000000000377f9a0:  00000000041b457a  0000000000000002
    000000000377f9b0:  0000000000000000  0000000001602438
    000000000377f9c0:  0000000000000000  0000000000000000
    000000000377f9d0:  0000000000000000  0000000000000000
    000000000377f9e0:  0000000000000000  0000000000000000
    000000000377f9f0:  0000000000000000  0000000000000000
    000000000377fa00:  0000000000000000  0000000000000000
    000000000377fa10:  0000000000000000  0000000000000000
    000000000377fa20:  0000000000000000  0000000000000000
    000000000377fa30:  00000000041b457a  0000000000000000
    000000000377fa40:  0000000000000000  000000000377fa60
    000000000377fa50:  0000000000000000  0000000000000000
    000000000377fa60: <0000000000000000  0000000000000000
    000000000377fa70:  0000000000000000  0000000000000000
    000000000377fa80:  0000000000000000  0000000000000000
    000000000377fa90:  0000000001602438  0000000000000000
    000000000377faa0:  0000000000000000  0000000000000000
    000000000377fab0:  0000000000000000  0000000000000000
    000000000377fac0:  0000000000000000  000007fefd02133c
    000000000377fad0:  0000000000000000  0000000000000000
    000000000377fae0:  0000000000000000  0000000000000000
    000000000377faf0:  0000000000003000  0000000000458a1e <runtime.asmstdcall+94>
    000000000377fb00:  0000000000000000  0000000000458a1e <runtime.asmstdcall+94>
    000000000377fb10:  0000000002dc0000  0000000000010000
    000000000377fb20:  0000000000000000  0000000000000000
    000000000377fb30:  0000000000000000  0000000000000000
    000000000377fb40:  0000000000000000  0000000000000000
    000000000377fb50:  0000000000000000  0000000000000000
    
    goroutine 18 [syscall]:
    github.com/mattn/go-oci8._Cfunc_OCIHandleFree(0x1602438, 0x4, 0x0)
            _cgo_gotypes.go:504 +0x54
    github.com/mattn/go-oci8.(*OCI8Stmt).Close.func1(0x1602438, 0xc000000004, 0x0)
            Z:/dev/src/github.com/mattn/go-oci8/oci8.go:942 +0x65
    github.com/mattn/go-oci8.(*OCI8Stmt).Close(0xc04205dd80, 0x0, 0x0)
            Z:/dev/src/github.com/mattn/go-oci8/oci8.go:942 +0x74
    
    goroutine 1 [chan receive]:
    github.com/kardianos/service.(*windowsService).Run(0xc042145e90, 0xa3f8c8, 0xc042097b00)
            Z:/dev/src/github.com/kardianos/service/service_windows.go:273 +0x139
    main.main()
            Z:/dev/src/github.com/pvelder/transport/main.go:80 +0x656
    
    goroutine 19 [syscall]:
    os/signal.signal_recv(0x0)
            D:/Go/src/runtime/sigqueue.go:139 +0xad
    os/signal.loop()
            D:/Go/src/os/signal/signal_unix.go:22 +0x29
    created by os/signal.init.0
            D:/Go/src/os/signal/signal_unix.go:28 +0x48
    
    goroutine 20 [chan receive]:
    main.main.func1(0xc042097b00)
            Z:/dev/src/github.com/pvelder/transport/main.go:64 +0x44
    created by main.main
            Z:/dev/src/github.com/pvelder/transport/main.go:62 +0x4f3
    
    goroutine 21 [IO wait]:
    internal/poll.runtime_pollWait(0x135d3d0, 0x72, 0xa84fc0)
            D:/Go/src/runtime/netpoll.go:173 +0x5e
    internal/poll.(*pollDesc).wait(0xc0420cf508, 0x72, 0xd9a400, 0x0, 0x0)
            D:/Go/src/internal/poll/fd_poll_runtime.go:85 +0xa2
    internal/poll.(*ioSrv).ExecIO(0xdf9b38, 0xc0420cf358, 0xc04234e940, 0x1, 0x0, 0xe8)
            D:/Go/src/internal/poll/fd_windows.go:223 +0x13a
    internal/poll.(*FD).acceptOne(0xc0420cf340, 0xe8, 0xc04208c2a0, 0x2, 0x2, 0xc0420cf358, 0x47fcf9, 0xc042045b58, 0x41236f, 0x10)
            D:/Go/src/internal/poll/fd_windows.go:793 +0xae
    internal/poll.(*FD).Accept(0xc0420cf340, 0xc04217d7f0, 0x0, 0x0, 0x0, 0x0, 0xc000000000, 0x0, 0x0, 0x0, ...)
            D:/Go/src/internal/poll/fd_windows.go:827 +0x142
    net.(*netFD).accept(0xc0420cf340, 0xc042346940, 0xc042045cc8, 0x4028b8)
            D:/Go/src/net/fd_windows.go:192 +0x86
    net.(*TCPListener).accept(0xc042080658, 0xc042045cf8, 0x40175e, 0xc042346940)
            D:/Go/src/net/tcpsock_posix.go:136 +0x35
    net.(*TCPListener).AcceptTCP(0xc042080658, 0xc042045d40, 0xc042045d48, 0x18)
            D:/Go/src/net/tcpsock.go:246 +0x50
    net/http.tcpKeepAliveListener.Accept(0xc042080658, 0xa3fa20, 0xc0423468c0, 0xa88cc0, 0xc042352c60)
            D:/Go/src/net/http/server.go:3216 +0x36
    net/http.(*Server).Serve(0xc042178a90, 0xa88780, 0xc042080658, 0x0, 0x0)
            D:/Go/src/net/http/server.go:2770 +0x1ac
    net/http.(*Server).ListenAndServe(0xc042178a90, 0xc042178a90, 0x5)
            D:/Go/src/net/http/server.go:2711 +0xb0
    net/http.ListenAndServe(0xc0420617e8, 0x5, 0x0, 0x0, 0x4, 0xc0420617e8)
            D:/Go/src/net/http/server.go:2969 +0x81
    github.com/pvelder/transport/svc.(*Program).run(0xe1bf00)
            Z:/dev/src/github.com/pvelder/transport/svc/service.go:35 +0x1a2
    created by github.com/pvelder/transport/svc.(*Program).Start
            Z:/dev/src/github.com/pvelder/transport/svc/service.go:22 +0x46
    
    goroutine 22 [IO wait]:
    internal/poll.runtime_pollWait(0x135d300, 0x72, 0xa84fc0)
            D:/Go/src/runtime/netpoll.go:173 +0x5e
    internal/poll.(*pollDesc).wait(0xc0420cf7c8, 0x72, 0xd9a400, 0x0, 0x0)
            D:/Go/src/internal/poll/fd_poll_runtime.go:85 +0xa2
    internal/poll.(*ioSrv).ExecIO(0xdf9b38, 0xc0420cf618, 0xa3f808, 0xc0424498d0, 0x47342b, 0x93e340)
            D:/Go/src/internal/poll/fd_windows.go:223 +0x13a
    internal/poll.(*FD).Read(0xc0420cf600, 0xc04235a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
            D:/Go/src/internal/poll/fd_windows.go:484 +0x248
    net.(*netFD).Read(0xc0420cf600, 0xc04235a000, 0x1000, 0x1000, 0xc042449978, 0x6eede1, 0xc042352d58)
            D:/Go/src/net/fd_windows.go:151 +0x56
    net.(*conn).Read(0xc042080668, 0xc04235a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
            D:/Go/src/net/net.go:176 +0x71
    net/http.(*connReader).Read(0xc042352d50, 0xc04235a000, 0x1000, 0x1000, 0xc0420cf6f0, 0x12c06a8, 0x3)
            D:/Go/src/net/http/server.go:764 +0xff
    bufio.(*Reader).fill(0xc0423590e0)
            D:/Go/src/bufio/bufio.go:100 +0x125
    bufio.(*Reader).ReadSlice(0xc0423590e0, 0xc042449a0a, 0xc042449ad8, 0x41164d, 0x12c77d0, 0x0, 0xc042449ab8)
            D:/Go/src/bufio/bufio.go:341 +0x33
    bufio.(*Reader).ReadLine(0xc0423590e0, 0xc042116000, 0x100, 0xf8, 0xa00620, 0x1, 0x100c04203a800)
            D:/Go/src/bufio/bufio.go:370 +0x3b
    net/textproto.(*Reader).readLineSlice(0xc042144060, 0xc042138601, 0xc042449ba8, 0x41236f, 0x100, 0xa00620)
            D:/Go/src/net/textproto/reader.go:55 +0x77
    net/textproto.(*Reader).ReadLine(0xc042144060, 0xc042116000, 0x0, 0x0, 0x72)
            D:/Go/src/net/textproto/reader.go:36 +0x32
    net/http.readRequest(0xc0423590e0, 0x0, 0xc042116000, 0x0, 0x0)
            D:/Go/src/net/http/request.go:929 +0x93
    net/http.(*conn).readRequest(0xc0423468c0, 0xa88c00, 0xc04205de40, 0x0, 0x0, 0x0)
            D:/Go/src/net/http/server.go:944 +0x176
    net/http.(*conn).serve(0xc0423468c0, 0xa88c00, 0xc04205de40)
            D:/Go/src/net/http/server.go:1768 +0x4e3
    created by net/http.(*Server).Serve
            D:/Go/src/net/http/server.go:2795 +0x282
    rax     0x1602438
    rbx     0x1602438
    rcx     0x1602438
    rdi     0xc04208a000
    rsi     0x1602438
    rbp     0xc042089e70
    rsp     0x377fa60
    r8      0x0
    r9      0xb9ccf9200fab
    r10     0xc04205dd80
    r11     0x246
    r12     0x43fb70
    r13     0x4
    r14     0x0
    r15     0x4
    rip     0x41b457a
    rflags  0x10202
    cs      0x33
    fs      0x53
    gs      0x2b
 
I have no problem running the same code using go 1.10.0 compiler on macOS.

By adding some extra logging, I noticed that the problem is linked to the usage of runtime.SetFinalizer on go_oci8.go line 931: 

[runtime.SetFinalizer(ss, (*OCI8Stmt).Close)](https://github.com/mattn/go-oci8/blob/master/oci8.go#L931)

When the garbage collector gets called, this seems to be after 2 minutes, the crash happens.
I forced a runtime.gc() in the test code and got the crash immediately.  The extra logging reveals that all prepared statements get closed without a problem except for 1 of them.  Commenting out this statement, makes the problem appear on one of the other statements, which was previously correctly closed.

The crashing code is in [the OCIHandleFree call in the close call](https://github.com/mattn/go-oci8/blob/master/oci8.go#L942-L944). 

Problem looks very similar to [issue 140](https://github.com/mattn/go-oci8/issues/140).

Let me know if I can do extra tests on my codebase in order to try to fix the problem.

**Comment by pvelder** [comment]
I filtered out [this minimal test program](https://gist.githubusercontent.com/pvelder/0c0e11de7bd2268b175ad427b8503c9e/raw/15079d51385a632a0580f93c295da25886c3183e/main.go ) that still shows the crash (at least in my windows environment).  
It is a small http server.  If you connect your browser to http://localhost:8082/testme it crashes.
Hope this helps.

**Comment by mattn** [comment]
Temporary disable runtime.SetFinalizer.

**Comment by pvelder** [comment]
Thanks @mattn   What would you think about keeping the open OCI8Stmts at OCI8Conn level and close these when the OCI8Conn is closed ... ?

I' tried this (even with the finalizer active) it seems to work: 

    $ git diff
    diff --git a/oci8.go b/oci8.go
    index 19609b5..d288902 100644
    --- a/oci8.go
    +++ b/oci8.go
    @@ -432,6 +432,7 @@ type OCI8Conn struct {
            inTransaction        bool
            enableQMPlaceholders bool
            closed               bool
    +       openOCI8Stmts        []*OCI8Stmt
     }
    
     type OCI8Tx struct {
    @@ -875,6 +876,10 @@ func (c *OCI8Conn) Close() error {
                    }
            }
    
    +       for _, openOCI8Stmt := range c.openOCI8Stmts {
    +               err = openOCI8Stmt.Close()
    +       }
    +
            C.OCIHandleFree(
                    c.env,
                    C.OCI_HTYPE_ENV)
    @@ -929,6 +934,8 @@ func (c *OCI8Conn) prepare(ctx context.Context, query string) (driver.Stmt, erro
    
            ss := &OCI8Stmt{c: c, s: s, bp: (**C.OCIBind)(bp), defp: (**C.OCIDefine)(defp)}
            runtime.SetFinalizer(ss, (*OCI8Stmt).Close)
    +       c.openOCI8Stmts = append(c.openOCI8Stmts, ss)
    +
            return ss, nil
     }

 If you want I can make a pull request ?

**Comment by mattn** [comment]
> The finalizer would no longer be needed I guess ?

Yes, could you please send me pull-request?

**Comment by pvelder** [comment]
OK. Cfr https://github.com/mattn/go-oci8/pull/198

**Comment by pvelder** [comment]
Fixed with pr https://github.com/mattn/go-oci8/pull/198
