### ISSUE TITLE
sql.out issues with 1.8.3

### ISSUE THREAD

**Issue by tommycha** [mattn/go-oci8#204]
when trying to use go-oci8 Today:

# github.com/mattn/go-oci8
../src/github.com/mattn/go-oci8/oci8_go18.go:77: undefined: sql.Out
../src/github.com/mattn/go-oci8/oci8_go18.go:83: undefined: sql.Out

**Comment by mattn** [comment]
What version of go do you use?

**Comment by tommycha** [comment]
go version go1.8.3 linux/amd64

**Comment by mattn** [comment]
Sorry, sql.Out is included on go1.9. I'll fix in later.

**Comment by mattn** [comment]
https://github.com/mattn/go-oci8/pull/205 fix this.
