### ISSUE TITLE
Support for queries with column names with $$

### ISSUE THREAD

**Issue by wcabarcas** [mattn/go-oci8#207]
Hello @mattn 

I've been working with your go-oci8 driver and works great, but when I add column names which have $$ suffix (i.e Oracle's materialized view logs table structure). Running code, the loop for {} can't extract data from table and does not show any error, just when I add dmltype$$ column.
  
Here is the code:
```go
var sql_delta_mlog string = "select id, dmltype$$ operation from mlog$_persons"

 delta_rows, err := db.Query(sql_delta_mlog)
                  if err != nil {
                     fmt.Println(err)
                  }
                  defer delta_rows.Close()

                  for delta_rows.Next() {

                      var primary_key string
                      var operation string
                      delta_rows.Scan(&primary_key)
                      delta_rows.Scan(&operation)
                      fmt.Println(primary_key)
                     fmt.Println(operation)

                  }
```
Hope you can help me, maybe can be a bug.
Thanks a lot!

**Comment by mattn** [comment]
please check all of return err of Scan.

**Comment by wcabarcas** [comment]
The query with column with suffix $$ is working.
Thanks
