### ISSUE TITLE
while reading long raw image from oracle - ORA-01406 

### ISSUE THREAD

**Issue by shivanisingh** [mattn/go-oci8#208]
Image from long raw format is not supported in current package. 
While reading exception is thrown as:
ORA-01406: fetched column value was truncated

db, err := sql.Open("oci8", getDSN()) //function to get connection details 
    if err != nil {
        fmt.Println(err)
        return
    }
    defer db.Close()
    rows, err := db.Query("SELECT idKey, image FROM sysadm.all_images")
    if err != nil {
        fmt.Println(err)
        return
    }
    defer rows.Close()
    for rows.Next() {
       var id string
       var data []byte
       rows.Scan(&id, &data)    
    }
    fmt.Println("Total errors", rows.Err())
}

**Comment by MichaelS11** [comment]
How big are the long raw?

**Comment by shivanisingh** [comment]
Its has binary format of image. As WA I converted images to blob. It works there after

**Comment by shivanisingh** [comment]
Its has binary format of image. As WA I converted images to blob. It works there after
