### ISSUE TITLE
Can I use DEFINE to define a variable in a statement?

### ISSUE THREAD

**Issue by bwmarrin** [mattn/go-oci8#211]
I want to use something like this

```sql
define ReportDate = to_date('2018-03-07', 'YYYY/MM/DD')
select * from table where date=&ReportDate
```
I can do this in the Oracle SQL Developer tool, but it doesn't seem to work from Go.  Is this possible somehow?  I have a separate query where I need this because the date value is used about 40 times and passing 40 ordered parameters of the exact same data seems insane.

**Comment by lnxbil** [comment]
As far as I know, this is a feature of `sqlplus`, not the SQL itself.

**Comment by bwmarrin** [comment]
Sorry for not following up here :) Thanks for the responses everyone.  

The reason a bind variable wouldn't work as easily for me, is in this example the SQL statement needed the same variable about 20 times within the sql script.  So adding 20 bind variables is pretty tedious.

I ended up using the golang template package to parse the SQL script and insert the parameters that way.  This might have some security concerns in some situations but in my case it was an acceptable solution.

**Comment by bwmarrin** [comment]
Oh, yeah I could parse it to insert bind  ? marks :)

But back in the Go code, I'd have to have a matching bind value for every one of those ? marks inside the script. So there'd be potentially 30-40 binds to the exact same data value mixed with binds for other values, and keeping that all in the right order could be a nightmare.

Maybe there's a cleaner way to do it that I'm not realizing but both the performance and speed are fine in my usecase, I'm open to better ideas though.
