### ISSUE TITLE
Remove pkg-config dependency?

### ISSUE THREAD

**Issue by MichaelS11** [mattn/go-oci8#215]
Couldn't the dependency on pkg-config be easily removed? For example on Linux, the steps could just be:

Download oracle instant client:
http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html

Set variables:
export LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib/
export CGO_CFLAGS="-I/usr/include/oracle/11.2/client64/"
export CGO_LDFLAGS="-L/usr/lib/oracle/11.2/client64/lib/ -lstdc++ -lclntsh"

Install:
go install -v ...

Seems like the pkg-config dependency is not really needed.

**Comment by mattn** [comment]
No, it can't. Because install location is not /usr prefix. It is depend on Linux distributions.

**Comment by mattn** [comment]
And also, different library is required for the several version.

**Comment by MichaelS11** [comment]
Was saying couldn't the line #cgo pkg-config: oci8 in oci8.go be removed. Would still have to install clients and configure the variables to the correct locations, but would not have to install/use pkg-config to do it.

**Comment by MichaelS11** [comment]
@mattn 

All that is needed is to set the correct environment variables instead of having to setup, and often download,  pkg-config. Could pkg-config be removed?

**Comment by mattn** [comment]
No, it can't since library name are different between several version of Oracle.

**Comment by mattn** [comment]
Do you mean build constraints or something hack in CGO CFLAGS? AFAIK, $ prefix for environment variables in CGO pragma doesn't work.

**Comment by MichaelS11** [comment]
I am saying when I build something that uses oci8, I first remove the pkg-config line from oci8.go. Then I set the three environment variables (LD_LIBRARY_PATH, CGO_CFLAGS, CGO_LDFLAGS). This way I don't have use pkg-config.

Either removing pkg-config from oci8 or adding a built option to remove pkg-config would be great.

**Comment by mattn** [comment]
If there are some environment that doesn't have pkg-config, https://github.com/mattn/pkg-gonfig can be used.

**Comment by MichaelS11** [comment]
Using environment variables probably makes it so Go get doesn't fail. Go get requires pkg-config to be configured before Go get works. So using environment variables makes it so that Go get will not fail if pkg-config is not setup correctly.

**Comment by mattn** [comment]
Also if you miss set environment variable, go-get will be fail. Installing pkg-config is installation instruction as same as Oracle. Not related on Go or go-oci8, I think.

**Comment by MichaelS11** [comment]
Are you saying pkg-config is needed for Oracle? I have only had to use pkg-config for go-oci8 so far.

Not setting the three environment variables should have no affect on go get when the pkg-config line is removed.

**Comment by mattn** [comment]
CGO_CFLAGS must be set in each times to install/update go-oci8 since it is specified for only flags for oracle. pkg-config does not required to setup each times.

**Comment by MichaelS11** [comment]
Any environment variable can be set to stay, they do not have to be setup each time.

**Comment by mattn** [comment]
If set CGO_LDFLAGS on .bashrc, installed binary via `go get github.com/mattn/go-gtk` will link Oracle library.

**Comment by MichaelS11** [comment]
Trying to see about removing dependencies.

**Comment by mattn** [comment]
> Trying to see about removing dependencies.

Do you mean that linker must try to remove need-less libraries? Yes (but No on Windows)

**Comment by mattn** [comment]
How about to separate sources to enable both like below?

oci8_pkg-config.go
```go
// +build pkg-config

package oci8

/*
#cgo pkg-config: oci8
*/
import "C"
```

**Comment by MichaelS11** [comment]
Yeah, a build flag would be great. If it defaulted to current pkg-config, that would be expected. Just adding a build flag/tag of something like oci8-no-pkg-config would be great

**Comment by mattn** [comment]
Could you please send me PR ? :)

**Comment by MichaelS11** [comment]
PR:
https://github.com/mattn/go-oci8/pull/235

Thank you! :)
