### ISSUE TITLE
ORA-01861: literal does not match format string 

### ISSUE THREAD

**Issue by pamelamei** [mattn/go-oci8#222]
Use Prepare Statement to insert table :
1. prepare sql command: INSERT INTO HSP_RG_PERF (STORAGE_NAME, RECORD_TIME, RAID_GROUP_NUMBER, BUSY_RATE, MAX_BUSY_RATE) values(:val1, :val2, :val3, :val4, :val5)
2. error inserting &{ci12 2018-05-17 23:42:24 0 0 0}, err ORA-01861: literal does not match format string 
How to debug? How can I print the whole statement for Exec?

**Comment by mattn** [comment]
What value are passed into Exec() ?

**Comment by pamelamei** [comment]
values passed in to Exec() as below
 (val1, val2, val3, val4, val5) val1-val5 is string type 
 (ci12, 2018-05-18 09:59:43,  0,  0,  0)
BTW, each column data type is as below:
CREATE TABLE HSP_RG_PERF (STORAGE_NAME  varchar2(128) NOT NULL, RECORD_TIME  DATE NOT NULL, RAID_GROUP_NUMBER varchar2(128) NOT NULL, BUSY_RATE varchar2(128) NOT NULL, MAX_BUSY_RATE varchar2(128) NOT NULL)

**Comment by pamelamei** [comment]
So will oci8 convert the string to TODATE('2018-05-18 09:59:43','yyyy-mm-dd hh24:mi:ss')?

**Comment by pamelamei** [comment]
Nope, not question mark as place holder, but following below's rule.
So use :val$n instead for Oracle.
MySQL               PostgreSQL            Oracle
=====               ==========            ======
WHERE col = ?       WHERE col = $1        WHERE col = :col
VALUES(?, ?, ?)     VALUES($1, $2, $3)    VALUES(:val1, :val2, :val3)

**Comment by pamelamei** [comment]
I just did test that convert the column RECORD_TIME  type from DATE to varchar2(128), then can be "Exec"ed w/o error and inserted to table correctly.
So the problem could be if the string that should be pass to Exec as DATE type.
I tried convert the string from 2018-05-18 09:59:43 to TO_DATE('2018-05-18 09:59:43','yyyy-mm-dd hh24:mi:ss'), seems ORA-01861 disappear.
But new error is out: ORA-01858: a non-numeric character was found where a numeric was expected.
So what do you suggest to deal with the DATE type value? Could you please help give any example?

**Comment by mattn** [comment]
Did you try to pass time.Time into Exec?

https://github.com/mattn/go-oci8/blob/a2928e4a4ebc87c6fd85734514396182b94537c2/more_test.go#L597-L605

**Comment by pamelamei** [comment]
Yes, using time.Time instead of string can work well. ^_^
Using string can work well in mysql driver, so if oci8 can support automatic convert string in to time.Time, that would be great ;)
Thanks, Mattn.

**Comment by pamelamei** [comment]
I'll close such issue.
