### ISSUE TITLE
dyld: Library not loaded: @rpath/libclntsh.dylib.12.1

### ISSUE THREAD

**Issue by proclinux** [mattn/go-oci8#224]
hi, something was wrong when I run the program on mac:
![image](https://user-images.githubusercontent.com/7356984/40774895-5885ee4a-64f9-11e8-96df-c380cd08cc05.png)

oci8.pc:
prefixdir=/Users/proclinu/Oracle/instantclient_12_2
libdir=${prefixdir}
includedir=${prefixdir}/sdk/include

Name: OCI
Description: Oracle database driver
Version: 12.2
Libs: -L${libdir} -lclntsh
Cflags: -I${includedir}

GOROOT=/usr/local/Cellar/go/1.9.2/libexec #gosetup
GOPATH=/Users/proclinu/GoLang #gosetup
/usr/local/Cellar/go/1.9.2/libexec/bin/go build -i -o /private/var/folders/g4/qk5035gn3fj1919kzrqj5c940000gn/T/___go_build_query_go /Users/proclinu/GoLang/src/locale/oracle/query.go #gosetup
/private/var/folders/g4/qk5035gn3fj1919kzrqj5c940000gn/T/___go_build_query_go #gosetup
dyld: Library not loaded: @rpath/libclntsh.dylib.12.1
  Referenced from: /private/var/folders/g4/qk5035gn3fj1919kzrqj5c940000gn/T/___go_build_query_go
  Reason: image not found

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

I used a makefile to test,it's ok:
objects = test.o

test: ${objects}
	gcc -o test ${objects} $(pkg-config --libs --cflags libclntsh)

so I guess, maybe some wrong happened in oci8

**Comment by proclinux** [comment]
![image](https://user-images.githubusercontent.com/7356984/40775023-a644572a-64f9-11e8-9417-030c0ee06bac.png)
libclntsh can not be loaded correctly.

**Comment by proclinux** [comment]
my ide goland have some problems，DYLD_LIBRARY_PATH can not be loaded.
must add manualy

**Comment by cjbj** [comment]
Since recent versions of macOS ignore DYLD_LIBRARY_PATH in subshells, and therefore it isn't useful or reliable, you may just want to install Instant Client following the [instructions](http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html#ic_osx_inst) and put it in ~/lib or /usr/local/lib

**Comment by CH3T** [comment]
It's important to put it in ~/lib/, at least that worked for me after I put libclntsh.dylib in 

> /usr/local/lib

I used ln -s <pathTo_libclntsh.dylib> ~/lib/ as it's done here https://oracle.github.io/odpi/doc/installation.html#macos

Also do not do this as "sudo su" as then you would put the libs under /var/root/lib. You should put it under ~/lib while being the same user that runs your programs.
