### ISSUE TITLE
Buffer too small for CLOB to CHAR or BLOB to RAW 

### ISSUE THREAD

**Issue by proclinux** [mattn/go-oci8#225]
when i use call procedure get_clob(source clob, dest clob), it return:
2018/06/05 18:05:57 main.go:32: ORA-22835: Buffer too small for CLOB to CHAR or BLOB to RAW conversion (actual: 4020, maximum: 4000)
length of source is more then 4000.
exec dos not support clob which length is more then 4000?
this is my program:
_, err = db.Exec("CALL get_clob(:source, :dest)",
		sql.Named("source", source),
		sql.Named("dest", sql.Out{Dest: &dest, In:false}),)
	if err != nil {
		log.Fatal(err)
	}

**Comment by MichaelS11** [comment]
Now have tests for up to 32K. Is this still an issue?

**Comment by MichaelS11** [comment]
@mattn Close this?
