### ISSUE TITLE
Info Linux Installation 11.2.0.4.0

### ISSUE THREAD

**Issue by branscha** [mattn/go-oci8#227]
I successfully installed the package on Ubuntu. Here is my setup, maybe other people might find useful information.

I installed both files by unzipping to a directory <INSTALLDIR>

 *  instantclient-basic-linux.x64-11.2.0.4.0.zip
 * instantclient-sdk-linux.x64-11.2.0.4.0.zip

I defined environment variables: 

 * LD_LIBRARY_PATH
 * PKG_CONFIG_PATH

I needed to create a symbolic link to the versioned libraries. This is necessary to prevent the "/usr/bin/ld: cannot find -llibclntsh.so" error.

      ln -s libclntsh.so.11.1 libclntsh.so
      ln -s libocci.so.11.1 libocci.so

I defined a oci8.pc 

      prefix=<INSTALLDIR>
      exec_prefix=${prefix}
      libdir=${prefix}
      includedir=${prefix}/sdk/include

      glib_genmarshal=glib-genmarshal
      gobject_query=gobject-query
      glib_mkenums=glib-mkenums

      Name: oci8
      Description: oci8 library
      Libs: -L${libdir} -lclntsh
      Cflags: -I${includedir}
      Version: 11.2

**Comment by mattn** [comment]
Thanks for your useful information.

**Comment by MichaelS11** [comment]
@mattn Close this?
