### ISSUE TITLE
How to use placeholder parameters when querying oracle database?

### ISSUE THREAD

**Issue by m3ng9i** [mattn/go-oci8#228]
I have a sql to run (note that the value of col1 and col2 are the same):

```
select * from sometable where col1=123 and col2=123
```

I've tried three different ways to do this, but which one is the best practice?

1. Use two `:var` and two `value`:

```
var value = 123
rows, err := db.Query("select * from sometable where col1=:var and col2=:var", value, value)
```

2. Use two `:var` and one `value`:

```
var value = 123
rows, err := db.Query("select * from sometable where col1=:var and col2=:var", value)
```

3. Use `:var1`, `:var2` and two `value`:

```
var value = 123
rows, err := db.Query("select * from sometable where col1=:var1 and col2=:var2", value, value)
```

**Comment by MichaelS11** [comment]
Did you try them? Do they all work? Did you try some simple timing tests/benchmarks? If so, any timing differences?

Benchmarks are a great way to see what the best way in these kind of options.
Can also look at the database statistics, like AWR reports.

**Comment by mattn** [comment]
Please use [sql.NamedArg](https://golang.org/pkg/database/sql/#Named)
