### ISSUE TITLE
Concurrency issues: Getting driver:bad connection intermittently

### ISSUE THREAD

**Issue by sumiet** [mattn/go-oci8#229]
I have been using oci8 for over a year now for several batch processes. There I used to make oracle calls based on a particular frequency without any high number of parallel requests. Recently I started using this driver to process multiple number of user requests in parallel using go routines. The connections go through 90% of the times but for remaining 10% I see an error `driver: bad connection` being thrown from this driver. This is generally happening in two situations:

1. When the connection was left ideal for too long(happens for few requests).
2. When there is a spike in number of connections.

Actions taken:
1. Already checked with my oracle DB for connection/session limits. There is no such limit on it.
2. Tried forking the branch and adding error logs which didn't seem to compile.

Most of the people who have faced this issue mentioned wrong handling of multiple connections at the same time. For me that is something done by oci8.

Please help!

**Comment by sumiet** [comment]
This is the exact error message i was able to find from driver: `ORA-03114: not connected to ORACLE`

**Comment by mattn** [comment]
Could you please show me small example to reproduce?

**Comment by pamelamei** [comment]
I met the same issue.

**Comment by cjbj** [comment]
If you see ORA-3114 after a period of idleness, check if you have a firewall etc that is closing idle connections. 

On a related front (though you would get different ORA errors), make sure the DB is not killing idle sessions with ALTER SYSTEM KILL, and there is no profile or resource manager that is closing connections.  Also make sure the DB 'processes' parameter is configured high enough to cope with your connection & disconnection load (again you would see different errors).

Don't forget that each Oracle connection can only execute one statement at a time.

Without knowing your code, I can't add much more.

**Comment by sumiet** [comment]
This was related to internal network issues

**Comment by reev277** [comment]
> This was related to internal network issues

Can you please tell what was the issue, and how was it resolved?
