### ISSUE TITLE
Calling stored proc with VARCHAR2 output param failing

### ISSUE THREAD

**Issue by Ritzpak** [mattn/go-oci8#236]
I'm using Go v1.10 x64 for Windows, oci8 2caf1d2 with Oracle 12.2.  I'm trying to call a stored procedure contained in a package that has some output params.  Number types work fine.  Varchar2 fails every time on line 1669 of oci8.go with this error.

ORA-01480: trailing null missing from STR bind value

Here is what I'm testing with:

```
CREATE OR REPLACE
PACKAGE BODY GOLANG_TEST_PKG AS

  PROCEDURE ProcName
  (
    Arg1          OUT VARCHAR2
  ) IS
  BEGIN
    Arg1 := 'Testing';
  END;
  
  PROCEDURE ProcName2
  (
    Arg1          OUT NUMBER
  ) IS
  BEGIN
    Arg1 := 23;
  END;

END GOLANG_TEST_PKG;
```

```
func (c *Database) ProcTest(ctx context.Context) (bool, error) {
	c.logger.Info("ProcTest")

	var outArg2 int64
	_, err := c.DB.ExecContext(ctx, "BEGIN GOLANG_TEST_PKG.ProcName2(Arg1=>:Arg1); END;", sql.Named("Arg1", sql.Out{Dest: &outArg2}))

	var outArg string
	_, err = c.DB.ExecContext(ctx, "BEGIN GOLANG_TEST_PKG.ProcName(Arg1=>:Arg1); END;", sql.Named("Arg1", sql.Out{Dest: &outArg}))

	if err != nil {
		return false, err
	}

	return true, nil
}
```

**Comment by MichaelS11** [comment]
Did you try a pure SQL solution (SQL anonymous block) outside of Go using something like SQL plus? If so, post your results?

**Comment by MichaelS11** [comment]
@mattn Close this?

**Comment by Ritzpak** [comment]
![image](https://user-images.githubusercontent.com/1278990/48131749-28423c00-e25f-11e8-8171-431e4ee16a9b.png)
The proc works fine.  Still not working in Go with VARCHAR2 output param.

**Comment by Ritzpak** [comment]
I updated to e24061a and it is working now.  Thank you!

**Comment by MichaelS11** [comment]
Woot! :) Welcome
