### ISSUE TITLE
Example is poor

### ISSUE THREAD

**Issue by n0b0dyvn** [mattn/go-oci8#25]
I tried to use but seem like your code exception for sql.Open is poor. In your example your write db, err := sql.Open("oci8","scott/tiger"). I belive when i read your code i see your comment mean scott/tiger can be replace by user:password@host:port/sid. I tried to replace them but seem like it all success even i wrong host or port. 

Even i correct them, something like db.Exec("CONN SYSTEM/<pass>") return runtime.panic. After that i try to test ParseDSN and i realize your format is wrong. And i must continue to figure how your code work.

Hope you fix all that soon.

**Comment by mattn** [comment]
You can set DSN environment variable.
