### ISSUE TITLE
[Bug] Number Parase Error,  int64 parsed to float64

### ISSUE THREAD

**Issue by aiderzcx** [mattn/go-oci8#258]
// If the precision is nonzero and scale is -127, then it is a FLOAT, else it is a NUMBER(precision, scale).
			// For the case when precision is 0, NUMBER(precision, scale) can be represented simply as NUMBER.
			// https://www.codeproject.com/Articles/776119/An-Oracle-OCI-Data-Source-Class-for-Ultimate-Gri
   
   ***********  This condition check error, only when precision==0 and scale == 0 , the number parseed to int,   ********
 			if !(precision != 0 && scale == -127) && scale == 0 { 
				oci8cols[i].kind = C.SQLT_INT
				oci8cols[i].size = 8
				oci8cols[i].pbuf = C.malloc(C.size_t(oci8cols[i].size))
			} else {
				oci8cols[i].kind = C.SQLT_BDOUBLE
				oci8cols[i].size = 8
				oci8cols[i].pbuf = C.malloc(C.size_t(oci8cols[i].size))
			}

**Comment by aiderzcx** [comment]
queryASH.Scan().sql: Scan error on column index 0: converting driver.Value type float64 (\"5.39504e+06\") to a uint64: invalid syntax" .  

index 0 is sample_id

**Comment by mattn** [comment]
Please show me your code and DDL.

**Comment by aiderzcx** [comment]
QuerySqlCmd: 
select_ash11 = `
	SELECT 
		sample_id,sample_time,session_id,session_serial#,session_type,session_state,
		user_id,sql_id,sql_child_number,sql_opcode,sql_plan_hash_value,force_matching_signature,
		service_hash,qc_session_id,qc_instance_id,blocking_session,blocking_session_status,
		blocking_session_serial#,event,event_id,event#,seq#,p1,p2,p3,wait_class,
		wait_class_id,wait_time,time_waited,rawtohex(xid),current_obj#,current_file#,
		current_block#,program,client_id,0  
	FROM v$active_session_history 
	WHERE sample_id>:sample_id
	`
Code:
	for rows.Next() {
		var data moudle.RowDataST
		err := rows.Scan(
			&data.SampleId,
			&data.SampleTime,
			&data.SessionId,
			&data.SessionSerial,
			&data.SessionType,
			&data.SessionState,
			&data.UserId,
			&data.SqlId,
			&data.SqlChildNum,
			&data.SqlOpCode,
			&data.SqlplanHash,
			&data.ForceMatching,
			&data.ServiceHash,
			&data.QcSessionId,
			&data.QcInstanceId,
			&data.BlockSession,
			&data.BlockSessionStatus,
			&data.BlockSessionSerial,
			&data.Event,
			&data.EventId,
			&data.EventN,
			&data.SeqN,
			&data.P1,
			&data.P2,
			&data.P3,
			&data.WaitClass,
			&data.WaitClassId,
			&data.WaitTime,
			&data.TimeWaited,
			&data.Xid,
			&data.CurObj,
			&data.CurFile,
			&data.CurBlock,
			&data.Program,
			&data.ClientId,
			&data.ConId,
		)
		if err != nil {
			log.Warning("queryASH.Scan().%v", err)
			continue
		}

data define:
type RowDataST struct {
	sql.NullInt64
	SampleId           uint64         
	SampleTime         time.Time     
	SessionId          sql.NullInt64 
	SessionSerial      sql.NullInt64 
	SessionType        sql.NullString
	SessionState       sql.NullString
	UserId             sql.NullInt64
	SqlId              sql.NullString
	SqlChildNum        sql.NullInt64
	SqlplanHash        sql.NullInt64 
	ForceMatching      sql.NullString
	SqlOpCode          sql.NullInt64 
	ServiceHash        sql.NullInt64 
	QcSessionId        sql.NullInt64 
	QcInstanceId       sql.NullInt64 
	BlockSession       sql.NullInt64 
	BlockSessionStatus sql.NullString
	BlockSessionSerial sql.NullInt64 
	Event              sql.NullString
	EventId            sql.NullInt64  
	EventN             sql.NullInt64  
	SeqN               sql.NullInt64  
	P1                 sql.NullString
	P2                 sql.NullString 
	P3                 sql.NullString 
	WaitClass          sql.NullString 
	WaitClassId        sql.NullInt64 
	WaitTime           sql.NullInt64  
	TimeWaited         sql.NullInt64  
	Xid                sql.NullString 
	CurObj             sql.NullInt64 
	CurFile            sql.NullInt64  
	CurBlock           sql.NullInt64  
	Program            sql.NullString
	ClientId           sql.NullString 
	ConId              sql.NullInt64 
}

**Comment by MichaelS11** [comment]
Can you provide very simple code, DDL, and SQL that shows the issue?

The information you provided makes it hard to figure out what values are in the table, what values are being pulled out of the table, and what the passed value is. A very simple example, maybe a table with one column and one row would be great.

**Comment by MichaelS11** [comment]
Have very simple code, DDL, and SQL that shows the issue makes troubleshooting much easier.

That being said, it looks like SAMPLE_ID should be a float. Looking at the table/view V$ACTIVE_SESSION_HISTORY on Oracle 11.2.0.3 the SAMPLE_ID column type is NUMBER. From my understanding a NUMBER type should be a float.

Here is a simple example in SQL Plus showing that:

```sql
SQL> create table TEST1 ( A number );

Table created.

SQL> insert into TEST1 ( A ) values ( 1 );

1 row created.

SQL> insert into TEST1 ( A ) values ( 1.1 );

1 row created.

SQL> commit;

Commit complete.

SQL> select * from TEST1;

         A
----------
         1
       1.1

2 rows selected.
```

An int would act differently:
```sql
SQL> create table TEST1 ( A int );

Table created.

SQL> insert into TEST1 ( A ) values ( 1 );

1 row created.

SQL> insert into TEST1 ( A ) values ( 1.1 );

1 row created.

SQL> select * from TEST1;

         A
----------
         1
         1

2 rows selected.
```

**Comment by aiderzcx** [comment]
thanks, Number is a float
