### ISSUE TITLE
Cross compile get error: undefined: OCI8Connector

### ISSUE THREAD

**Issue by MichaelS11** [mattn/go-oci8#262]
**Please note this is issue is only about cross compile go get error. If you are getting a cross compile build error, that can be fixed. Please look at other issues for fixes.** 

Getting undefined: OCI8Connector on go get cross compile. This works:

`go get github.com/mattn/go-oci8`

This:
```
set GOOS=linux
go get github.com/mattn/go-oci8
```

Gives this error:
```
# github.com/mattn/go-oci8
..\src\github.com\mattn\go-oci8\connector.go:20:22: undefined: OCI8Connector
```

Tried this from Windows to Linux as well as from Linux to Windows.

The cross compile seems to work, just not the go get. Any ideas? A Go bug?

Tried on Windows Go version 1.10.3 and Linux Go version 1.11.1.

**Comment by mattn** [comment]
Seems to be build cache of your cross compiling. :)

**Comment by MichaelS11** [comment]
Hmmm, but it would build just find. Only get was having the issue, which seems like it would not be the build cache. Did you mean some other cache?

Did try the below, but received the same error:
```
set GOOS=
go clean -cache -testcache github.com/mattn/go-oci8
set GOOS=linux
go clean -cache -testcache github.com/mattn/go-oci8
go get github.com/mattn/go-oci8
```

**Comment by chanlan** [comment]
xxxx@localhost /cygdrive/e/go-push/src/vendor/github.com/mattn/go-oci8
$ go install
# vendor/github.com/mattn/go-oci8
.\connector.go:20:22: undefined: OCI8Connector

why? i want to know! 

set GOARCH=amd64
set GOBIN=E:\go-push\bin
set GOCACHE=C:\Users\xxxx\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\go-push
set GORACE=
set GOROOT=D:\Go
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_386
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fmessage-length=0 -fdebug-prefix-map=C:\cygwin64\tmp\go-build483581658=/tmp/go-build -gno-record-gcc-switches

**Comment by splilly1987** [comment]
Was this ever solved? I'm getting this issue when attempting to build. I can go run my code just fine though.

**Comment by dushaofeng** [comment]
I get this same issue, have no idea to fix it.

**Comment by splilly1987** [comment]
This is correct. I was compiling with CGO=enabled. Once I removes that it compiled properly. Thanks!

**Comment by dushaofeng** [comment]
How to remove CGO_enabled flag?  Do you compile linux target on windows?  And how to confirm what C compile used?  Ths

**Comment by dushaofeng** [comment]
How to install cross C compiler? ths. 
@mattn

**Comment by MichaelS11** [comment]
**Please note this is issue is only about cross compile go get error. If you are getting a cross compile build error, that can be fixed. Please look at other issues for fixes.** 

For example:
https://github.com/mattn/go-oci8/issues/84#issuecomment-420784283

**Comment by dushaofeng** [comment]
How can i know what C version i used? Ths.  @MichaelS11 

**go env**
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=0

**gcc -v output**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-7.3.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --enable-libstdcxx-filesystem-ts=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev2, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 7.3.0 (Rev2, Built by MSYS2 project)

**Comment by robinsoon** [comment]
github.com/jzaikovs/ora   
This is written by pure go [Oracle driver]. It works well at present.

**Comment by MichaelS11** [comment]
It is not pure Go, it is cgo. It is using https://github.com/rainycape/dl which loads the Oracle instant client which is written in C

**Comment by robinsoon** [comment]
> It is not pure Go, it is cgo. It is using https://github.com/rainycape/dl which loads the Oracle instant client which is written in C

It using package syscall 
```
import (
	"syscall"
)

var (
	ociLibrary = syscall.NewLazyDLL("oci.dll")
)
```
I compiled 64-bit and 32-bit programs on Windows and released them. There is no barrier to test queries. There is only one disadvantage. It can't simultaneously extract multiple concurrent processes.

**Comment by MichaelS11** [comment]
It is doing a lot of stuff and it is still using cgo. 

Inside the rainycape/dl package there is a call to import "C". Once an import to C is called in **any** package anywhere in the program the binary has to switch to running cgo instead of pure Go. One of the great features of pure Go is the easy cross-compile. That is why for monitoring applications like Telegraf or Prometheus there is support for many many databases but not Oracle. There is no pure Go driver for Oracle. Telegraf and Prometheus want to keep there project pure Go so they can use Go's easy cross-compile features.

Telegraf inputs:
https://github.com/influxdata/telegraf#input-plugins

Prometheus database exporters:
https://prometheus.io/docs/instrumenting/exporters/#databases

I would love to see/have/use a pure Go driver. It might be possible but would be a lot of work.

Note:
Any interest in an experiment creating a pure Go Oracle driver?
https://github.com/mattn/go-oci8/issues/216

**Comment by moonskyJIE** [comment]
hi,tried this from Linux to Linux,"go get github.com/mattn/go-oci8" is success, but "go build exporter" is fail .What caused this problem?
$ go build -o ./exporter-linux oracle_exporter
# github.com/mattn/go-oci8
../github.com/mattn/go-oci8/connector.go:20:18: undefined: Connector

**Comment by moonskyJIE** [comment]
I do it by use `cgo` not `go`.
