### ISSUE TITLE
can't OCIEnvCreate

### ISSUE THREAD

**Issue by vickhello** [mattn/go-oci8#271]
I encountered this problem as below, hoping to give directions. 
panic: can't OCIEnvCreate
goroutine 1 [running]:
bigdata-goods-store/confProcess.InitConf(0xc0000147f0, 0x4, 0xc000022200, 0x38, 0xc000014890, 0xc, 0xc0000148b0, 0x4, 0xc0000148d0, 0xc)
	/go/src/bigdata-goods-store/confProcess/conf.go:38 +0x44f
main.init.0()
	/go/src/bigdata-goods-store/goodsStore/goodsStore.go:39 +0x30f

**Comment by vickhello** [comment]
Configured Oracle client on linux is  instantclient-basiclite-linux.x64-18.3.0.0.0dbru.zip，and Environment variable settings as below：
export ORACLE_HOME=/home/orcl/instantclient_18_3
export TNS_ADMIN=$ORACLE_HOME/network/admin
export NLS_LANG='simplified chinese_china'.ZHS16GBKexport 
export LD_LIBRARY_PATH=$ORACLE_HOME
export PATH=$ORACLE_HOME:$PATH

**Comment by vickhello** [comment]
I build on another linux machine，and run on this linux machine. This machine's environment configuration  is only oracle client.

**Comment by vickhello** [comment]
how to solve this problem ?

**Comment by mattn** [comment]
Do you have environment variable `$ORACLE_HOME` ?

**Comment by vickhello** [comment]
yes,I configured this variable in file "/etc/profile", the file contents as below:
export ORACLE_HOME=/home/orcl/instantclient_18_3
export TNS_ADMIN=$ORACLE_HOME/network/admin
export NLS_LANG='simplified chinese_china'.ZHS16GBKexport
export LD_LIBRARY_PATH=$ORACLE_HOME
export PATH=$ORACLE_HOME:$PATH

**Comment by vickhello** [comment]
yeah，sqlplus work well

**Comment by mattn** [comment]
```
export LD_LIBRARY_PATH=$ORACLE_HOME
```
This seems to be wrong. Please try to set `$ORACLE_HOME/lib32:$ORACLE_HOME/lib:$LD_LIBRARY_PATH`.

**Comment by vickhello** [comment]
![image](https://user-images.githubusercontent.com/33645617/47061198-12fb6400-d203-11e8-926c-aa01dd03396f.png)
There is no lib32 or lib under the folder “ORACLE_HOME=/home/orcl/instantclient_18_3”，am I use wrong oracle client ？

**Comment by vickhello** [comment]
The problem is not solved

**Comment by MichaelS11** [comment]
Looked at instantclient-basiclite-linux.x64-18.3.0.0.0dbru.zip and it does not seem to have the needed files.

I would try oracle-instantclient18.3-basiclite-18.3.0.0.0-1.x86_64.rpm

**Comment by vickhello** [comment]
I tried the oracle-instantclient18.3-basiclite-18.3.0.0.0-1.x86_64.rpm, and modify the environment variable as below:
export ORACLE_HOME=/usr/lib/oracle/18.3
export TNS_ADMIN=$ORACLE_HOME/network/admin
export NLS_LANG='simplified chinese_china'.ZHS16GBKexport 
export LD_LIBRARY_PATH=$ORACLE_HOME/lib:$LD_LIBRARY_PATH
export PATH=$ORACLE_HOME:$PATH

but the problem "can't OCIEnvCreate" is not resolved

**Comment by vickhello** [comment]
Comparing the two installation files, the files installed are basically the same.The difference is that one is under “usr/lib” and the other is in custom directory.

**Comment by vickhello** [comment]
The problem is resolved, you can close the problem.
Actually in a clean environment, only need to execute the following command,and don't configuration "etc/profile".
1) vim /etc/ld.so.conf 
the contents is  /xxx/xxx/instantclient_18_3
2)  ldconfig -v

Thanks a lot for your reply.

**Comment by vickhello** [comment]
On the basis of a problematic environment, the implementation of the command "unset NLS_LANG" can also solve the problem.This makes me wonder.
The detail information is "NLS_LANG='simplified chinese_china'.ZHS16GBKexport"

**Comment by cjbj** [comment]
For future readers, please follow the Instant Client installation instructions [here for Linux](https://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html#ic_x64_inst) on using ldconfig.  Note they don't mention setting ORACLE_HOME.
