### ISSUE TITLE
I need an example about batch insert operation

### ISSUE THREAD

**Issue by sunshyer** [mattn/go-oci8#277]
I tried to improve insert efficiency , but I can not find the right way about commit/prepare/stmt.exec.

**Comment by MichaelS11** [comment]
Added simple insert benchmark/example:

https://github.com/mattn/go-oci8/blob/8fa434520277b7371232d48f23662fd2ec1cad3c/oci8Sql_test.go#L783-L864

There are additional ways to speed up inserts depending on what you are doing. For example, can do a insert from many select dual union all which works well. (Found 50 to 100 works well depending.) Can also use more than one goroutine depending on use case.

**Comment by MichaelS11** [comment]
@sunshyer Alright to close this?

**Comment by cjbj** [comment]
@MichaelS11 you may be interested in https://groups.google.com/forum/#!topic/golang-sql/-J_1aay72nM

**Comment by MichaelS11** [comment]
@cjbj Cool, thanks. Something that can be looked into later.

**Comment by MichaelS11** [comment]
Close this?

**Comment by sunshyer** [comment]
Yes, thanks .
