### ISSUE TITLE
Are slices supported in prepared statements?

### ISSUE THREAD

**Issue by hydroflame** [mattn/go-oci8#278]
eg. 
```
db.Prepare("SELECT * FROM whatever WHERE fieldA in :1").Exec([]string{"a", "b", "c"})
```
results in 
```
sql: converting argument $1 type: unsupported type []string, a slice of string
```

**Comment by MichaelS11** [comment]
The OCI8 driver calls the sql driver ConvertValue. That error seems to be coming from line 277.

https://golang.org/src/database/sql/driver/types.go

Seems like it would need a custom covert to be supported.

**Comment by mattn** [comment]
It's not possible to pass values to prepared statement. Concating strings is dangerous.

**Comment by hydroflame** [comment]
Where is the problem? postgres and mysql can do it. What's different here?

**Comment by mattn** [comment]
Where is the repository? github.com/lib/pq or  github.com/go-sql-driver/mysql?

Your query is not escaped. When the parameter which user input is used for concating query, it's dangerous. For example:

user's input
```
1; DELETE FROM A;
```

query before concating
```
SELECT * FROM A WHERE B IN ...
```

after concating
```
SELECT * FROM A WHERE B = 1; DELETE FROM A;
```

**Comment by mattn** [comment]
placeholder in prepared statement doesn't accept non-value. You are trying to pass the SQL-like string as value.

**Comment by hydroflame** [comment]
The term value might be overloaded here. Are you refering to this type?

https://godoc.org/database/sql/driver#Value

Because as far as I know that's the only kind of data I have access to that can pass this test
https://golang.org/src/database/sql/driver/types.go
line 233

**Comment by mattn** [comment]
I don't add this since Oracle does not have a type array or list which is typed. You should use concating string in your own risk.

**Comment by hydroflame** [comment]
I'm not asking you to modify your library. I'm just looking for a solution. 

If oracle does not have a array type why does a query like `SELECT * FROM t1 WHERE x in ('a', 'b', 'c')` work? Shouldn't `('a', 'b', 'c')` count as an array? What's it considered to oracle?

**Comment by MichaelS11** [comment]
I think you are trying to do something like this (code not tested):

db.Prepare("SELECT * FROM whatever WHERE fieldA in (:1, :2, :3)").Exec([]string{"a", "b", "c"}...)

If you have variable amount of variables to pass into the in, the :1, :2, ... part can be dynamically created with a simple for loop.

**Comment by mattn** [comment]
`[]string{"a", "b", "c"}` can be translated to `...[]string{"a", "b", "c"}`.

**Comment by hydroflame** [comment]
For future readers. 
If like me you have more than just the list to pass as argument to the prepared statement you can make a slice of interface and append everything to it
```
var args []interface{}
args = append(args, a1)
args = append(args, a2)
args = append(args, ...list)
stmt.Exec(args)
```

However that's still not really getting to the crux of the problem. I'll check how the other libraries do it and jdbc does support array so this is a driver side problem not a oracle problem

**Comment by mattn** [comment]
As far as I can see, Oracle SDK does not have API for binding array.

https://docs.oracle.com/database/121/LNOCI/oci16rel003.htm#LNOCI153

And also, go-oci8 can't replace placeholder `?` in your query since driver MUST NOT replace `?` in SQL string literal.

FYI, JDBC Oracle driver doesn't support binding array since Oracle doesn't have the API.

https://github.com/gluck/ikvm/blob/9ba99a6448dbaf62602ba4273943e1f9b5dcb496/openjdk/sun/jdbc/odbc/JdbcOdbcConnection.java#L92-L95

**Comment by hydroflame** [comment]
https://github.com/gluck/ikvm/blob/9ba99a6448dbaf62602ba4273943e1f9b5dcb496/openjdk/sun/jdbc/odbc/JdbcOdbcPreparedStatement.java#L108

**Comment by mattn** [comment]
a

**Comment by hydroflame** [comment]
ah, my bad

**Comment by mattn** [comment]
Because interface PreparedStatement define setArray. They MUST implement even if the driver doesn't support Array.

https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html

**Comment by MichaelS11** [comment]
Maybe this will help shed a little light as well?

Can I bind an array to an IN() condition?
https://stackoverflow.com/questions/920353/can-i-bind-an-array-to-an-in-condition

**Comment by Rnkumar** [comment]
To bind an array to an IN() condition in golang, this might help.

```
db, err := sqlx.Open("godror", connectionString)
var result []Result

query, args, err := sqlx.In("SELECT * FROM whatever WHERE fieldA in (?)", []string{"a", "b", "c"})
if err != nil {
// error handling
}

query = db.Rebind(query)

err = db.SelectContext(ctx.Request.Context(), &result, query, args...)
if err != nil {
// error handling
}

fmt.Println(result)
```

	
You would get the required rows in result array.
