### ISSUE TITLE
Prefetch is (incorrectly) enabled for SELECT statements in exec

### ISSUE THREAD

**Issue by kurt-google** [mattn/go-oci8#279]
https://github.com/mattn/go-oci8/blob/master/statement.go#L661

Enables prefetch when a select statement is passed to Exec. This fails with ORA-16196 since the Exec flow does not setup anywhere to load rows.

Exec is explicitly not for row returning calls but enabling exec for select statements can be helpful even without returning any rows. When the statement type is `OCI_STMT_SELECT` `OCIStmtExecute()`  should be called with `iter` set to 0. You can query this information via a method like

```C
func (s *OCI8Stmt) Type() C.ub2 {
    r := C.WrapOCIAttrGetUb2(s.s, C.OCI_HTYPE_STMT, C.OCI_ATTR_STMT_TYPE, (*C.OCIError)(s.c.err))
    if r.rv != C.OCI_SUCCESS {
        return C.OCI_STMT_UNKNOWN
   }
   return r.num
}
```
This is how oracle's odpi library works.

**Comment by kurt-google** [comment]
Allowing users to issue any valid SQL into Exec is helpful from an interface perspective. Users need not worry about some SQL failing in Exec and only working in Query and visa versa.

In my case I care only to check that a SQL can execute without caring for its result. 

I also find it very hard to believe oracle does not have SQL callable functions without side-effects though they may be rare.

**Comment by MichaelS11** [comment]
I hear what you are saying. I look at this another way, if select statement is being done in exec that means something went wrong and it should error.

I would leave it as is but @mattn makes the final call.

**Comment by mattn** [comment]
I don't understand what is really problem.

**Comment by kurt-google** [comment]
The problem is that if you execute
```
db.Exec("Select 1 from dual")
```
An error is returned (`ORA-16196`). The equivalent `Exec` call in mysql, postgres, and even your own go-sqlite3 driver returns successfully.

I think that `Exec` when called with a `SELECT` statement should return successfully if the query executes successfully, just like the other go drivers.

The rest of the OP is a possible solution to the `ORA-16196` error which is based on looking at Oracle's ODPI library.

**Comment by MichaelS11** [comment]
@mattn So can we close this?

**Comment by MichaelS11** [comment]
@mattn Close this?
