### ISSUE TITLE
function ColumnTypeScanType(i int) case C.SQLT_NUM return int64 cause scan failed 

### ISSUE THREAD

**Issue by eyeits** [mattn/go-oci8#280]
function ColumnTypeScanType(i int) case C.SQLT_NUM return int64 cause scan failed, the actual value is float64 type. Can C.SQLT_NUM database type return to golang float64 type?

**Comment by MichaelS11** [comment]
What would a create table look like for a SQLT_NUM number type?

**Comment by eyeits** [comment]
round function sometimes return SQLT_NUM

**Comment by MichaelS11** [comment]
Do you have a test case/code/SQL to reproduce this issue? Otherwise doubtful I would be able to fix it.

**Comment by MichaelS11** [comment]
Close this?

**Comment by eyeits** [comment]
close
