### ISSUE TITLE
fatal error: oci.h: No such file or directory (Win 64bit)

### ISSUE THREAD

**Issue by lindamanf** [mattn/go-oci8#284]
I  can't solve this error.

> $ go get github.com/mattn/go-oci8
> #-github.com/mattn/go-oci8
> In file included from ..\github.com\mattn\go-oci8\cHelpers.go:3:
> ./oci8.go.h:1:10: fatal error: oci.h: No such file or directory
>  #include <oci.h>
>           ^~~~~~~
> compilation terminated.
> 

The follow is the my development env.
*OS: Windows 7 (64bit Operating System)
*Instant Client
```
instantclient-basic-windows.x64-11.2.0.4.0.zip
instantclient-sdk-windows.x64-11.2.0.4.0.zip
instantclient-sqlplus-windows.x64-11.2.0.4.0.zip

```
*env variable
```
GOPATH=C:\Users\FumiyaHayashi\go
GOROOT=C:\Go
Path=(other pathes);C:\app\mingw64\bin
PKG_CONFIG_PATH=C:\app\instantclient_11_2\pkgconfig

```
*oci8.pc
```
prefix=C:/app/instantclient_11_2
exec_prefix=${prefix}
libdir={prefix}/sdk/lib/msvc
includedir={prefix}/sdk/include

glib_genmarshal=glib-genmarshal
gobject_query=gobject-query
glib_mkenums=glib-mkenums

Name: oci8
Description: oci8 library
Libs: -L${libdir} -loci
Cflags: -I${includedir}
Version: 11.2

```

If there is necessary information, please teach me.

**Comment by MichaelS11** [comment]
Did you install pkg-config then run it?

`pkg-config oci8`

pkg-config is it's own download and install.

**Comment by lindamanf** [comment]
I downloaded pkg-config in reference to [this site](https://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows).

and place theme in C:\app\mingw64\bin .

**Comment by lindamanf** [comment]
Thank you for rep.

I downloaded pkg-config in reference to this site.
and place theme in C:\app\mingw64\bin .

**Comment by MichaelS11** [comment]
Did that fix it?

**Comment by lindamanf** [comment]
No, I didn't fix.
When I post this issue, pkg-config has been installed.

**Comment by MichaelS11** [comment]
Did you update PKG_CONFIG_PATH to point to the location where oci8.pc file is located? Did the command `pkg-config oci8` work?

Recommend searching the issues here, lots of people have had the same type of issue. Almost always is an Oracle driver or settings setup misconfiguration.

**Comment by lindamanf** [comment]
Yes, PKG_CONFIG_PATH is correct path.
```
C:\app\instantclient_11_2\pkgconfig>set PKG_CONFIG_PATH
PKG_CONFIG_PATH=C:\app\instantclient_11_2\pkgconfig

C:\app\instantclient_11_2\pkgconfig>dir
2018/11/06  15:49    <DIR>          .
2018/11/06  15:49    <DIR>          ..
2018/11/07  12:28               303 oci8.pc
```

Executing **_pkg-config oci8_** command, Nothing is showing.
```
C:\app\instantclient_11_2\pkgconfig>pkg-config oci8

```
Here is wrong. I try to fix that.

**Comment by MichaelS11** [comment]
pkg-config oci8 give usually gives no output when correct.

**Comment by mattn** [comment]
@lindamanf try `pkg-config --cflags oci8`

**Comment by lindamanf** [comment]
@mattn 
Thanks for the reply, mattn.
```
c:\>pkg-config --cflags oci8
-I{prefix}/sdk/include
```

**Comment by MichaelS11** [comment]
Figure this out?

**Comment by lindamanf** [comment]
No. 
I try to build on CentOS.
Thank you for my going out to me.
