### ISSUE TITLE
Getting undefined: C  error on doing a go build

### ISSUE THREAD

**Issue by sheetal-s** [mattn/go-oci8#285]
I followed these steps:
go get -d -u github.com/mattn/go-oci8
cd $GOPATH/src/github.com/mattn/go-oci8
go build

I am getting this error : 

/home/cohesity/workspace/restricted/.go/src/github.com/mattn/go-oci8/rows.go:271: undefined: C in C.OCI_DTYPE_PARAM
/home/cohesity/workspace/restricted/.go/src/github.com/mattn/go-oci8/rows.go:357: undefined: C in C.OCI_DTYPE_PARAM
/home/cohesity/workspace/restricted/.go/src/github.com/mattn/go-oci8/rows.go:391: undefined: C in C.OCI_DTYPE_PARAM
/home/cohesity/workspace/restricted/.go/src/github.com/mattn/go-oci8/statement.go:373: undefined: C in C.OCI_DTYPE_PARAM

Is this a bug or am I missing something?

**Comment by sheetal-s** [comment]
Thanks for the quick reply. Also my go version is 1.7, hope that isnt a problem.

**Comment by MichaelS11** [comment]
Go 1.9 or higher is required.

**Comment by mattn** [comment]
Go version is too older. Please reopen if you still have problem on Go 1.9 or higher.
