### ISSUE TITLE
Cross compile Windows to Linux

### ISSUE THREAD

**Issue by ajthomp2** [mattn/go-oci8#309]
How can I cross compile from windows to linux?  I got the error below.

> GOOS=linux GOARCH=amd64 go build
# runtime/cgo
gcc_linux_amd64.c: In function '_cgo_sys_thread_start':
gcc_linux_amd64.c:62:2: error: unknown type name 'sigset_t'; did you mean '_sigset_t'?
  sigset_t ign, oset;
  ^~~~~~~~
  _sigset_t
gcc_linux_amd64.c:67:2: error: implicit declaration of function 'sigfillset' [-Werror=implicit-function-declaration]
  sigfillset(&ign);
  ^~~~~~~~~~
gcc_linux_amd64.c:62:16: error: unused variable 'oset' [-Werror=unused-variable]
  sigset_t ign, oset;
                ^~~~
cc1.exe: all warnings being treated as errors

**Comment by mattn** [comment]
Because you didn't use cross C compiler.

**Comment by MichaelS11** [comment]
@ajthomp2 Suggest checking out some of the issues. 

This in particular might help:

https://github.com/mattn/go-oci8/issues/84#issuecomment-420784283

**Comment by zhaofengcumt** [comment]
in #84 (comment) i did not understand ,can you tell me how i can do to compile from windows to linux,thanks?

**Comment by zhaofengcumt** [comment]
@ajthomp2  can you tell me how to solve this problem,thanks!

**Comment by shuidaan** [comment]
D:\Go\gowork\landlord\main>go build -o ../ddz4
# runtime/cgo
gcc_linux_amd64.c: In function '_cgo_sys_thread_start':
gcc_linux_amd64.c:61:2: error: unknown type name 'sigset_t'; did you mean '_sigset_t'?
  sigset_t ign, oset;
  ^~~~~~~~
  _sigset_t
gcc_linux_amd64.c:66:2: error: implicit declaration of function 'sigfillset' [-Werror=implicit-function-declaration]
  sigfillset(&ign);
  ^~~~~~~~~~
gcc_linux_amd64.c:61:16: error: unused variable 'oset' [-Werror=unused-variable]
  sigset_t ign, oset;
                ^~~~
cc1.exe: all warnings being treated as errors

**Comment by DenKn** [comment]
The same problem on Windows for Linux. How to solve this?

**Comment by mattn** [comment]
go-oci8 is CGO module. And you are trying to build Linux binary on Windows. So you NEED to use cross C compiler. This is NOT host C compiler. gcc which you use is not cross C compiler.

**Comment by woshizhicainiaoluguo** [comment]
> The same problem on Windows for Linux. How to solve this?
@DenKn same problem on Windows for Linux. How to solve this one year later...  Thanks
