### ISSUE TITLE
Execute query "select '中文'  from dual" rows.Next() throw ORA-01406: fetched column value was truncated

### ISSUE THREAD

**Issue by nh-live** [mattn/go-oci8#313]
Hi mattn
Execute query "select '中文'  from dual" rows.Next() throw ORA-01406: fetched column value was truncated.
Thanks

**Comment by MichaelS11** [comment]
Duplicate of https://github.com/mattn/go-oci8/issues/306 ? If so, close this?

**Comment by nh-live** [comment]
yes
