### ISSUE TITLE
Stmt.exeC Env.ociError ORA-03135: connection lost contact\nProcess ID: 61366\nSession ID: 2867 Serial number: 60060

### ISSUE THREAD

**Issue by chakrapani123** [mattn/go-oci8#315]
hello,

i am making updates to oracle version 12.2.0.1 and using the following code snippet..

func (o *Oracle) UnReserveCdb(cdbname string) (unreserved bool, err error) {

	fmt.Println(cdbname)
	udb := o.Db
	utx, err := udb.Begin()
	if err != nil {
		fmt.Println("error", err)
	}
	ures, err := utx.Exec("update testdb.DATABASE_INFO set CDB_CONSUMED = 'YES' , CDB_AVAILABLE = 'NO' where CDB_NAME = :1", cdbname)
	if err != nil {
		fmt.Println("error in exec: ", err)
		utx.Rollback()
		return unreserved, err
	}
	if err := utx.Commit(); err != nil {
		fmt.Println("error", err)
	}
	urowCnt, err := ures.RowsAffected()
	if err != nil {
		fmt.Println("error", err)
	}
	fmt.Println("rows changed ", urowCnt)

	if urowCnt > 0 {
		return true, err
	} else {
		return false, err
	}
}

type Oracle struct {
	Driver        string
	ConnectString string
	Db            *sql.DB
	logger        log.Logger
}

func NewOracleConnection(cfg config.Config, log log.Logger) (Connection, error) {
	var err error
	o := &Oracle{
		Driver:        cfg.DB.Driver,
		ConnectString: cfg.DB.ConnectString,
		logger:        log,
	}
	o.Db, err = sql.Open(o.Driver, o.ConnectString)
	if err != nil {
		log.Log("event", "connecting to database", "err", err.Error())
	}
	return o, err
}

thanks
Chakri

**Comment by MichaelS11** [comment]
Connection errors do happen. Not sure what you are asking or what the problem you are wanting help with.

The best way to get help is to have a small code snippet and ALL SQL involved that is easily repeatable by someone else so the error can be reproduced.

**Comment by MichaelS11** [comment]
@chakrapani123 Everything alright now? Close this?

**Comment by chakrapani123** [comment]
Yes . Please

thanks
Chakri
