### ISSUE TITLE
prefetch_rows does not work with clobs?

### ISSUE THREAD

**Issue by dbgeek** [mattn/go-oci8#323]
Looks like when query having a clob in the resultset. Then go-oci8 go back to do fetch for each query.

[Gist with some test code](https://gist.github.com/dbgeek/5967a8d9bad92dae197aa048be120bd4)

**Output**
> 2019/01/20 10:54:59 Query with clob took 2.097061085s
> 2019/01/20 10:54:59 Query with clob SQLID: 1836z1tr3b785, fetches:1001 , rowsProcessed: 1000

**Comment by MichaelS11** [comment]
I am not sure if Oracle OCI C driver will prefetch clobs or not.

Here is the relevant go-oci8 code:

https://github.com/mattn/go-oci8/blob/9816237c2e725b378da0a7b3f675e539f477d701/rows.go#L104

https://github.com/mattn/go-oci8/blob/9816237c2e725b378da0a7b3f675e539f477d701/connection.go#L358-L395

**Comment by MichaelS11** [comment]
From:
https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lnoci/oci-function-server-round-trips.html#GUID-AD3700EF-9293-4E14-807E-43A6B395CBD5

> OCILobRead2() | 0 or 1

> For calls whose number of round-trips is "0 or 1," if LOB buffering is on, and the request can be satisfied in the client, no round-trips are incurred.

What is LOB buffering? Is it something we should look into?

**Comment by dbgeek** [comment]
I get the same behavior when I do the test in sqlplus and that using OCI  I guess. But when I try with sqlcli that is a java program och uses JDBC it only does one fetch for the 1000 rows.

**Comment by dbgeek** [comment]
This can maybe be something?
[OCI_ATTR_LOBPREFETCH_SIZE](https://docs.oracle.com/cd/B28359_01/appdev.111/b28395/oci07lob.htm#CHDDHFAB)

**Comment by cjbj** [comment]
We  worked through the features and issues in [ODPI-C](https://github.com/oracle/odpi) (used by [goracle](https://github.com/go-goracle/goracle), [node-oracledb](https://github.com/oracle/node-oracledb/), [cx_Oracle](https://github.com/oracle/python-cx_Oracle/), etc) and decided against LOB prefetching and went with direct fetches (as well as streaming).  Coupled with using array fetches instead of prefetching, hopefully the LOB experience is smoother for the general user of the mentioned language drivers.  We are also working with Oracle's LOB team to make LOB improvements, but that's a longer term thing.

For go-oci8, I'll let you experiment :)

**Comment by MichaelS11** [comment]
Was thinking about enabling the the user session setting OCI_ATTR_DEFAULT_LOBPREFETCH_SIZE

https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lnoci/handle-and-descriptor-attributes.html#GUID-FB263210-118E-4DB3-A840-1769EF0CB977

If prefetch_lob_size is set to something greater than 0 then set OCI_ATTR_DEFAULT_LOBPREFETCH_SIZE to that number. No idea if that setting will help anything or not, but easy enough to add to the driver if wanted. Please let me know.

**Comment by dbgeek** [comment]
Would be awesome if you could add OCI_ATTR_DEFAULT_LOBPREFETCH_SIZE. Then I can see if that make some difference.

**Comment by MichaelS11** [comment]
Should be able to add it this week.

**Comment by cjbj** [comment]
Beware: there are a few bugs with LOB prefetch not fixed until 12.2.  That's why https://oracle.github.io/node-oracledb/doc/api.html#propdblobprefetchsize was marked as disabled.  In the meantime, node-oracledb got LOB direct fetches as strings (via ODPI-C) and LOB prefetching is redundant, so we haven't re-enabled it.

**Comment by dbgeek** [comment]
> Beware: there are a few bugs with LOB prefetch not fixed until 12.2. That's why https://oracle.github.io/node-oracledb/doc/api.html#propdblobprefetchsize was marked as disabled. In the meantime, node-oracledb got LOB direct fetches as strings (via ODPI-C) and LOB prefetching is redundant, so we haven't re-enabled it.

@cjbj LOB prefetch bugs are them in the DB client or the server side? Our Database is running 12.1.0.2 and our go program using Oracle instant client 12.2..

**Comment by cjbj** [comment]
@dbgeek both client & server.  You may or may not tickle them.  FWIW there is a LOB example for goracle (am I allowed to mention that here?) in the conference slides https://static.rainfocus.com/oracle/oow18/sess/1525791357522001Q5tc/PF/DEV5047%20-%20The%20Go%20Language_1540587475596001afdk.pdf

**Comment by MichaelS11** [comment]
@dbgeek What is the plan? Are we good now? Close this? Something else?

**Comment by dbgeek** [comment]
@MichaelS11 Looks like #325 is still open so I have not been able to test it or is it in master?

**Comment by MichaelS11** [comment]
You can pull it from here for testing if you want.
https://github.com/MichaelS11/go-oci8/tree/lob

**Comment by dbgeek** [comment]
> You can pull it from here for testing if you want.
> https://github.com/MichaelS11/go-oci8/tree/lob

I look like it does not work/help with the new version. Here is my [gist](https://gist.github.com/dbgeek/59ad81e941afb416faf83698d03676fd) that show the example code that I have run.

my go.mod this i guess point against your lob branch
```
require github.com/MichaelS11/go-oci8 v0.0.0-20190123233825-70888477cb00 // indirect
```

Done different test. Look like prefetch_lob_size does not have any effect.
```
2019/01/31 09:46:13 conn: system/manager@localhost:1521/pdb1?prefetch_rows=1000&prefetch_memory=1000000&prefetch_lob_size=10000
2019/01/31 09:46:15 Start looping result
2019/01/31 09:46:17 Query with clob took 2.098076561s
2019/01/31 09:46:17 Query with clob SQLID: 1836z1tr3b785, fetches:1001 , rowsProcessed: 1000
bash-4.4$ export DB_PREFETCHMEMORY=0
bash-4.4$ export DB_PREFETCHROWS=1000
bash-4.4$ ./main2
2019/01/31 09:46:35 conn: system/manager@localhost:1521/pdb1?prefetch_rows=1000&prefetch_memory=0&prefetch_lob_size=10000
2019/01/31 09:46:37 Start looping result
2019/01/31 09:46:39 Query with clob took 2.194997793s
2019/01/31 09:46:39 Query with clob SQLID: 1836z1tr3b785, fetches:1001 , rowsProcessed: 1000
bash-4.4$ export DB_PREFETCHROWS=0
bash-4.4$ ./main2
2019/01/31 09:46:45 conn: system/manager@localhost:1521/pdb1?prefetch_rows=0&prefetch_memory=0&prefetch_lob_size=10000
2019/01/31 09:46:46 Start looping result
2019/01/31 09:46:48 Query with clob took 2.159642986s
2019/01/31 09:46:48 Query with clob SQLID: 1836z1tr3b785, fetches:1001 , rowsProcessed: 1000
```

**Comment by MichaelS11** [comment]
Ok, not sure how else to help.

If there is some C/C++ or other code that is using the Oracle OCI driver which handles LOBs better I am happy to look at it. Just need to understand what calls need to happen to the Oracle OCI driver to make the prefetch better.

**Comment by dbgeek** [comment]
Thanks, @MichaelS11 to look into this issue. Will use go-oracle for the lob stuff.

**Comment by MichaelS11** [comment]
Welcome

@mattn Any idea what needs to happen to help with LOBs prefetch?

**Comment by mattn** [comment]
Do you know the example code that can handle LOB prefetch?

**Comment by MichaelS11** [comment]
I do not

**Comment by MichaelS11** [comment]
@mattn Could you share with me the LOB prefetch code example?

**Comment by mattn** [comment]
I don't have.
