### ISSUE TITLE
Connect string with Oracle wallet

### ISSUE THREAD

**Issue by bop0hz** [mattn/go-oci8#329]
Hi,

I could not find how to connect with Oracle wallet.
For example, I am able to connect in this way:

> sqlplus /@tnsentry

Is it possible to connect with Oracle wallet credentials in go-oci8?

**Comment by MichaelS11** [comment]
Looking at this:

https://docs.oracle.com/en/cloud/paas/atp-cloud/atpug/connect-preparing.html#GUID-3667EC68-930E-4566-95B3-DFA24203A8FF

I think it should work but do not have wallet setup to test. The connect string would be something like:
username/password@tnsname_entry

**Comment by MichaelS11** [comment]
@bop0hz Get this figured out? Can this be closed?

**Comment by bop0hz** [comment]
Actually not yet. I have no user/password with wallet. My connstring is mentioned above.
I looked into the source code and there are no conditions to handle my case..

**Comment by MichaelS11** [comment]
Or right, of course. Did you try just using the tnsnames entry? If so, what happens?

**Comment by MichaelS11** [comment]
@bop0hz How did it go?

**Comment by bop0hz** [comment]
> @bop0hz How did it go?

Sorry, Actually I have changed the oracle go driver to another. I will try it again with go-oci8 to get the error.

**Comment by cjbj** [comment]
@bop0hz out of interest, why did you decide to use go-oci8?

**Comment by cjbj** [comment]
Ignore me; too much github email and not enough coffee

**Comment by bop0hz** [comment]
> Or right, of course. Did you try just using the tnsnames entry? If so, what happens?

ORA-01017: invalid username/password; logon denied

**Comment by MichaelS11** [comment]
Is your sqlnet.ora file setup? What does it look like? Is your tnsnames.ora file setup? What does it look like?

**Comment by MichaelS11** [comment]
@bop0hz Close this?

**Comment by bop0hz** [comment]
> @bop0hz Close this?

ok, let's close..

**Comment by MichaelS11** [comment]
If you would like to troubleshoot more, happy to help. Otherwise, can you please close it?
