### ISSUE TITLE
go 1.12 windows/amd64 with go-oci8 crashes

### ISSUE THREAD

**Issue by erwindw** [mattn/go-oci8#331]
Installation of go-oci8 seems to be ok, followed the instructions accurately, but

go test -v github.com/mattn/go-oci8 -tags noPkgConfig -args -disableDatabase=false -hostValid replace_with_your_db_host -username scott -password tiger
fails with
exit status 3221225781

Any ideas how to resolve that? I've tried a lot already

**Comment by erwindw** [comment]
Installation of go-oci8 seems to be ok, followed the instructions accurately, but

go test -v github.com/mattn/go-oci8 -tags noPkgConfig -args -disableDatabase=false -hostValid replace_with_your_db_host -username scott -password tiger
fails with 
exit status 3221225781

Any ideas how to resolve that? I've tried a lot already

**Comment by MichaelS11** [comment]
The exit status 3221225781 usually means an Oracle setup issue. It maybe also mean a C++ compiler setup issue, but that is probably not the case.

Please double check all the steps in the readme installation. Note that you either need to use pkgConfig or the CGO_CFLAGS and CGO_LDFLAGS environmental variables.

Note I install Go 1.12 on Linux and tested, worked fine.

**Comment by erwindw** [comment]
Ok, I will also try on Linux.

Note that the build was successful. I've checked with dumpbin and all dll's are available. Just simple code with import of go-oci8 fails to run.

**Comment by MichaelS11** [comment]
Will most likely work with Go 1.12 on Windows as well, just saying that I did test it on Linux. I am running Go 1.11 on my Windows box.

**Comment by erwindw** [comment]
Confirmed that on ubuntu it works fine.
