### ISSUE TITLE
调用存储过程，out参数为null时候报错

### ISSUE THREAD

**Issue by zhiyunliu** [mattn/go-oci8#332]
我这样解决请帮忙看看是否合理。

https://github.com/zhiyunliu/go-oci8/commit/8fd85141081b4c5855a68f3b1fd2de9511160195#diff-eaeb246e5dfb1f0b15828b3713028f45

**Comment by mattn** [comment]
Please write english.

**Comment by zhiyunliu** [comment]
title: Call the stored procedure and report an error when the out parameter is null. i used this way to solve it. is it fine.
https://github.com/zhiyunliu/go-oci8/commit/8fd85141081b4c5855a68f3b1fd2de9511160195

**Comment by mattn** [comment]
What do you mean here?

https://github.com/zhiyunliu/go-oci8/commit/8fd85141081b4c5855a68f3b1fd2de9511160195#diff-eaeb246e5dfb1f0b15828b3713028f45R89

**Comment by zhiyunliu** [comment]
This is my modification code.
just want to tell you what i changed.

**Comment by zhiyunliu** [comment]
sorry , my english is poor

**Comment by mattn** [comment]
okay, now i understood what you mean. thank you.

**Comment by MichaelS11** [comment]
@zhiyunliu  Can you please provide an SQL and PL/SQL example of the problem so we can make a test case?

**Comment by zhiyunliu** [comment]
It's incredible that using the new version of oci8 works well. I did not find any inconsistencies in acquisition errors.  in my fork version ,it is still working error.
`create or replace procedure p_test_output(v_in  varchar2,
                                          v_in2 number,
                                          v_n   out number,
                                          v_b   out varchar2) is
begin
  v_n := 1;
end;
`
![image](https://user-images.githubusercontent.com/29598760/54667920-91e52780-4b28-11e9-8609-655e02ccf733.png)

**Comment by MichaelS11** [comment]
@zhiyunliu So there is no issue?

**Comment by zhiyunliu** [comment]
yeah,i suppose so.

**Comment by zhiyunliu** [comment]
well ,i want to known how to fix this in new version also.

**Comment by zhiyunliu** [comment]
there are same  in getError.
![image](https://user-images.githubusercontent.com/29598760/54735894-7854e600-4be3-11e9-9e3a-c743917934ef.png)

![image](https://user-images.githubusercontent.com/29598760/54735945-b94cfa80-4be3-11e9-8749-61cb4a206e28.png)

**Comment by MichaelS11** [comment]
Are you asking how to fix ORA-01405? If so, did you try running your package in sql plus to see what is going on?

**Comment by zhiyunliu** [comment]
yes,the procedure works fine, but raise error in my fork version.
![image](https://user-images.githubusercontent.com/29598760/54799242-59b02700-4c97-11e9-933f-87e636618607.png)

**Comment by MichaelS11** [comment]
In your Go code, try changing `var pb string` to `var pb sql.NullString` and let me know what happens.

**Comment by zhiyunliu** [comment]
raise [ORA-01405] error yet.
![image](https://user-images.githubusercontent.com/29598760/54803588-1069d280-4cab-11e9-845f-1d46277443b7.png)

**Comment by zhiyunliu** [comment]
i change my project to use the lastest version,so forget the issue now.then i have free time i will find what's the reason.  thank you.
