### ISSUE TITLE
Can anybody give an example to how to connect to timesten using go-oci8?

### ISSUE THREAD

**Issue by sinylei** [mattn/go-oci8#336]
Can anybody give an example to how to connect to timesten using go-oci8?

**Comment by MichaelS11** [comment]
@cjbj
Does oci8 support connecting to timesten?

**Comment by cjbj** [comment]
@MichaelS11 OCI8 does connect to TimesTen: https://blogs.oracle.com/timesten/is-the-python-cx_oracle-sql-driver-fast-enough-for-database-benchmarks

**Comment by MichaelS11** [comment]
@sinylei Did you have any luck getting it to work?

**Comment by MichaelS11** [comment]
@mattn Close this?
