### ISSUE TITLE
the cross-compilation has gone wrong in windows

### ISSUE THREAD

**Issue by robinsoon** [mattn/go-oci8#342]
The program has been debugged and run correctly, 
but the cross-compiler has been released to other machines to run out of order.

```
go-oci8.init.0()    go-oci8/globals.go:185 +0x223
panic:The system cannot find the path specified.
```

Cgo brings many difficulties to the release of go program. Static compilation into stand-alone executable files is good. Oracle drivers have been puzzling for several days. I hope you can give me  some advice on how to configure and distribute programs based on this component (github.com mattn go-oci8) under windows.

I want to make it run successfully in different system environments.

**Comment by MichaelS11** [comment]
Have you checked this out?

https://github.com/mattn/go-oci8/issues/84#issuecomment-420784283

Cross compile can be really tricky. I would suggest going from Linux to other systems. Going from Windows to other system can be even more tricky.

**Comment by robinsoon** [comment]
> Have you checked this out?
> 
> [#84 (comment)](https://github.com/mattn/go-oci8/issues/84#issuecomment-420784283)
> 
> Cross compile can be really tricky. I would suggest going from Linux to other systems. Going from Windows to other system can be even more tricky.

There's really nothing I can do. I'll continue to focus on this solution in the future. Maybe a good IDE can do it. Thank you for your advice.
