### ISSUE TITLE
ORA-01735: invalid ALTER TABLE option

### ISSUE THREAD

**Issue by misterEggroll** [mattn/go-oci8#346]
The command being used as a part of my code works when using sqlplus.

![Screenshot 2019-07-15 at 3 58 37 PM](https://user-images.githubusercontent.com/12442230/61210324-bf7a6000-a719-11e9-8c22-94532be97613.png)

Code:
```
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/mattn/go-oci8"
)

func main() {
	db, err := sql.Open("oci8", "<sysDBA connectionString>")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer func(db *sql.DB) {
		if err := db.Close(); err != nil{
			fmt.Println(err)
		}
	}(db)

	_sql := `ALTER TABLE "CONVERSATIONS" ADD "TAGGER_METADATA" CLOB CHECK("TAGGER_METADATA" IS JSON);`

	result, err := db.Exec(_sql)
	if err != nil {
		fmt.Println("Issue with altering table...")
		fmt.Println(err)
		return
	}

	fmt.Println(result.RowsAffected())
}
```

DB : Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
The DB is running on: **Oracle Linux Server 7.6**
The client code is running on: **MacOS Mojave 10.14.5** 

@mattn I've tried to check older issues similar to this one but I couldn't find any. Please point out if this is a duplicate. If not, can you share example code where tables can be updated ?

**Comment by MichaelS11** [comment]
Greetings @misterEggroll ,

In general alter table commands do work, use them all the time. Have you tried removing the `;` from the end of the SQL?

If still having issues, could you please provide the full SQL (create table and alter table) and code together?

**Comment by misterEggroll** [comment]
@MichaelS11 Removing the ";" command at the end of the SQL did the trick. I think this is the same reason why my alter table commands weren't working when attempting to add a foreign key to the table.

Thank you for you quick response!
