### ISSUE TITLE
How to verify dsn？

### ISSUE THREAD

**Issue by Karel-Xiang** [mattn/go-oci8#354]
When I pass in an incorrect dsn, e.g. "system:pwd?123?tcp(20.23.136.77:1521/orcl/), any query statement is not returned

**Comment by MichaelS11** [comment]
Not sure what you are asking here. If you are trying to send bad connection strings to the oci8 connection string parse code it will probably will fail in unexpected ways.

The format is here:
https://godoc.org/github.com/mattn/go-oci8#ParseDSN
PR https://github.com/mattn/go-oci8/pulls is correcting [/instance_name] to [/service_name].
If you want to use instance name it is [:instance_name].

**Comment by Karel-Xiang** [comment]
Ok, thank you, my English is not very good, but you solved my problem.
