### ISSUE TITLE
Does context not work?

### ISSUE THREAD

**Issue by Karel-Xiang** [mattn/go-oci8#355]
`ctx, cancel := context.WithTimeout(context.Background(), 6*time.Second)
	defer cancel()

	start := time.Now()
	err := db.PingContext(ctx) 
    fmt.Println(err, ctx.Err())
    fmt.Println(ctx.Deadline())
	fmt.Println(time.Since(start))

    if err != nil { 
        fmt.Println("ping error:", err) 
        return
    }`
but it turned out like this.
ORA-12547: TNS:lost contact
 context deadline exceeded
2019-09-19 10:59:02.784253242 +0800 CST m=+6.004184455 true
13.031078811s
ping error: ORA-12547: TNS:lost contact

**Comment by MichaelS11** [comment]
For connection timeout I suggest using tnsnames.ora with CONNECT_TIMEOUT or sqlnet.ora file with SQLNET.OUTBOUND_CONNECT_TIMEOUT. See: https://github.com/mattn/go-oci8/issues/352

Also there is a PR for ping context:
https://github.com/mattn/go-oci8/pull/353

**Comment by MichaelS11** [comment]
@Karel-Xiang Try the timeout settings?

**Comment by Karel-Xiang** [comment]
Thank you, you solved my problem. The context.WithTimout is only useful when dsn is right. Now I use sqlnet.ora file with SQLNET.OUTBOUND_CONNECT_TIMEOUT and  context.WithTimout together.

**Comment by MichaelS11** [comment]
Most welcome. Please close this issue.
