### ISSUE TITLE
Reading BLOBs bigger than 4000 bytes

### ISSUE THREAD

**Issue by AndrewWPhillips** [mattn/go-oci8#357]
I am reading from a table with a BLOB (image) field that I need.  I'm not sure how big they can get but I have seen some over 500Kb.  When I get the field it appears to be truncated to 4000 bytes.  I believe this is due to a fixed buffer being used (see globals.go).

```
	lobBufferSize      = 4000
```

Is there a way around this without modifying the code?

**Comment by MichaelS11** [comment]
Should be able to, there are tests in the code that do so. How are you trying to read the value in? Do you have a code example? Try reading it in as an interface or byte slice?

**Comment by AndrewWPhillips** [comment]
I created a simple program to demonstrate.  (Note that error handling, calls to close() etc were removed for simplicity.)
```
func main() {
	db, _ := sql.Open("oci8", "XXX/xxx@xxx/xxx")
	ctx, _ := context.WithTimeout(context.Background(), 55*time.Second)
	rows, _ := db.QueryContext(ctx, "select IMAGE from XXX where IMAGE is not null")

	var image sql.RawBytes
	for count := 0; rows.Next(); count++ {
		_ = rows.Scan(&image)
		log.Printf("len %d\n", len(image))
	}
}
```
I am reading in as sql.RawBytes which is a byte slice.  When I run the above it prints 4000 many times.

**Comment by MichaelS11** [comment]
Did you update oci8 to the latest? When you check for errors are there any?

**Comment by AndrewWPhillips** [comment]
I did `go get` of the library today.  Open(), Query() and Scan() do not return an error.

**Comment by MichaelS11** [comment]
Could you please do `go get -u github.com/mattn/go-oci8`?

Also could you please check `rows.Err()`?

If still having issues after that, could you try doing almost the same as the below example except just print what dest[0] type is and what len of dest[0] is?

https://godoc.org/github.com/mattn/go-oci8#example-package--SqlSelect

**Comment by AndrewWPhillips** [comment]
Thanks, the -u (option to go get) fixed it.
