### ISSUE TITLE
GCC failed -i386 architecture of input file ... incompatible with i386:x86-64 output

### ISSUE THREAD

**Issue by yokesnowwolf** [mattn/go-oci8#361]
Hi. I get the error after go build with mingw:

`D:\devtools\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
D:/devtools/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\xxx\AppData\Local\Temp\go-link-250400547\000000.o' is
incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status`

### Build batch command:
`@echo off

set GOARCH=amd64

set GOOS=windows

go build -o .....`

### go-oci8 version:
github.com/mattn/go-oci8 v0.0.0-20191029050031-9c5d7cd922fc h1:6e10jghyKVKo0/3g2Ub+6Wr+3dUKKd8/JyGP/I1XKPk=

### OS Version:
`C:\>ver

Microsoft Windows [版本 10.0.18362.418]`

### GO Version:
`C:\>go version

go version go1.13.4 windows/amd64`

### GCC Version:
`C:\>gcc --version

gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

### instantclient:
`C:\>pkg-config --cflags -- oci8

-ID:/devtools/oracle/instantclient_12_2/sdk/include/ -ID:/devtools/mingw/mingw64/include`

oci8.pc file content：

`# Package Information for pkg-config

prefixdir=D:/devtools/oracle/instantclient_12_2
libdir=${prefixdir}/sdk/lib/msvc/
includedir=${prefixdir}/sdk/include/
gcclib=D:/devtools/mingw/mingw64/lib
gccinclude=D:/devtools/mingw/mingw64/include

Name: oci8
Description: Oracle Instant Client
Version: 12.2
Libs: -L${libdir} -L${gcclib} -loci
Libs.private:
Cflags: -I${includedir} -I${gccinclude}`

Does anyone known how to avoid the wrong?
Thanks very much!

**Comment by MichaelS11** [comment]
Maybe have some 32 bit software mixed in with 64 bit?

**Comment by yokesnowwolf** [comment]
I'm try find what about win32 again，the cause is the prj directory has a admin Privilege request resource file！
The file from my project template and only for win32.
removed it and then fine.
Thanks!
