### ISSUE TITLE
Failed to compile a file on Linux that runs on arm

### ISSUE THREAD

**Issue by xuwenjj251** [mattn/go-oci8#366]
My linux is centos7.4
Error is:
![image](https://user-images.githubusercontent.com/58059375/69395069-af523d00-0d18-11ea-9e80-7c0713675be5.png)

**Comment by mattn** [comment]
Probably, you don't install cross C compiler for amd64 (not for arm)

**Comment by MichaelS11** [comment]
Did you check out some of the other issues about cross compling?

**Comment by MichaelS11** [comment]
@xuwenjj251 All good? Close this?

**Comment by MichaelS11** [comment]
@mattn Close this?

**Comment by daicheng123** [comment]
老铁，在arm上编译，你搞定了吗

**Comment by PengFei-io** [comment]
> 

oracle 官网不支持.你没办法
