### ISSUE TITLE
Periodic core dump

### ISSUE THREAD

**Issue by japettyjohn** [mattn/go-oci8#37]
I have a webapp written in using this driver, it makes one sql instance and re-uses that everywhere. Periodically the app core dump. The app doesn't do much more then queries and output the results as json. Not always on the same query, seems like it sometimes goes even when not running a query.

I'm using oracle 9i with driver 11.2 on fedora 16 with gcc version 4.6.3. Haven't figured out how to get the core dump yet, currently just get a message of:

Trace/breakpoint trap   (core dumped) ./bin/site

**Comment by mattn** [comment]
too old
