### ISSUE TITLE
CLOB is trunc

### ISSUE THREAD

**Issue by giorgiootto** [mattn/go-oci8#371]
Hi,

I have a CLOB with 328.000 bytes, and in GO is string.
When a I save in database , field type CLOB, only save  63472 bytes.

Wait,

Giorgio

**Comment by MichaelS11** [comment]
Please make sure you are on the newest version of go-oci8.

`go get -u github.com/mattn/go-oci8`

**Comment by giorgiootto** [comment]
It worked.

Thanks,

**Comment by giorgiootto** [comment]
HI,
It,s ok. Worked.
Thanks,
Giorgio
    Em terça-feira, 3 de dezembro de 2019 13:44:17 BRT, MichaelS11 <notifications@github.com> escreveu:  
 
 
Please make sure you are on the newest version of go-oci8.

go get -u github.com/mattn/go-oci8
