### ISSUE TITLE
Error when cross compile, from MacOSX to linux/amd64

### ISSUE THREAD

**Issue by CaoLiSheng** [mattn/go-oci8#378]
my build script:

`env GOOS=linux GOARCH=amd64 go build -o golang-server main.go`

and got this:

```
# github.com/mattn/go-oci8
../../github.com/mattn/go-oci8/connector.go:14:10: undefined: OCI8Connector
../../github.com/mattn/go-oci8/connector.go:20:22: undefined: OCI8Connector
../../github.com/mattn/go-oci8/connector.go:21:9: undefined: OCI8Driver
../../github.com/mattn/go-oci8/connector.go:25:22: undefined: OCI8Connector
../../github.com/mattn/go-oci8/connector.go:26:15: undefined: OCI8Conn
```

I've searched almost a whole day, known this might be related to cross compiler.
But I'm not familiar with compiler, so please give a tutorial link.

Note: Not `go get github.com/mattn/go-oci8`

**Comment by MichaelS11** [comment]
Have you checked this out yet?

https://github.com/mattn/go-oci8/issues/84#issuecomment-420784283

It is for Linux to Windows but simular idea.

**Comment by MichaelS11** [comment]
@CaoLiSheng All good? Can this be closed?

**Comment by najam-awan-db** [comment]
Hello,

Normal go build runs program just fine only generating binary for linux using go build with following options gives me errors.

$CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ GOOS=linux GOARCH=amd64 go build -v -tags noPkgConfig -o myprogram.exe main.go

runtime/cgo
# runtime/cgo
gcc_linux_amd64.c: In function '_cgo_sys_thread_start':
gcc_linux_amd64.c:61:9: error: unknown type name 'sigset_t'; did you mean '_sigset_t'?
   61 |         sigset_t ign, oset;
      |         ^~~~~~~~
      |         _sigset_t
gcc_linux_amd64.c:66:9: error: implicit declaration of function 'sigfillset' [-Werror=implicit-function-declaration]
   66 |         sigfillset(&ign);
      |         ^~~~~~~~~~
gcc_linux_amd64.c:61:23: error: unused variable 'oset' [-Werror=unused-variable]
   61 |         sigset_t ign, oset;
      |                       ^~~~
cc1: all warnings being treated as errors
make: *** [build] Error 2


my go env output is:

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/awannaj/Library/Caches/go-build"
GOENV="/Users/awannaj/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/awannaj/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/awannaj/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.18/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/awannaj/Projects/golang/gooci/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7w/gr3_dpks1cb83tg6chlrbqr00000gp/T/go-build525868492=/tmp/go-build -gno-record-gcc-switches -fno-common"

go verion is go version go1.18 darwin/amd64
