### ISSUE TITLE
Compile go-oci8 failed(Not cross compile)

### ISSUE THREAD

**Issue by zhaowq32** [mattn/go-oci8#388]
**HOST:** Linux billing01 3.10.0-327.el7.ppc64 #1 SMP Thu Oct 29 17:33:57 EDT 2015 ppc64 ppc64 ppc64 GNU/Linux
```
# github.com/mattn/go-oci8
../../go/pkg/mod/github.com/mattn/go-oci8@v0.0.8/connector.go:14:10: undefined: Connector
../../go/pkg/mod/github.com/mattn/go-oci8@v0.0.8/connector.go:20:18: undefined: Connector
../../go/pkg/mod/github.com/mattn/go-oci8@v0.0.8/connector.go:21:9: undefined: Driver
../../go/pkg/mod/github.com/mattn/go-oci8@v0.0.8/connector.go:25:18: undefined: Connector
../../go/pkg/mod/github.com/mattn/go-oci8@v0.0.8/connector.go:30:11: undefined: Conn
```
```
[billing@billing01]/cbss/billing/user/zhaowq/GoLang/passmgr$ cat oci8.pc 
prefix=/cbss/pubsoftware/oracle/instantclient_11_2
prefixdir=${prefix}
exec_prefix=${prefix}
libdir=${prefix}
includedir=${prefixdir}/sdk/include

glib_genmarshal=glib-genmarshal
gobject_query=gobject-query
glib_mkenums=glib-mkenums

Name: oci8
Description: oci8 library
Libs: -L${libdir} -lclntsh
Cflags: -I${includedir}
Version: 11.2
[billing@billing01]/cbss/billing/user/zhaowq/GoLang/passmgr$ echo $LD_LIBRARY_PATH |grep instan
/cbss/pubsoftware/oracle/instantclient_11_2
[billing@billing01]/cbss/billing/user/zhaowq/GoLang/passmgr$ echo $PKG_CONFIG_PATH
/cbss/billing/user/zhaowq/GoLang/passmgr

**Comment by zhaowq32** [comment]
export CGO_ENABLED="1" solved this problem

**Comment by liqiangxuMr** [comment]
windows error:
go build github.com/mattn/go-oci8: invalid flag in pkg-config --cflags: Premium

**Comment by IT-GreenHand** [comment]
![image](https://user-images.githubusercontent.com/48703937/96695722-8ae56180-13bc-11eb-89b2-e656a1976701.png)
mac error

**Comment by liqiangxuMr** [comment]
thanks for your help!


My development environment is windows system；


oci8.pc file&nbsp; contents are as follows，test passed，thank you anyway！




# Package Information for pkg-config
prefix=C:/SoftWare/instantclient_19_5
exec_prefix=C:/SoftWare/instantclient_19_5
libdir=${exec_prefix}
includedir=${prefix}/sdk/include/


Name: OCI
Description: Oracle database engine
Version: 12.2
Libs: -L${libdir} -loci
Libs.private:&nbsp;
Cflags: -I${includedir}




 

&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "mattn/go-oci8"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 下午4:44
收件人:&nbsp;"mattn/go-oci8"<go-oci8@noreply.github.com&gt;;
抄送:&nbsp;"徐立强"<1249782650@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [mattn/go-oci8] Compile go-oci8 failed(Not cross compile) (#388)





 

 mac error
