### ISSUE TITLE
Update statement block execution

### ISSUE THREAD

**Issue by raianfs** [mattn/go-oci8#389]
Hello,
I'm doing a simple UPDATE on a table and it is getting stucked on Exec command.

I simplified the code to this, and the problem is also happening:

```
func update() {
	fmt.Println("updating")

	_, err = db.Exec("update CONNECTION set w_first_name=:1 where w_doc=:2", "test", "test")
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println("updated")
}
```

I tried with prepared statments, and transactions. If I execute the same statement on SQLPlus, it works.
Enabling LOG with oci8.Driver.Logger = log.New(os.Stdout, "oci8 ", log.Ldate|log.Ltime|log.LUTC|log.Llongfile) show nothing.

Is it a known BUG on the driver, or maybe a problem in my env? 
I can do inserts and queries without problems..

**Comment by raianfs** [comment]
My database connection is also simple:

```
oci8.Driver.Logger = log.New(os.Stdout, "oci8 ", log.Ldate|log.Ltime|log.LUTC|log.Llongfile)

	log.Println("starting database connection")
	db, err := sql.Open("oci8", fmt.Sprintf("MY_USER/MY_PASS@MY_HOST:1521/MY_SERVICE"))
	if err != nil {
		log.Fatalf("error on open db connection: %s", err)
		return
	}

	if db == nil {
		log.Fatalf("error on open db connection: %s", err)
		return
	}
```

**Comment by MichaelS11** [comment]
Does the `db.Exec` give an error? If so, what is the error? Did you make sure the table is setup correctly and there is a `w_doc` set to test?

**Comment by raianfs** [comment]
The db.Exec never returns, it got stucked in this call, so it never give the error.
The table is correct.. The same command (copy, pasted and altered just the params) works on sqlplus.
I'm testing this right now, and I saw it works some times, when I change:
`where w_doc=:2`
to `where w_doc like :2`

It would be a error on my statement, but why is it stucking?

**Comment by MichaelS11** [comment]
Try the full table name, with the schema/user.
If that doesn't work, try with context timeout set.

**Comment by raianfs** [comment]
I had already tried the timeout context. The exec is stopped and I got the timeout error from the context. However the data is not updated.

I tried now the SCHEMA.TABLE format.. and got the same problem.

**Comment by raianfs** [comment]
I guessing the problem is a transaction blocking the data on database.. I will look for that.

**Comment by MichaelS11** [comment]
Ok. If you think it is an issue with go-oci8 please provide a full example, Go code with SQL create, insert, update, etc.

**Comment by raianfs** [comment]
Its was a transaction locking my data. Tks by the support.

**Comment by MichaelS11** [comment]
Welcome, glad you got it figured out :)
