### ISSUE TITLE
No stack information

### ISSUE THREAD

**Issue by zhaoya881010** [mattn/go-oci8#390]
used import go-oci8，golang crash no stack information print.
`package main
/*
#include <stdio.h>

void sayHi() {
	char *p = NULL;
	*P = 0;
    printf("Hi");
}
*/
import "C"

import _ "github.com/mattn/go-oci8"
func main() {
	C.sayHi()
}`

run main crash,but no statck print. remove import oci8,stack print.

**Comment by MichaelS11** [comment]
Please follow the readme install steps:
https://github.com/mattn/go-oci8/blob/master/README.md

The try a simple select:
https://godoc.org/github.com/mattn/go-oci8#example-package--SqlSelect

**Comment by zhaoya881010** [comment]
@MichaelS11 i want closed “oracle Fault Diagnosability”, because it capture signal，I can't see the stack print.
the method：
To turn off the OCCI signal handler and to re-enable standard operating system failure processing, edit the sqlnet.ora file by adding the corresponding parameter: DIAG_SIGHANDLER_ENABLED=FALSE.
i can use go-oci8 set DIAG_SIGHANDLER_ENABLED=FALSE？i don‘t want retain sqlnet.ora.

**Comment by cjbj** [comment]
https://stackoverflow.com/questions/41811197/php-oci-connection-ignores-sigint-ctrl-c#comment70847750_41812370 seems to indicate it can be set as an environment variable. I forget whether I ever tried it.  Let us know what you find.

**Comment by MichaelS11** [comment]
Are we good? Can this be closed?

**Comment by zhaoya881010** [comment]
good！
