### ISSUE TITLE
Precision/Scale handling yeilding an inappropriate conversion to Float.

### ISSUE THREAD

**Issue by DrHayt** [mattn/go-oci8#392]
Having some production issues when we updated to the latest version of go-oci8.
Traced it down to different handling of statements where the precision and scale are being used to determine the go type.

In reading the documentation, the existing if/else block did not seem to match what oracle was saying.  Modified it to be a case statement.   This has all existing number cases pass.

Added new cases which DID NOT pass using old code.  Now pass with new code. #391

**Comment by MichaelS11** [comment]
Can you give some real number / SQL examples of problems you were having?

**Comment by DrHayt** [comment]
I will revise the issue and re-post with more examples.

The most pressing of which are identity columns.
