### ISSUE TITLE
Crosscompile go-apps with oracleDB on macos to windows

### ISSUE THREAD

**Issue by pmmson** [mattn/go-oci8#393]
I don't understand whats wrong..
I have: macOS (10.15.5) with install go (go1.14.3 darwin/amd64)
Oracle Instant Client (19.6.0.0.0 - Basic and SDK packages) for Windows
mingw32-w64 (from brew - brew info mingw-w64 mingw-w64: stable 7.0.0 (bottled))

build my go-apps:
GOOS=windows GOARCH=386 CGO_ENABLED=1 CC="i686-w64-mingw32-gcc" CGO_CFLAGS="-I/Applications/oracle/product/instantclient_19_6/sdk/include/" CGO_LDFLAGS="-L/Applications/oracle/product/instantclient_19_6/sdk/lib/msvc/ -loci" go build -v -tags noPkgConfig

result:

github.com/mattn/go-oci8
# github.com/mattn/go-oci8
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x002.o:c_helpers.cgo2.c:(.text+0x37): неопределённая ссылка на «OCIDescriptorFree»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x62): неопределённая ссылка на «OCIAttrGet»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0xd8): неопределённая ссылка на «OCIAttrSet»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x123): неопределённая ссылка на «OCIBreak»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x20b): неопределённая ссылка на «OCIDateTimeConstruct»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x281): неопределённая ссылка на «OCIDateTimeGetDate»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x309): неопределённая ссылка на «OCIDateTimeGetTime»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x374): неопределённая ссылка на «OCIDateTimeGetTimeZoneOffset»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x3de): неопределённая ссылка на «OCIDescriptorAlloc»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x465): неопределённая ссылка на «OCIErrorGet»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x4d0): неопределённая ссылка на «OCIHandleAlloc»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x51a): неопределённая ссылка на «OCIHandleFree»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x574): неопределённая ссылка на «OCILobCharSetForm»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x618): неопределённая ссылка на «OCILobCreateTemporary»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x729): неопределённая ссылка на «OCILobRead2»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x83d): неопределённая ссылка на «OCILobWrite2»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x88b): неопределённая ссылка на «OCILogoff»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x8da): неопределённая ссылка на «OCIPing»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x929): неопределённая ссылка на «OCIServerDetach»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0x983): неопределённая ссылка на «OCISessionEnd»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0xa27): неопределённая ссылка на «OCIStmtPrepare2»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x003.o:connection.cgo2.c:(.text+0xa87): неопределённая ссылка на «OCITransStart»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x004.o:globals.cgo2.c:(.text+0x84): неопределённая ссылка на «OCIEnvCreate»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x004.o:globals.cgo2.c:(.text+0xcf): неопределённая ссылка на «OCINlsCharSetNameToId»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x005.o:oci8.cgo2.c:(.text+0xaa): неопределённая ссылка на «OCIEnvNlsCreate»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x005.o:oci8.cgo2.c:(.text+0x150): неопределённая ссылка на «OCILogon»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x005.o:oci8.cgo2.c:(.text+0x1bb): неопределённая ссылка на «OCIServerAttach»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x005.o:oci8.cgo2.c:(.text+0x225): неопределённая ссылка на «OCISessionBegin»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x005.o:oci8.cgo2.c:(.text+0x279): неопределённая ссылка на «OCITransCommit»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x005.o:oci8.cgo2.c:(.text+0x2c8): неопределённая ссылка на «OCITransRollback»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x006.o:rows.cgo2.c:(.text+0x82): неопределённая ссылка на «OCIIntervalGetDaySecond»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x006.o:rows.cgo2.c:(.text+0xed): неопределённая ссылка на «OCIIntervalGetYearMonth»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x006.o:rows.cgo2.c:(.text+0x166): неопределённая ссылка на «OCIStmtFetch2»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x007.o:statement.cgo2.c:(.text+0xe6): неопределённая ссылка на «OCIBindByName»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x007.o:statement.cgo2.c:(.text+0x1d0): неопределённая ссылка на «OCIBindByPos»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x007.o:statement.cgo2.c:(.text+0x29a): неопределённая ссылка на «OCIDefineByPos»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x007.o:statement.cgo2.c:(.text+0x305): неопределённая ссылка на «OCIParamGet»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x007.o:statement.cgo2.c:(.text+0x364): неопределённая ссылка на «OCIRowidToChar»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x007.o:statement.cgo2.c:(.text+0x3f8): неопределённая ссылка на «OCIStmtExecute»
/usr/local/Cellar/mingw-w64/7.0.0_2/toolchain-i686/bin/i686-w64-mingw32-ld: $WORK/b038/_x007.o:statement.cgo2.c:(.text+0x463): неопределённая ссылка на «OCIStmtRelease»
collect2: ошибка: выполнение ld завершилось с кодом возврата 1

**Comment by MichaelS11** [comment]
Should your GOARCH be set to amd64?

**Comment by pmmson** [comment]
No! So it's working settings

GOOS=windows CGO_ENABLED=1 CC="x86_64-w64-mingw32-gcc" CGO_CFLAGS="-I/Applications/oracle/product/instantclient_19_6/sdk/include/" CGO_LDFLAGS="-L/Applications/oracle/product/instantclient_19_6/sdk/lib/msvc/ -loci" go build -v -tags noPkgConfig

I successfully built the application and ran it on the target OS
Thank you!

**Comment by MichaelS11** [comment]
Great, glad you got it working. Please close this issue if all done.
