### ISSUE TITLE
About error in multiple using of named parameters on SQL

### ISSUE THREAD

**Issue by foolmacky** [mattn/go-oci8#394]
Hello,

I think Oracle allows for using multiple SQL placeholders in same name.
For example,
```
INSERT into test_table values ('Name', 99, :HOGE, :HOGE);
```
In this case, number of variable is 2, but number of named parameters is 1.
But OCI interface function cannot get number of distinct place holders.

In go-oci8, before 2019.5, driver relly on Database engine for checking number of SQL parameters,
but now version, driver check parameters by function "OCIAttrGet".
Then multiple using of named parameters occours error in database/sql.
```
params := []sql.NamedArg{
    {Name: "HOGE", Value: "Oracle"},
}
     :(some process)
res, err := tx.ExecContext(
    ctx,
    "INSERT into test_table values ('Name', 99, :HOGE, :HOGE)",
    args...)

//ERROR
2020/06/18 18:15:24 sql: expected 2 arguments, got 1
```
```
params := []sql.NamedArg{
    {Name: "HOGE", Value: "Oracle"},
    {Name: "HOGE", Value: "Oracle"},
}
     :(some process)
res, err := tx.ExecContext(
    ctx,
    "INSERT into test_table values ('Name', 99, :HOGE, :HOGE)",
    args...)
//That's OK
```
This is very simple case to deal.
But in complex long SQL, we have to define many args.
```
params := []sql.NamedArg{
    {Name: "EXEC_DATE", Value: "20200620"},
    {Name: "EXEC_DATE", Value: "20200620"},
    {Name: "EXEC_DATE", Value: "20200620"},
    {Name: "UPDATE_ID", Value: "Oracle"},
    {Name: "UPDATE_ID", Value: "Oracle"},
}
```
or
```
params := []sql.NamedArg{
    {Name: "EXEC_DATE1", Value: "20200620"},
    {Name: "EXEC_DATE2", Value: "20200620"},
    {Name: "EXEC_DATE3", Value: "20200620"},
    {Name: "UPDATE_ID1", Value: "Oracle"},
    {Name: "UPDATE_ID2", Value: "Oracle"},
}
```
Is it better way to leave checking number of SQL parameter to Oracle engine ?
Or that is an error in my understanding ?

Please tell me what you think.

**Comment by MichaelS11** [comment]
Sure, we could leave the checking to the Oracle driver/database. It would be an easy change, just update NumInput to always return -1 per Stmt specs. https://golang.org/pkg/database/sql/driver/#Stmt

The question is should we? I am fine with that change.

Anyone else have any thoughts?

Will give it a week or so to see if anyone else has any other thoughts.

**Comment by foolmacky** [comment]
Thank you for your responce.
I really appreciate for all effort to go-oci8 developpment.

**Comment by MichaelS11** [comment]
https://github.com/mattn/go-oci8/pull/395

**Comment by MichaelS11** [comment]
Please test

**Comment by foolmacky** [comment]
Thank you !
I have tested and confirmed that it works just as expected.

**Comment by MichaelS11** [comment]
Wonderful! :) Glad to hear it.

If all done, could you close this issue?

**Comment by foolmacky** [comment]
All right.
