### ISSUE TITLE
os.Setenv("NLS_LANG", "SIMPLIFIED CHINESE_CHINA.AL32UTF8") is unavailable 

### ISSUE THREAD

**Issue by Xjunjun** [mattn/go-oci8#396]
import (
	"database/sql"
	"fmt"
	"os"

	_ "github.com/mattn/go-oci8"
)

func main() {
	os.Setenv("NLS_LANG", "SIMPLIFIED CHINESE_CHINA.AL32UTF8")
	os.Setenv("NLS_NCHAR", "SIMPLIFIED CHINESE_CHINA.AL32UTF8")

	db, err := sql.Open("oci8", "test/test@testdb")

	stmt, err := db.Prepare(`select china_word  from tbl_test WHERE id = 1`)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer stmt.Close()
	rows := stmt.QueryRow()
	var test string
	err = rows.Scan(&test)
	if err != nil {
		fmt.Println(err)
		return
	}
        fmt.Printf("NLS_LANG[%s]NLS_NCHAR[%s]\n", os.Getenv("NLS_LANG"), os.Getenv("NLS_NCHAR"))
	fmt.Println(test)

}

output :
go run main.go
NLS_LANG[SIMPLIFIED CHINESE_CHINA.AL32UTF8]NLS_NCHAR[SIMPLIFIED CHINESE_CHINA.AL32UTF8]
������

But If I   export NLS_LANG='SIMPLIFIED CHINESE_CHINA.AL32UTF8' then in the terminal I execute 'go run main.go',I can get true word "中文词". So I think Setenv("NLS_LANG", "SIMPLIFIED CHINESE_CHINA.AL32UTF8")  is unavailable in the code.
PS:
oracle server is "American_America.ZHS16GBK"

**Comment by MichaelS11** [comment]
There is very little the go-oci8 code does with NLS_LANG. The underlying Oracle C++ OCI driver is really what makes use of that.

How about trying SIMPLIFIED CHINESE_CHINA.ZHS16GBK, does that work?

**Comment by Xjunjun** [comment]
I think I can change NLS_LANG through SetEnv xxxxx   in the program before  "sql.Open", but I find I can't do it.
If I set the environment  “export NLS_LANG='SIMPLIFIED CHINESE_CHINA.AL32UTF8'“  then I run my program  is ok.
It was a petty problem and I cat set environment  in the system replace instead of  os.Setenv to solve the question.
