### ISSUE TITLE
Can this driver support Stored Procedure？

### ISSUE THREAD

**Issue by loraxh** [mattn/go-oci8#397]
I tried several times, une excute method to execute a stored procedure with in parameters can success, but when there's a out/inout parameters will error: data type Error translation

**Comment by MichaelS11** [comment]
Yes, use sql.Out, like in the example below.

https://godoc.org/github.com/mattn/go-oci8#example-package--SqlFunction

**Comment by MichaelS11** [comment]
@loraxh All good? If so, please close this issue.

**Comment by loraxh** [comment]
thank you!
