### ISSUE TITLE
Error $GOPATH/src/github.com/mattn/go-oci8/oci8.go:116:25: could not determine kind of name for C.OCI_SYSASM

### ISSUE THREAD

**Issue by aagrrla** [mattn/go-oci8#398]
I commented out $GOPATH/src/github.com/mattn/go-oci8/oci8.go:116 and 117
Then I got following error.
$GOPATH/src/github.com/mattn/go-oci8/connection.go:24:21: too many arguments in call to _Cfunc_OCIPing
	have (*_Ctype_struct_OCISvcCtx, *_Ctype_struct_OCIError, number)
	want (*_Ctype_struct_OCISvcCtx, *_Ctype_struct_OCIError)

Next I removed , C.OCI_DEFAULT (3rd parameter) at connection.go:24.

Now everything is working for oracle_instant_client_19_6.

I just wanted to note it down if that may be helpful. 

Thanks.

**Comment by MichaelS11** [comment]
Oracle documentation is not showing any changes to OCIPing. Not sure why you got that error.

https://docs.oracle.com/database/121/LNOCI/oci17msc007.htm#LNOCI17291

https://docs.oracle.com/en/database/oracle/oracle-database/19/lnoci/miscellaneous-functions.html#GUID-033BF96D-D88D-4F18-909A-3AB7C2F6C70F

**Comment by MichaelS11** [comment]
Anyone else get this error? If not, seems like this can be closed.
