### ISSUE TITLE
Go build error.

### ISSUE THREAD

**Issue by psoKnight** [mattn/go-oci8#399]
Dear:
          The project can run normally, but when me go build reports an error, like this：

D:\GOPATH\src\yisa\trasffer_same_household _registration>go build -o trasffer_same_household_registration
# github.com/mattn/go-oci8
..\..\..\pkg\mod\github.com\mattn\go-oci8@v0.0.8\connector.go:14:10: undefined: Connector
..\..\..\pkg\mod\github.com\mattn\go-oci8@v0.0.8\connector.go:20:18: undefined: Connector
..\..\..\pkg\mod\github.com\mattn\go-oci8@v0.0.8\connector.go:21:9: undefined: Driver
..\..\..\pkg\mod\github.com\mattn\go-oci8@v0.0.8\connector.go:25:18: undefined: Connector
..\..\..\pkg\mod\github.com\mattn\go-oci8@v0.0.8\connector.go:30:11: undefined: Conn

D:\GOPATH\src\yisa\trasffer_same_household _registration>

**Comment by MichaelS11** [comment]
Would check the readme and other issues. Probably something to do with the setup needs to be changed.

**Comment by MichaelS11** [comment]
All good? Could you close this?
