### ISSUE TITLE
Golang 1.14 unreliably supported

### ISSUE THREAD

**Issue by calvinmo** [mattn/go-oci8#408]
When making use of this library in a golang 1.14 application the application as a whole intermittently starts up.  Once the import for this library is removed the same application starts up just fine.

Worth giving consideration for golang 1.15 as well I think.

**Comment by MichaelS11** [comment]
Do you have a PR that would fix this?

**Comment by calvinmo** [comment]
I must admit I have not attempted to make one. I notice you have got tests targeting each golang version 1.9 - 1.13 (https://github.com/mattn/go-oci8/blob/master/test.sh) and I thought I would first find out if there was already a failed attempt due to a known issue that wasn't obvious to me.

**Comment by lggomez** [comment]
On the same line I'd like to ask: which is the latest compatible version of the oracle instant client?
I'm trying to compile a project with instant client v19.6 and I get the following error:

```
main #gosetup
# runtime/cgo
clang: error: /opt/oracle/instantclient_19_8: 'linker' input unused [-Werror,-Wunused-command-line-argument]

Compilation finished with exit code 2
```

**Comment by calvinmo** [comment]
Sorry I am not sure why I didn't see this comment come through...

For me the latest version of golang that works reliably with this library is 1.13.  Given that this library is written with golang 1.13 either its a big coincidence or it might just be a matter of changing the golang version (and adding a test here: https://github.com/mattn/go-oci8/blob/master/test.sh) and done and dusted.

If there is no better plan than this I will give it a shot soon enough...

**Comment by lggomez** [comment]
@calvinmo I found some time to take care of that and as #409's pipeline passed now we can assert that the package works with the latest versions of 1.14 and 1.15 (at least with the test coverage provided here)

Logs can be seen here: https://travis-ci.org/github/mattn/go-oci8/builds/750614710

I guess that leaves two questions open (agreeing with @MichaelS11 label here):
- Whether there are platform any platform specific issues and fill them separately with mode detail (MacOS has it nasty share of issues, I don't know how well CGo fares there but that's my work environment and I was unable to install this package seamlessly)
- Whether newer versions of oracle include a compatible libocci.so

This can be tested via some juggling with docker images (oracle provides a generator on https://github.com/oracle/docker-images/tree/master/OracleDatabase). If I have the time to run the tests myself I will check in here

**Comment by MichaelS11** [comment]
@calvinmo There does not seem to be an issue with Golang 1.14. Can you please close this issue?

**Comment by calvinmo** [comment]
OK it seems I incorrectly diagnosed this issue then. My apologies. Back to the drawing board for me...
