### ISSUE TITLE
Memory leak in transaction handles

### ISSUE THREAD

**Issue by lucio-santi** [mattn/go-oci8#411]
Hi all,

It seems that transaction handles are being allocated upon starting new transactions without proper deallocations of previous handles, which leads to memory leaks. We found significant memory issues in one of our apps with high traffic loads and we think it may be due to this.

**Comment by MichaelS11** [comment]
Talking about it on the PR you did:
https://github.com/mattn/go-oci8/pull/410
Probably can close this so we are talking about it in one place.

**Comment by MichaelS11** [comment]
@lucio-santi All good? Can you close this issue?

**Comment by lucio-santi** [comment]
Done! Sorry for keeping it open. Hope you are fine!
