### ISSUE TITLE
./oci8.go.h:1:10: fatal error: 'oci.h' file not found

### ISSUE THREAD

**Issue by VinnyR1am** [mattn/go-oci8#413]
I get this error after trying to start a debug session in VSCode on my Mac and when i try "go get github.com/mattn/go-oci8".  I followed all the steps in the install instructions and still get this error. Not sure how to fix this. I even tried what is suggested in  [Issue #168 ](https://github.com/mattn/go-oci8/issues/168 ) but to no use. Any help is appreciated.

**Comment by MichaelS11** [comment]
Does it work normally outside of a debug session?

**Comment by MichaelS11** [comment]
If you have figured out a solution please close this issue.

**Comment by VinnyR1am** [comment]
> Does it work normally outside of a debug session?

It does not. Here is the details of my issue

When i do 
`go get github.com/mattn/go-oci8`

I get the following error

`# github.com/mattn/go-oci8
In file included from ../../../../go/pkg/mod/github.com/mattn/go-oci8@v0.1.1/c_helpers.go:3:
./oci8.go.h:1:10: fatal error: 'oci.h' file not found
#include <oci.h>`

And my go env is 
`
GOPATH="/Users/myusername/go"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z1/8ksy3gtx1xs98gg8w1yzpv7c0000gn/T/go-build3233366812=/tmp/go-build -gno-record-gcc-switches -fno-common"
`

$pkg-config --cflags --libs oci8

`-I/usr/local/Cellar/instantclient-sdk/19.3.0.0.0dbru/include -L/usr/local/Cellar/instantclient-basic/19.3.0.0.0dbru/lib -lclntsh`

**Comment by MichaelS11** [comment]
Would go threw the readme steps again. Also check another issues posted.

**Comment by MichaelS11** [comment]
How did that work out?
