### ISSUE TITLE
Using context timeout when DB unavailable?

### ISSUE THREAD

**Issue by cheshirex** [mattn/go-oci8#417]
I'm trying to handle a case where a DB I'm using becomes unavailable in the middle of processing. I'm trying to do this by added a context with a timeout to the QueryContext call.

In order to simulate the DB being unavailable, I'm adding a firewall rule in the middle of my run to block the DB server. What I find is that the call does not seem to respect the context timeout, does not seem to respect the TRANSPORT_CONNECT_TIMEOUT I set in the tnsnames.ora file, and instead takes a much longer time to return with a "ORA-12152: TNS:unable to send break message" error.

Any insight would be appreciated. Thanks!

**Comment by MichaelS11** [comment]
How much longer? There are two timers in work here. First there is the context timeout. After that, `ociBreak()` is called:

https://github.com/mattn/go-oci8/blob/5982e16ac11f4252659e5b98bcede0fddd3230e2/connection.go#L596

The timeout for `ociBreak()` might be controlled by sqlnet.ora settings. Maybe SQLNET.OUTBOUND_CONNECT_TIMEOUT
https://docs.oracle.com/cd/E11882_01/network.112/e10835/sqlnet.htm#NETRF427

I think that tnsnames.ora will only affect the database startup connection timeout.

**Comment by cheshirex** [comment]
From the application log, it takes 1048 seconds before the Oracle client returns the error.

I looked up the SQLNET.OUTBOUND_CONNECT_TIMEOUT parameter, saw that it is overridden by CONNECT_TIMEOUT in the tnsnames.ora file, tried that, and again, no effect. But from the description of all of these parameters, it sounds like it may only affect startup connection. I'm digging around to see if there are other configuration parameters to work with.

**Comment by cjbj** [comment]
Setting [`EXPIRE_TIME`](https://www.oracle.com/pls/topic/lookup?ctx=dblatest&id=GUID-6140611A-83FC-4C9C-B31F-A41FC2A5B12D) can help to detect 'dead servers', see https://stackoverflow.com/questions/66910012/get-access-to-sqlalchemy-connection-socket-to-prevent-firewall-timeouts/66913142#66913142 for usage.

**Comment by MichaelS11** [comment]
All good now? Can you close this?

**Comment by cheshirex** [comment]
I managed to get it to somewhat reasonable times by adding SQLNET.RECV_TIMEOUT -- nothing else seemed to have an effect. At any rate, that's solved what I needed to do. Thanks for the help!
