### ISSUE TITLE
Context cancelation not being honored

### ISSUE THREAD

**Issue by calvn** [mattn/go-oci8#419]
`PingContext` does not seem to honor context cancellation. I've mainly tested with `PingContext` and `BeginTx`, but this issue may be present in other methods as well, and I suspect that it might have to do with how `OCIBreak` works. However, I am not knowledgeable/familiar enough with Oracle to dig into its C library to further triage the issue. 

### Sample repro program:
```go
package main

import (
	"context"
	"database/sql"
	"log"
	"time"

	_ "github.com/mattn/go-oci8"
)

func main() {
	log.Println("Calling sql.Open")
	db, err := sql.Open("oci8", "vaultadmin/myreallysecurepassword@localhost:1521/ORCLPDB1")
	if err != nil {
		log.Fatalf("error opening connection: %s", err)
	}
	defer db.Close()
	log.Println("Finished sql.Open")

	timeout := 10 * time.Second
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	done := make(chan struct{})
	go func() {
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()
		for {
			select {
			case <-ticker.C:
				log.Println("Still processing...")
			case <-done:
				return
			case <-ctx.Done():
				// Context cancellation should print the error, cancel the
				// PingContext call, and exit shortly after. However, the
				// program hangs for a period that is long past our timeout of
				// 10s before exiting.
				log.Println(ctx.Err())
				return
			}
		}

	}()

	log.Println("Calling PingContext")
	err = db.PingContext(ctx)
	if err != nil {
		log.Fatalf("error on ping: %s", err)
	}
	close(done)
	log.Println("Finished PingContext")
}
```

### Output
Run where database is accessible:
```
› go run main.go
2021/04/28 16:46:32 Calling sql.Open
2021/04/28 16:46:32 Finished sql.Open
2021/04/28 16:46:32 Calling PingContext
2021/04/28 16:46:33 Finished PingContext
```

Run where database is inaccessible:
```
› go run main.go
2021/04/28 16:48:01 Calling sql.Open
2021/04/28 16:48:01 Finished sql.Open
2021/04/28 16:48:01 Calling PingContext
2021/04/28 16:48:02 Still processing...
2021/04/28 16:48:03 Still processing...
2021/04/28 16:48:04 Still processing...
2021/04/28 16:48:05 Still processing...
2021/04/28 16:48:06 Still processing...
2021/04/28 16:48:07 Still processing...
2021/04/28 16:48:08 Still processing...
2021/04/28 16:48:09 Still processing...
2021/04/28 16:48:10 Still processing...
2021/04/28 16:48:11 context deadline exceeded
^Csignal: interrupt
```

**Comment by cjbj** [comment]
My go-to headache tablet with this kind of problem is to see if adding `disable_oob=on` to the sqlnet.ora (on the machine where you run Go) helps.  (Note if you are using 19c DB and 19c Oracle client libraries, then this line is not needed.)

**Comment by MichaelS11** [comment]
If you remove the `case <-ctx.Done():` how long does it go for?

There are other database timeouts that the OCI calls have to deal with so it will not return quickly. This question might help give a little insight:
https://github.com/mattn/go-oci8/issues/417

**Comment by calvn** [comment]
@MichaelS11 I have it running for 10+ minutes and it's still not terminated.

**Comment by calvn** [comment]
I'm compiling on MacOS using `instantclient_19_8` if that helps.

**Comment by calvn** [comment]
I was able to get the application to terminate early by specifying `SQLNET.OUTBOUND_CONNECT_TIMEOUT=15` in a `sqlnet.ora` file and setting the `TNS_ADMIN` environment variable. However, it would be ideal if context cancelation would terminate the process/drop the connection immediately without waiting for the full duration on the specified timeout value.

```
› go run main.go
2021/05/03 14:00:46 Calling sql.Open
2021/05/03 14:00:46 Finished sql.Open
2021/05/03 14:00:46 Calling PingContext
2021/05/03 14:00:47 Still processing...
2021/05/03 14:00:48 Still processing...
2021/05/03 14:00:49 Still processing...
2021/05/03 14:00:50 Still processing...
2021/05/03 14:00:51 Still processing...
2021/05/03 14:00:52 Still processing...
2021/05/03 14:00:53 Still processing...
2021/05/03 14:00:54 Still processing...
2021/05/03 14:00:55 Still processing...
2021/05/03 14:00:56 context deadline exceeded
2021/05/03 14:01:01 error on ping: ORA-12170: TNS:Connect timeout occurred
```

**Comment by MichaelS11** [comment]
Glad you got it to work.

Yeah, that would be nice. Welcome a PR if you know of a good way to do it.
