### ISSUE TITLE
Commits since nov 11,  does not work in Windows 7 with 32 bits

### ISSUE THREAD

**Issue by paparipote** [mattn/go-oci8#42]
Hello, your last package compiles well, generates the .a file and my program that imports your packate compiles well also, but when executing, it hangs and produces the increment of CPU and I/O.
The connection to Database seems working well:
	db, err := sql.Open("oci8", connection)
But it hangs when invoking to:
        err = db.Ping()
I recovered one of the commits previous to november 11 and all is working as usual (very well), so it seems that the changes made to your code in nov 11 are the origin of the described problem.
Best regards.

**Comment by mattn** [comment]
Should be fixed
