### ISSUE TITLE
is there any fast bulk insert solutions like executemany() in python/node ?

### ISSUE THREAD

**Issue by nvl0** [mattn/go-oci8#425]
I'm using golang with go-oci8. The problem is in bulk insert. Now i have 15k records to insert, but in future the number will grow. PrepareNamed function inserts 15k records in 15s roughly (i removed transport time). But that is the way slower than Python with cx_Oracle. Python for example managed with 15k records in 0.5s. Things i should mention: tests and db tables were identical.

**Comment by wenzi1** [comment]
Try the insert all into statement and start multitasking. It should be faster
