### ISSUE TITLE
If the password have # character, will get error when access to the db

### ISSUE THREAD

**Issue by ocealin** [mattn/go-oci8#48]
db, err := sql.Open("oci8", "test:dd#test@testdb")

C:\go\src\github.com\wendal\go-oci8\example>go run oracle.go
2015/02/09 10:50:17 oracle.go:14: Oracle Driver example
2015/02/09 10:50:17 oracle.go:25: Invalid DSN: strconv.ParseInt: parsing "se": i
nvalid syntax
exit status 1

**Comment by ocealin** [comment]
just found the solution, the issue is because the new oci8's ParseDSN function is using the url.Parse to parse the dns, so for some special characters have to use url encode format.

**Comment by mattn** [comment]
Yes, right. I'll fix in few days.

**Comment by mattn** [comment]
Should be fixed.
