### ISSUE TITLE
Use port 1521 as default

### ISSUE THREAD

**Issue by ricsmania** [mattn/go-oci8#49]
It would be nice if I could pass a DSN as machine/instance instead of machine:1521/instance.

It seems to bem that these lines try to do this, however when SplitHostPort returns an error the host is not set, so it doesn't work. https://github.com/mattn/go-oci8/blob/3e4e9fb57dfd52e107865af8d7774feedd97fbd4/oci8.go#L389-L395

I tried setting the host inside the if block, but that caused the TNS names lookup to stop working.

**Comment by mattn** [comment]
Ah, the part you pointed should be `!=` not `==`

**Comment by ricsmania** [comment]
Hi!

This doesn't seem to work, I tried passing my connect as user/password@machine/instance and got a ORA-12541. It only works when I explicitly pass port 1521.

Thanks!
