### ISSUE TITLE
ORA-12560: TNS:protocol adapter error

### ISSUE THREAD

**Issue by michaelkrnac** [mattn/go-oci8#52]
I try to connect to my database with like:
````
	db, err := sql.Open("oci8", "user:password@server:port")
	if err != nil {
		fmt.Println(err)
		return
	}
````

but get the error
ORA-12560: TNS:protocol adapter error

**Comment by mattn** [comment]
I couldn't reproduce it. Do you try on latest?

**Comment by michaelkrnac** [comment]
Works, was my fault.
