### ISSUE TITLE
how to use boolean value in oracle?

### ISSUE THREAD

**Issue by magicwang-cn** [mattn/go-oci8#59]
i found that the boolean value in go-oci8.go just use SQLT_INT 0/1, and i create table just like this:
CREATE TABLE BUSADMIN.EVENT ( 
    ID                      NUMBER(9,0) NOT NULL,
    EVENT_TYPE              NUMBER(18,0) NOT NULL,
    CLEARED_TYPE            VARCHAR2(255) NOT NULL,
    EVENT_ID                NUMBER(18,0) NOT NULL,
    EVENT_NAME              VARCHAR2(255) NOT NULL,
    PERCEIVED_SEVERITY      VARCHAR2(255) NOT NULL,
    DETAILED_INFORMATION    VARCHAR2(255) NOT NULL,
    PROPOSED_REPAIR_ACTIONS VARCHAR2(255) NOT NULL,
    CREATEDAT               VARCHAR2(255) NOT NULL,
    UPDATEDAT               VARCHAR2(255) NOT NULL,
    B_IS_SYSTEM_DEFINE      NUMBER(1,0) NOT NULL,
    PRIMARY KEY(ID)
    NOT DEFERRABLE
     VALIDATE
)
the B_IS_SYSTEM_DEFINE  is a boolean value, but when i insert or delete value from the table, the process always dump, anyone can help me?

**Comment by mattn** [comment]
could you please show me your code?

**Comment by DunesUnLimited** [comment]
Typically a boolean is stored as Y/N in a char(1) column, as that is human readable when querying the table.

**Comment by MichaelS11** [comment]
So the oci8 code does a Go boolean as 0/1. But Oracle does not have a boolean type.

@mattn Close this?

**Comment by mattn** [comment]
If you still have an opinion or issue, please reopen this.
