### ISSUE TITLE
Travis-CI Testing

### ISSUE THREAD

**Issue by jonlawlor** [mattn/go-oci8#60]
I've managed to cobble together a working test environment on travis-ci for go-oci8.  It appears that you typically add travis-ci to your go projects; I imagine that the reason it is not included in this one is because it is very irritating to do.  I hope it helps.  If you are interested I can submit a pull request.

You should be able to see the changes at my fork at https://github.com/jonlawlor/go-oci8 & an example build at https://travis-ci.org/jonlawlor/go-oci8/builds/63115619

It seems to fail on TestFooRowid currently, but all other tests pass.  There were some inconsistent results when using go 1.3 as well.  It takes a long time to run, because every build has to download Oracle XE and the instant client.

**Comment by mattn** [comment]
Cool! Could you please send me your PR?

**Comment by MichaelS11** [comment]
@mattn Close this?

**Comment by mattn** [comment]
Now we are using docker.
