### ISSUE TITLE
RowsAffected returns 0 after success insert

### ISSUE THREAD

**Issue by mynoheart** [mattn/go-oci8#63]
This behavior apperaed after commit a6eb4a39ec2a4209e1586ddb760c3c74a21848a4

**Comment by zihuxinyu** [comment]
I have the same problem

**Comment by MichaelS11** [comment]
Close this?

**Comment by MichaelS11** [comment]
Is this still an issue?

**Comment by MichaelS11** [comment]
@mattn Close this?

**Comment by mattn** [comment]
This should be fixed. Please reopen you still have issue and it is related on go-oci8.
