### ISSUE TITLE
ORA-12545: Connect failed because target host or object does not exist

### ISSUE THREAD

**Issue by novalagung** [mattn/go-oci8#65]
I'm trying to use **go-oci8** on my project. I use OSX. I already prepare the oracle *instantclient* and everything, and I can finally use it using sqlplus.

This is my `tnsnames.ora`

```
210=(DESCRIPTION=
        (ADDRESS_LIST=
            (ADDRESS=
                (PROTOCOL=TCP)
                (HOST=192.168.0.210)
                (PORT=1521)
            )
        )
        (CONNECT_DATA=
            (SID=ORCL)
            (SERVER=DEDICATED)
            (SERVICE_NAME=orcl.my.local)
        )
    )
```

This is the env.

```bash
export ORACLE_HOME=/Applications/oracle/instantclient_11_2
export PKG_CONFIG_PATH=$ORACLE_HOME/pkg
export GO_OCI8_CONNECT_STRING="(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.0.210)(PORT=1521)))(CONNECT_DATA=(SID=ORCL)(SERVER=DEDICATED)(SERVICE_NAME=orcl.my.local)))"
export ORACLE_SID="ORCL"
export DYLD_LIBRARY_PATH=$ORACLE_HOME:$DYLD_LIBRARY_PATH
export PATH=$PATH:$ORACLE_HOME
```

##### It's working if I use **sqlplus**, `sqlplus scott/tiger@210`.

![Connect using sqlplus](http://oi59.tinypic.com/k3ptsm.jpg)

---

##### The problem is I cannot connect to the oracle server using go-oci8 example.

I have put `oci8.pc` file inside `$PKG_CONFIG_PATH` and below is the content of the file.

```bash
orainc=/Applications/oracle/instantclient_11_2/sdk/include
oralib=/Applications/oracle/instantclient_11_2

Name: oci8
Description: Oracle Instant Client
Version: 12.1
Cflags: -I${orainc}
Libs: -L${oralib} -lclntsh
```

Everytime I run it, this error always showing up.
```bash
ORA-12545: Connect failed because target host or object does not exist
```

![Can't connect to oracle server from golang](http://oi58.tinypic.com/2w2etso.jpg)

Could you help me solving this problem? Or am I missing something. Thank you in advance.

**Comment by mattn** [comment]
Could you please show me your `oracle.go`?

**Comment by novalagung** [comment]
oracle.go is sample of the project. here is the link https://github.com/mattn/go-oci8/blob/master/_example/oracle.go <https://github.com/mattn/go-oci8/blob/master/_example/oracle.go>.

**Comment by mattn** [comment]
Try with

```
export GO_OCI8_CONNECT_STRING="youruser/yourpass@210"
```

**Comment by novalagung** [comment]
It's working now. Thanks!
