### ISSUE TITLE
How to insert a string into the oracle clob field?

### ISSUE THREAD

**Issue by xpbliss** [mattn/go-oci8#66]
how to use the oci8 to read or write a string into the clob field?

**Comment by mattn** [comment]
like this.

https://github.com/mattn/go-oci8/blob/master/oci8.go

**Comment by xpbliss** [comment]
if the clob is stored a string, is not the byte[], how to read and store?

**Comment by mattn** [comment]
see https://github.com/mattn/go-oci8/blob/master/_example/blob.go#L45-L46

**Comment by xpbliss** [comment]
I want store a string into the oracle clob fields,  in the oracle clob, it should be a string, not  the bytes.   how to do ?

**Comment by mattn** [comment]
Ah, sorry. go-oci8 already return string from clob.

https://github.com/mattn/go-oci8/blob/master/oci8.go#L1268
