### ISSUE TITLE
Maybe a serious issue:RowsAffected returns 0 after success insert or update or delete!

### ISSUE THREAD

**Issue by xpbliss** [mattn/go-oci8#67]
package main
import (
    "database/sql"
     "fmt" 
     "os"
    _ "github.com/mattn/go-oci8"
)

var connStr string = "cms/cmsadmin@ORCL"

func main() {
 os.Setenv("NLS_LANG", "AMERICAN_AMERICA.AL32UTF8")  
    db, err := sql.Open("oci8", connStr)
    if err != nil {
        panic(err)
    }
    defer db.Close()
     SQL := `INSERT INTO CMS."dxh"(CMS."dxh"."id", CMS."dxh"."content") VALUES ('dxh','my test data my test data')`
     res,_:=db.Exec(SQL)
    aa,e:=res.RowsAffected()  
    fmt.Println(aa,e) 	  //aa is always 0, whatever insert or update or delete
}

**Comment by xpbliss** [comment]
It's still!  why not fix it?

**Comment by mattn** [comment]
I don't have much time to do. RowsAffected/LastInsertId is changed in https://github.com/mattn/go-oci8/commit/a6eb4a39ec2a4209e1586ddb760c3c74a21848a4

because it was crashed.

**Comment by mattn** [comment]
oracle doesn't support to get last inserted rowid.

**Comment by xpbliss** [comment]
https://community.oracle.com/thread/334501

**Comment by mattn** [comment]
what do you mean? i can't understand the link.

**Comment by xpbliss** [comment]
the change " RowsAffected / LastInsertId "  in a6eb4a3 is still a issue. 
"aa,e:=res.RowsAffected()", the aa is 0 ,and the e is still  not nil.

**Comment by mattn** [comment]
okay, I'll fix RowsAffected. And return error from LastInsertId.

**Comment by xpbliss** [comment]
good!  all seems ok!
