### ISSUE TITLE
can not get float column from oracle 

### ISSUE THREAD

**Issue by huyg** [mattn/go-oci8#68]
I can not get float column from table such as "select price from items".
no errors, but codes will not traverse rows.
if change to "select ceil(price) from items" , it will works well. 

the column is "NUMBER(0,0)"

**Comment by mattn** [comment]
what is your code?

**Comment by huyg** [comment]
codes:


	package main

	import (
		"database/sql"
		"fmt"
		"log"
		"os"
		_ "github.com/mattn/go-oci8"
	)

	func main() {

		log.SetFlags(log.Lshortfile | log.LstdFlags)
		os.Setenv("NLS_LANG", "SIMPLIFIED CHINESE_CHINA.UTF8")

		db, err := sql.Open("oci8", "user/passwd@node:1521/testdb")
		if err != nil {
			log.Fatal(err)
		}
		defer db.Close()

		qs := `
	SELECT
		user_name,
		sum(run_time )
	FROM
		JOB_ACCOUNTING
	WHERE
		USER_NAME='huyg2'
	GROUP BY
		user_name
	`

		rows, err := db.Query(qs)

		if err != nil {
			fmt.Println(err)
			os.Exit(1)
		}
		defer rows.Close()
		for rows.Next() {
			var name string
			var data float32
			rows.Scan(&name, &data)

			fmt.Println(name, data)

		}
	}
	···





**output:**
blank

if change **qs** to 

	qs := `
	SELECT
		user_name,
		ceil(sum(run_time ))
	FROM
		JOB_ACCOUNTING
	WHERE
		USER_NAME='huyg2'
	GROUP BY
		user_name
	`
	
**output：**
huyg2 18553


SQL query screenshot:
![oci8](https://cloud.githubusercontent.com/assets/13047389/9897841/c12ef8ae-5c7f-11e5-9419-ab49e8e443ca.png)

**Comment by mattn** [comment]
show me DDL too please

**Comment by huyg** [comment]
CREATE TABLE "TESTDB"."JOB_ACCOUNTING" 
   (	"TIME_STAMP" DATE NOT NULL ENABLE, 
	"CLUSTER_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"JOB_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(256) NOT NULL ENABLE, 
	"QUEUE_NAME" VARCHAR2(256) NOT NULL ENABLE, 
	"APPLICATION_TAG" VARCHAR2(128), 
	"PROJECT_NAME" VARCHAR2(4000) DEFAULT '-', 
	"START_TIME" TIMESTAMP (6), 
	"RUN_TIME" NUMBER, 
	"END_TIME" TIMESTAMP (6), 
	"NUM_PROCESSORS" NUMBER, 
	"EXIT_STATUS" NUMBER, 
	"INSERT_REQ" NUMBER, 
	 CONSTRAINT "PK_JOB_ACCOUNTING" PRIMARY KEY ("TIME_STAMP", "USER_NAME", "QUEUE_NAME", "CLUSTER_NAME", "JOB_ID", "END_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 20971520 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "PA_DATA_2"  ENABLE
   )

**Comment by mattn** [comment]
Could you please try in latest go-oci8?

**Comment by huyg** [comment]
I have tried the latest go-oci8, 
delete the old go-oci8.a, and have a refresh build,
but still not work.

**Comment by mattn** [comment]
really? i confirmed fixing this issue.

**Comment by huyg** [comment]
Yes, I ensured the codes, still not work.

**Comment by mattn** [comment]
go get -u -x github.com/mattn/go-oci8

**Comment by huyg** [comment]
my server can not visit  internet, so I just downloaded the newest oci8.go and replace the old one. I checked the code, it's the newest which you updated yesterday  night.

**Comment by mattn** [comment]
what is the version of oracle do you use?

**Comment by huyg** [comment]
10.2.0.1.0 oracle DB server
instantclient_12_1

**Comment by mattn** [comment]
Hmm, I'm trying on OracleXE

**Comment by huyg** [comment]
So, is it the Oracle DB version difference ?

**Comment by mattn** [comment]
not believable

**Comment by huyg** [comment]
now I use 
CAST (sum(run_time) AS NUMERIC(10,4)) sum
to avoid that problem.
Thanks for your help!

**Comment by mattn** [comment]
okay, but please don't close this issue.

**Comment by huyg** [comment]
this problem fix by [https://github.com/mattn/go-oci8/pull/71](url)

**Comment by mattn** [comment]
okay. thanks.
