### ISSUE TITLE
SQL NULL column results the rest of fileds get nil 

### ISSUE THREAD

**Issue by wonsikin** [mattn/go-oci8#69]
Hello, I got a bug!!!
run SQL script result:
![2015-09-21 11 39 31](https://cloud.githubusercontent.com/assets/6659426/9984979/79527f0e-6055-11e5-9fff-5b8b1744c219.png)

fetch data using golang, result is: 

``` shell
#0: item is &{UpdateTime:2015-09-21 10:25:40.095772 +0800 CST InsCode:00000002 ChanCode:434653 TransAmt:0.2 RespCode:00 TransCode:PCR RevFlag:0 ProcessFlag:0 TraceNum:403995 MerCode:000000000000030 TermId:00000001 RespCodeClass:0 TransTypeClass:0}

#1: item is &{UpdateTime:2015-09-21 10:27:26.195695 +0800 CST InsCode:00000002 ChanCode: TransAmt:0 RespCode: TransCode: RevFlag: ProcessFlag: TraceNum: MerCode: TermId: RespCodeClass:0 TransTypeClass:0}
```

The `CHANCODE` in the second row is NULL,which results the rest of fields get `nil`.

**Comment by mattn** [comment]
please show me your code.

**Comment by ricsmania** [comment]
Are you using sql.NullInt? If not, that's the problem.

**Comment by wonsikin** [comment]
@ricsmania You are right. Thanks.
@mattn My old code is following:
```golang
for rows.Next() {
		var tr model.Trans
		err = rows.Scan(&tr.UpdateTime, &tr.InsCode, &tr.ChanCode, &tr.TransAmt, &tr.RespCode, &tr.TransCode, &tr.RevFlag, &tr.ProcessFlag, &tr.TraceNum, &tr.MerCode, &tr.TermId)
		results = append(results, &tr)
	}
```
and model.Trans is 
```golang
type Trans struct {
    UpdateTime  time.Time `json:"updateTime"`
    InsCode     string    `json:"insCode"` 
    ChanCode    string    `json:"chanCode"`
    TransAmt    float64   `json:"transAmt"` 
    ...
}
```
I scan the rows and put the values into the struct straightly.After using the sql.NullString, the bug is disappeared.

**Comment by mattn** [comment]
Then use NullString instead of string.

https://golang.org/pkg/database/sql/#NullString

go's string can't express nil.
