### ISSUE TITLE
ORA-01756 error

### ISSUE THREAD

**Issue by zapark** [mattn/go-oci8#7]
I get a oracle error "ORA-01756" when I insert into the table with Chinese string use the example.For example:
_, err = db.Exec("insert into foo values('你好我')")

But the following statement can be executed successful:
_, err = db.Exec("insert into foo values('你好你好你好你好你好你好你好你好你好你好你好你好')")

Like this has a same problem:
_, err = db.Exec("insert into foo values('你好你好你好你好你好你好你好你好你好你好你好中')")

That will be generated a "ORA-01756" if it has more than two Chinese strings in this statement.And some Chinese strings is no problem when I append them after the variable in this statement.
Another question: I can not get the Chinese unicode to query from database after insert into the table.The column results like "浣犲ソ浣犲ソ浣犲ソ浣犲ソ浣犲ソ".

**Comment by mattn** [comment]
What is your NLSLANG?

**Comment by mattn** [comment]
too old

**Comment by Arthur2e5** [comment]
你好 in UTF-8 re-interpreted in GB encodings result in the string posted. Just saw this at https://twitter.com/FakeUnicode/status/730482357019377664 and wow there is even a GitHub issue about this.
