### ISSUE TITLE
Remove dependency on pkg-config?

### ISSUE THREAD

**Issue by MichaelS11** [mattn/go-oci8#70]
Greetings,

Any thought about removing the dependency on pkg-config?

Found if removed the line #cgo pkg-config: oci8 in the file oci8.go and then set the CGO_CFLAGS and CGO_LDFLAGS environmental settings, it seems to work just fine.

For Windows, my settings where:

set CGO_CFLAGS=-IC:\app\instantclient_11_2_64\sdk\include\
set CGO_LDFLAGS=-LC:\app\instantclient_11_2_64\sdk\lib\msvc\ -lstdc++ -loci

Best regards,

Michael

**Comment by mattn** [comment]
It's your paths. I'm not. And many people doesn't use windows.

**Comment by MichaelS11** [comment]
Can set the environmental for Mac and Linux as well, was just showing Windows as an example.

**Comment by mattn** [comment]
I'm thinking pkg-config is a good for separate the issue of go-oci8 and the user's mistake of configuration for oci8 library. And user should set the CGO_CFLAGS in everytime when want to build go-oci8.

**Comment by MichaelS11** [comment]
Got ya, thanks :)
