### ISSUE TITLE
Compile issue on OSX Yosemite

### ISSUE THREAD

**Issue by alperkose** [mattn/go-oci8#72]
I am getting the following error when I try to build the package in Mac (Yosemite)
     
     akose@euakose ~/d/g/s/g/m/go-oci8> go build
     # github.com/mattn/go-oci8
     ./oci8.go:19:39: warning: passing 'char [1024]' to parameter of type 'OraText *' (aka 'unsigned char *') converts between pointers to integer types with different sign [-Wpointer-sign]
     /opt/oracle/instantclient_11_2/sdk/include/ociap.h:7266:48: note: passing argument to parameter 'bufp' here

pkg-config file is:

    includedir=/opt/oracle/instantclient_11_2/sdk/include
    libdir=/opt/oracle/instantclient_11_2/

    Name: OCI
    Description: Oracle Instant Client
    Version: 11.2
    Cflags: -I${includedir}
    Libs.private:
    Libs: -L${libdir} -lclntsh

Go version:

    go version go1.5.1 darwin/amd64

gcc & clang version :

    akose@euakose ~/d/g/s/g/m/go-oci8> gcc --version
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 7.0.0 (clang-700.1.76)
    Target: x86_64-apple-darwin14.5.0
    Thread model: posix

    akose@euakose ~/d/g/s/g/m/go-oci8> clang --version
    Apple LLVM version 7.0.0 (clang-700.1.76)
    Target: x86_64-apple-darwin14.5.0
    Thread model: posix

Can someone help me with the issue?
I tried :
- https://github.com/mattn/go-oci8/issues/15

**Comment by DunesUnLimited** [comment]
Its a warning, does it really fail?
Oratext is an unsigned char,  the default sign of a char is not guaranteed.
On most platforms chars are unsigned, but apparently on yours its signed,

Can you try if making the buffer for the error text explicitly unsigned (on line 11) solves the issue?
typedef struct {
  unsigned char err[1024];
  sword rv;
} retErr;

**Comment by alperkose** [comment]
I took another view to the issue after your response. i guess this warning was overlapped with some other error that I was having due to the docker instance that the Oracle server was running.

**Comment by asaf** [comment]
Hey, I'm getting same error in Sierra,

It works, but it's annoying to see this error everywhere,

```
vendor/github.com/mattn/go-oci8/oci8.go:201:44: warning: passing 'char [9]' to parameter of type 'const oratext *' (aka 'const unsigned char *') converts between pointers to integer types with different sign [-Wpointer-sign]

/Users/user/data/apps/instantclient_12_1/sdk/include/ociap.h:8549:56: note: passing argument to parameter 'name' here
```

Any clue how to shit this off?

Thanks
