### ISSUE TITLE
How do I compile this on windows

### ISSUE THREAD

**Issue by ugurozgen** [mattn/go-oci8#74]
I read this document and other documents but can't find exact solution for using oracle with golang.

When i build my go file it stops due to: 
# pkg-config --cflags oci8
pkg-config: exec: "pkg-config": executable file not found in %PATH%

I have some gaps in my mind about this document can anybody help me? 
1- Should i install pkg-config for windows? 
2- Should i set environment variables for oci8.pc
3- Is my oci8.pc file true?
<-- oci8.pc file -->
prefix=C:/instantclient
libdir=${prefix}
includedir=${prefix}/sdk/include/

Name: OCI
Description: Oracle database engine
Version: 11.2
Libs: -L${libdir} -lclntsh
Libs.private: 
Cflags: -I${includedir}

fmt.Println("THANK YOU")

**Comment by mattn** [comment]
> Should i install pkg-config for windows? 

Yes.

**Comment by vijayks040** [comment]
how to install pkg-config for windows without any errors again

**Comment by mattn** [comment]
I don't know what is best way to install pkg-config.exe. I use pkg-config bundled on msys2.

**Comment by vijayks040** [comment]
i did installed pkg-config and set path in environment varaibles also still getting error 
 >go get github.com/mattn/go-oci8
pkg-config --cflags oci8
pkg-config: exit status 3221225781

**Comment by mattn** [comment]
What output from  `pkg-config --cflags oci8` on console ?

**Comment by vijayks040** [comment]
when i tried pkg-config --cflags oci8 in console a system error popped up saying
The code execution cannot proceed because libglib-2.0-0.dl was not found
![image](https://user-images.githubusercontent.com/10988777/29963901-03c9f8be-8f26-11e7-91ce-1af70499b71a.png)

**Comment by mattn** [comment]
As far as I can see, your installation seems not be completed.

**Comment by vijayks040** [comment]
then how am i getting this error, please help me out to solve this

**Comment by mattn** [comment]
Sorry, I can't. It is not issue of go-sqlite3.

**Comment by vijayks040** [comment]
where should be this libglib-2.0-0.dl in folder structure

**Comment by mattn** [comment]
I'm not sure but probably, it should be same directory, or add the path into %PATH%.

**Comment by vijayks040** [comment]
okay i added the path then in tried itseems there's no no error
C:\Users\vijay>pkg-config --cflags oci8
-IC:instantclient_12_2sdkinclude -IC:mingw64libgccx86_64-w64-mingw327.1.0include
But again when i tried
C:\Users\vijay>go get github.com/mattn/go-oci8
# github.com/mattn/go-oci8
F:\SEARCHBLOX\searchblox\src\github.com\mattn\go-oci8\oci8.go:4:10: fatal error: oci.h: No such file or directory
 #include <oci.h>
          ^~~~~~~
compilation terminated.
![image](https://user-images.githubusercontent.com/10988777/29964753-bc20eeac-8f28-11e7-8b12-c55bafa7fd9b.png)

**Comment by mattn** [comment]
Maybe your path to oracle instant client is separated with `\`. try to replace path-separator to `/` or escape backslash double `\\`.

**Comment by vijayks040** [comment]
its not accepting / onstead of \ 
![image](https://user-images.githubusercontent.com/10988777/29965013-a29c43a4-8f29-11e7-8984-67b9eb9a3ac3.png)

**Comment by vijayks040** [comment]
i tried changing slashes in oci8.pc from forward to backward and i got an different error please see image for the error
![image](https://user-images.githubusercontent.com/10988777/29972393-9a21128e-8f49-11e7-881d-6d67ebd9cb92.png)

**Comment by mattn** [comment]
It's not my go-sqlite3. please file issue to gopkg.in/rana/ora.v4

**Comment by vijayks040** [comment]
even for github.com/mattn/go-oci8 i get same error

**Comment by mattn** [comment]
your oci8.pc seems wrong.

**Comment by vijayks040** [comment]
below is my oci8.pc
prefix=/devel/target/1.0
exec_prefix=${prefix}
oralib=C:\instantclient_12_2\sdk\lib\msvc
orainclude=C:\instantclient_12_2\sdk\include
gcclib=C:\mingw64\lib
gccinclude=C:\mingw64\include
glib_genmarshal=glib-genmarshal
gobject_query=gobject-query
glib_mkenums=glib-mkenums

Name: oci8
Version: 12.2
Description: oci8 library
Libs: -L${oralib} -L${gcclib} -loci
Libs.private: 
Cflags: -I${orainclude} -I${gccinclude}

**Comment by mattn** [comment]
What you see with `go get -x github.com/mattn/go-oci8`?

**Comment by vijayks040** [comment]
i get this when i do go get -x github.com/mattn/go-oci8
pkg-config --cflags oci8
pkg-config --libs oci8
CGO_LDFLAGS="C:\\instantclient_12_2\\sdk\\lib\\msvc" "-LC:instantclient_12_2sdklibmsvc" "-LC:mingw64lib" "-loci" "C:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "C:\\Users\\vijay\\AppData\\Local\\Temp\\go-build572941470\\github.com\\mattn\\go-oci8\\_obj\\" -importpath github.com/mattn/go-oci8 -- -IC:instantclient_12_2sdkinclude -IC:mingw64include -I "C:\\Users\\vijay\\AppData\\Local\\Temp\\go-build572941470\\github.com\\mattn\\go-oci8\\_obj\\" "C:\\instantclient_12_2\\sdk\\include" oci8.go
# github.com/mattn/go-oci8
F:\SEARCHBLOX\searchblox\src\github.com\mattn\go-oci8\oci8.go:4:10: fatal error: oci.h: No such file or directory
 #include <oci.h>
          ^~~~~~~
compilation terminated.

**Comment by mattn** [comment]
As far as I can see, your oci8.pc is escaped with backslash not slash. Also valid for CGO_LDFLAGS. CGO_LDFLAGS should be LDFLAGS. Sorry I don't have enough time to answer your question.

**Comment by vijayks040** [comment]
can you suggest right env path set or right oci8.pc

**Comment by vijayks040** [comment]
@mattn even i changed CGO_LDFLAGS to only LDFLAGS but still its same please suggest

**Comment by mattn** [comment]
maybe this issue can be your help

https://github.com/mattn/go-oci8/issues/172

https://github.com/mattn/go-oci8/issues/152

**Comment by vijayks040** [comment]
@mattn both the problem are for linux, mine is windows 64 machine

**Comment by mattn** [comment]
You still not modify oci8.pc correctly.

**Comment by vijayks040** [comment]
@mattn 
prefix=/devel/target/1.0
exec_prefix=${prefix}
oralib=C:\Instantclient_12_2\sdk\lib\msvc
orainclude=C:\Instantclient_12_2\sdk\include
gcclib=C:\Mingw64\lib
gccinclude=C:\Mingw64\include
glib_genmarshal=glib-genmarshal
gobject_query=gobject-query
glib_mkenums=glib-mkenums

Name: oci8
Version: 12.2
Description: oci8 library
Libs: -L${oralib} -L${gcclib} -loci
Libs.private: 
Cflags: -I${orainclude} -I${gccinclude}
see its already loci in my oci8

**Comment by mattn** [comment]
By the way, you should lie better.

![](https://go-gyazo.appspot.com/ffe933dc057dabd4.png)

**Comment by vijayks040** [comment]
since i could do not do it in windows i tried in linux it worked but when i cross compiled , it crashed in windows, i need this to be working in windows. dont mind

**Comment by vijayks040** [comment]
@mattn i am working on this oracle connection using go in windows for days, kindly help

**Comment by mattn** [comment]
I don't have enough time to answer for each your small questions.

**Comment by vijayks040** [comment]
@mattn  sorry one last question is this one please suggest fatal error: oci.h: No such file or directory
#include <oci.h>
^~~~~~~
compilation terminated.

**Comment by mattn** [comment]
try following oci8.pc

```
prefix=/devel/target/1.0
exec_prefix=${prefix}
oralib=C:/Instantclient_12_2/sdk/lib/msvc
orainclude=C:/Instantclient_12_2/sdk/include
gcclib=C:/Mingw64/lib
gccinclude=C:/Mingw64/include

Name: oci8
Version: 12.2
Description: oci8 library
Libs: -L${oralib} -L${gcclib} -loci
Libs.private:
Cflags: -I${orainclude} -I${gccinclude}
```

**Comment by vijayks040** [comment]
@mattn  okay, 
>go get github.com/mattn/go-oci8
# github.com/mattn/go-oci8
gcc: warning: C:\Instantclient_12_2\sdk\include: linker input file unused because linking not done
# github.com/mattn/go-oci8
gcc: warning: C:\Instantclient_12_2\sdk\include: linker input file unused because linking not done
# github.com/mattn/go-oci8
gcc: warning: C:\Instantclient_12_2\sdk\include: linker input file unused because linking not done
# github.com/mattn/go-oci8
C:/Mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Instantclient_12_2\sdk\lib\msvc: Permission denied
collect2.exe: error: ld returned 1 exit status

**Comment by mattn** [comment]
You don't modify oci8.pc correctly. I replaced all of backslash into slash. in oci8.pc .

**Comment by vijayks040** [comment]
yes i replaced all the backslash into slash in my oci8.pc

**Comment by mattn** [comment]
`go build -x` on directory go-oci8

**Comment by vijayks040** [comment]
here you go with the image 
![image](https://user-images.githubusercontent.com/10988777/30059785-2ccab768-925e-11e7-93be-5f17831f0947.png)

**Comment by mattn** [comment]
make sure what output of `pkg-config --cflags oci8` and `pkg-config --libs oci8`.

Below is oci8.pc i use.
```
prefix=c:/instantclient_12_2
includedir="c:/instantclient_12_2/sdk/include"
libdir="c:/instantclient_12_2/sdk/lib/msvc"

Name: oci8
Description: Oracle Instant Client
Version: 12.2
Cflags: -I${includedir}
Libs: -L${libdir} -loci
```

**Comment by mattn** [comment]
![fc0e3478ec528e1b](https://user-images.githubusercontent.com/10111/30059983-62a8ea8a-927c-11e7-8ab6-4d9ca0c0c66a.png)

This `C:\\InstantClient_12_2\\SDK\\lib\\msvc` is not have flag `-L`.

**Comment by vijayks040** [comment]
@mattn i changed some env variables and then tried 
![image](https://user-images.githubusercontent.com/10988777/30060320-80a8d002-9260-11e7-88b2-62031f8e1f50.png)

**Comment by vijayks040** [comment]
thanks for the patience @mattn

**Comment by novalagung** [comment]
@vijayks040 Hi vijay, can you please share your finalized `oci8.pc`. I still stuck at `gcc: warning: C:\Instantclient_12_2\sdk\include: linker input file unused because linking not done` error. Thank you.

**Comment by MichaelS11** [comment]
@novalagung I would suggest looking at some of the newer closed issues.

**Comment by novalagung** [comment]
@MichaelS11 This is the only issue I found after I search using `linker input file unused because linking not done` keyword. anyway I'll try to take a look at newer closed issues. Thank you

**Comment by ilovejs** [comment]
> I don't know what is best way to install pkg-config.exe. I use pkg-config bundled on msys2.

pacman -S pkg-config

**Comment by mattn** [comment]
I understand it. I just mean that I don't know what is easy way for everyone who does not install msys2.

**Comment by mattn** [comment]
One easy way to install pkg-config on Windows is:
```
go get github.com/mattn/pkg-gonfig/pkg-config
```

**Comment by novalagung** [comment]
probably very late to post but might be useful.

I'm able to get rid of this error `linker input file unused because linking not done` by ensuring these environment variables are set.

```bash
setx CGO_CFLAGS "-IC:\OtherPrograms\Oracle\instantclient_12_2\sdk\include"
setx CGO_LDFLAGS "-LC:\OtherPrograms\Oracle\instantclient_12_2 -loci"
setx PKG_CONFIG_PATH "C:\msys64\mingw64\lib\pkgconfig\oci8.pc"
```
