### ISSUE TITLE
Go 1.6beta1 - Changes to CGO pointer passing break (https://github.com/golang/go/issues/12416)

### ISSUE THREAD

**Issue by Son-Lam** [mattn/go-oci8#77]
Hello mattn,

We are experimenting with go1.6beta1 and got error as they are going to tighten the pointer passing between C and Golang.

Could you have to see if you can help to fix.

Best Regards,

2016/01/20 10:56:47 http: panic serving [::1]:42213: runtime error: cgo argument has Go pointer to Go pointer
goroutine 34 [running]:
net/http.(_conn).serve.func1(0xc8200f0000)
    /usr/local/go/src/net/http/server.go:1382 +0xc1
github.com/mattn/go-oci8._cgoCheckPointer0(0x70a920, 0xc820116260, 0xc82000a200, 0x1, 0x1, 0x0)
    ??:0 +0x56
github.com/mattn/go-oci8.(_OCI8Stmt).Query(0xc8200104e0, 0xc16e38, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /opt/local/golang/src/github.com/mattn/go-oci8/oci8.go:1070 +0x1e4e
database/sql.rowsiFromStatement(0x7f75dbe8d1f0, 0xc8200141c0, 0x7f75dbe8d1b0, 0xc8200104e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/database/sql/sql.go:1655 +0x3ba
database/sql.(_DB).queryConn(0xc820118000, 0xc8200141c0, 0xc82000a1e0, 0xc82011a240, 0x111, 0x0, 0x0, 0x0, 0x8084a0, 0x0, ...)
    /usr/local/go/src/database/sql/sql.go:1119 +0x48b
database/sql.(_DB).query(0xc820118000, 0xc82011a240, 0x111, 0x0, 0x0, 0x0, 0xc82004d601, 0x1, 0x0, 0x0)
    /usr/local/go/src/database/sql/sql.go:1079 +0x126
database/sql.(_DB).Query(0xc820118000, 0xc82011a240, 0x111, 0x0, 0x0, 0x0, 0x111, 0x0, 0x0)
    /usr/local/go/src/database/sql/sql.go:1062 +0xa3
sparq-api/serialized_unit/controllers.SerializedUnitController.GetSerializedUnitStatus(0x7f75dbe8d080, 0xc82010e000, 0xc8201060e0, 0xc820016240, 0x2, 0x2)
    /home/plc-solam/workspace.solam/sparq-stash/misc/sparq_api_httprouter/src/sparq-api/serialized_unit/controllers/serialized_unit.go:54 +0x827
sparq-api/serialized_unit/controllers.(SerializedUnitController).GetSerializedUnitStatus-fm(0x7f75dbe8d080, 0xc82010e000, 0xc8201060e0, 0xc820016240, 0x2, 0x2)
    /home/plc-solam/workspace.solam/sparq-stash/misc/sparq_api_httprouter/src/sparq-api/sparq-api.go:20 +0x6a
github.com/julienschmidt/httprouter.(_Router).ServeHTTP(0xc82006c340, 0x7f75dbe8d080, 0xc82010e000, 0xc8201060e0)
    /opt/local/golang/src/github.com/julienschmidt/httprouter/router.go:299 +0x228
net/http.serverHandler.ServeHTTP(0xc820088380, 0x7f75dbe8d080, 0xc82010e000, 0xc8201060e0)
    /usr/local/go/src/net/http/server.go:2068 +0x19e
net/http.(_conn).serve(0xc8200f0000)
    /usr/local/go/src/net/http/server.go:1465 +0xf2e
created by net/http.(_Server).Serve
    /usr/local/go/src/net/http/server.go:2124 +0x44e
connect to source database
SELECT P.description AS PART_DESC,
                                  WSNO.WIPSERIALSTATUS AS STATUS
                             FROM WIP_SERIAL_NO WSNO INNER JOIN PRODUCT P
                               ON P.ID = WSNO.PRODUCTID
                            WHERE P.productno = '1009830-00-A' and WSNO.serialno = '5YJSA1AC0DFP10592'
2016/01/20 10:56:47 http: panic serving [::1]:42214: runtime error: cgo argument has Go pointer to Go pointer
goroutine 35 [running]:
net/http.(_conn).serve.func1(0xc8200f0080)
    /usr/local/go/src/net/http/server.go:1382 +0xc1
github.com/mattn/go-oci8._cgoCheckPointer0(0x70a920, 0xc8201164a0, 0xc82000a360, 0x1, 0x1, 0x0)
    ??:0 +0x56
github.com/mattn/go-oci8.(_OCI8Stmt).Query(0xc820010750, 0xc16e38, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /opt/local/golang/src/github.com/mattn/go-oci8/oci8.go:1070 +0x1e4e
database/sql.rowsiFromStatement(0x7f75dbe8d1f0, 0xc8200142a0, 0x7f75dbe8d1b0, 0xc820010750, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/database/sql/sql.go:1655 +0x3ba
database/sql.(_DB).queryConn(0xc8201180b0, 0xc8200142a0, 0xc82000a340, 0xc82011a480, 0x111, 0x0, 0x0, 0x0, 0x8084a0, 0x0, ...)
    /usr/local/go/src/database/sql/sql.go:1119 +0x48b
database/sql.(_DB).query(0xc8201180b0, 0xc82011a480, 0x111, 0x0, 0x0, 0x0, 0xc82004d601, 0x1, 0x0, 0x0)
    /usr/local/go/src/database/sql/sql.go:1079 +0x126
database/sql.(_DB).Query(0xc8201180b0, 0xc82011a480, 0x111, 0x0, 0x0, 0x0, 0x111, 0x0, 0x0)
    /usr/local/go/src/database/sql/sql.go:1062 +0xa3
sparq-api/serialized_unit/controllers.SerializedUnitController.GetSerializedUnitStatus(0x7f75dbe8d080, 0xc82010e0c0, 0xc820106000, 0xc820016440, 0x2, 0x2)
    /home/plc-solam/workspace.solam/sparq-stash/misc/sparq_api_httprouter/src/sparq-api/serialized_unit/controllers/serialized_unit.go:54 +0x827
sparq-api/serialized_unit/controllers.(SerializedUnitController).GetSerializedUnitStatus-fm(0x7f75dbe8d080, 0xc82010e0c0, 0xc820106000, 0xc820016440, 0x2, 0x2)
    /home/plc-solam/workspace.solam/sparq-stash/misc/sparq_api_httprouter/src/sparq-api/sparq-api.go:20 +0x6a
github.com/julienschmidt/httprouter.(_Router).ServeHTTP(0xc82006c340, 0x7f75dbe8d080, 0xc82010e0c0, 0xc820106000)
    /opt/local/golang/src/github.com/julienschmidt/httprouter/router.go:299 +0x228
net/http.serverHandler.ServeHTTP(0xc820088380, 0x7f75dbe8d080, 0xc82010e0c0, 0xc820106000)
    /usr/local/go/src/net/http/server.go:2068 +0x19e
net/http.(_conn).serve(0xc8200f0080)
    /usr/local/go/src/net/http/server.go:1465 +0xf2e
created by net/http.(_Server).Serve
    /usr/local/go/src/net/http/server.go:2124 +0x44e
connect to source database
SELECT P.description AS PART_DESC,
                                  WSNO.WIPSERIALSTATUS AS STATUS
                             FROM WIP_SERIAL_NO WSNO INNER JOIN PRODUCT P
                               ON P.ID = WSNO.PRODUCTID
                            WHERE P.productno = '1009830-00-A' and WSNO.serialno = '5YJSA1AC0DFP10592'
2016/01/20 10:56:47 http: panic serving [::1]:42217: runtime error: cgo argument has Go pointer to Go pointer
goroutine 19 [running]:
net/http.(_conn).serve.func1(0xc820088400)
    /usr/local/go/src/net/http/server.go:1382 +0xc1
github.com/mattn/go-oci8._cgoCheckPointer0(0x70a920, 0xc820116500, 0xc82000a450, 0x1, 0x1, 0x0)
    ??:0 +0x56
github.com/mattn/go-oci8.(_OCI8Stmt).Query(0xc820010810, 0xc16e38, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /opt/local/golang/src/github.com/mattn/go-oci8/oci8.go:1070 +0x1e4e
database/sql.rowsiFromStatement(0x7f75dbe8d1f0, 0xc820014310, 0x7f75dbe8d1b0, 0xc820010810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/database/sql/sql.go:1655 +0x3ba
database/sql.(_DB).queryConn(0xc8200dc2c0, 0xc820014310, 0xc82000a430, 0xc82011a5a0, 0x111, 0x0, 0x0, 0x0, 0x8084a0, 0x0, ...)
    /usr/local/go/src/database/sql/sql.go:1119 +0x48b
database/sql.(_DB).query(0xc8200dc2c0, 0xc82011a5a0, 0x111, 0x0, 0x0, 0x0, 0xc820047601, 0x1, 0x0, 0x0)
    /usr/local/go/src/database/sql/sql.go:1079 +0x126
database/sql.(_DB).Query(0xc8200dc2c0, 0xc82011a5a0, 0x111, 0x0, 0x0, 0x0, 0x111, 0x0, 0x0)
    /usr/local/go/src/database/sql/sql.go:1062 +0xa3
sparq-api/serialized_unit/controllers.SerializedUnitController.GetSerializedUnitStatus(0x7f75dbe8d080, 0xc82016a000, 0xc820168000, 0xc82006c580, 0x2, 0x2)
    /home/plc-solam/workspace.solam/sparq-stash/misc/sparq_api_httprouter/src/sparq-api/serialized_unit/controllers/serialized_unit.go:54 +0x827
sparq-api/serialized_unit/controllers.(SerializedUnitController).GetSerializedUnitStatus-fm(0x7f75dbe8d080, 0xc82016a000, 0xc820168000, 0xc82006c580, 0x2, 0x2)
    /home/plc-solam/workspace.solam/sparq-stash/misc/sparq_api_httprouter/src/sparq-api/sparq-api.go:20 +0x6a
github.com/julienschmidt/httprouter.(_Router).ServeHTTP(0xc82006c340, 0x7f75dbe8d080, 0xc82016a000, 0xc820168000)
    /opt/local/golang/src/github.com/julienschmidt/httprouter/router.go:299 +0x228
net/http.serverHandler.ServeHTTP(0xc820088380, 0x7f75dbe8d080, 0xc82016a000, 0xc820168000)
    /usr/local/go/src/net/http/server.go:2068 +0x19e
net/http.(_conn).serve(0xc820088400)
    /usr/local/go/src/net/http/server.go:1465 +0xf2e
created by net/http.(_Server).Serve
    /usr/local/go/src/net/http/server.go:2124 +0x44e

**Comment by mattn** [comment]
should be fixied in https://github.com/mattn/go-oci8/commit/851c695dcffeaf834c5f26b44e74e06c576d9957

do you use latest?

**Comment by Son-Lam** [comment]
Hi mattn,

Thank you so much for the prompt reply.

I tried to get the latest but I got this error (go1.6beta2):

go get github.com/mattn/go-oci8
# cd .; git -C /opt/local/golang/src/github.com/mattn/go-oci8 submodule update --init --recursive
Unknown option: -C
usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
           [-p|--paginate|--no-pager] [--no-replace-objects]
           [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
           [--help] COMMAND [ARGS]
package github.com/mattn/go-oci8: exit status 129

Could you help.

Best Regards,

Son Lam.

**Comment by mattn** [comment]
it's not problem of go-oci8. please remove go-oci8 directory in $GOPATH. and do "go get" again please.

**Comment by Son-Lam** [comment]
Hi mattn,

I got it working.

Thanks so much for your help.

Thanks,

**Comment by MichaelS11** [comment]
@mattn 
Close this?
