### ISSUE TITLE
LastInsertId  oracle 12C

### ISSUE THREAD

**Issue by akarmakar** [mattn/go-oci8#78]
I am getting Error "LastInsertId not supported" for identity insert in oracle 12C. Am i doing some thing wrong or this is not yet implemented .

**Comment by mattn** [comment]
currently, not supported. because it's not possible to get with APIs. to get LastInsertId, it should modify all of SQL to do RETURNING.

```sql
INSERT INTO .... RETURNING C1 INTO :C1
```

**Comment by goloveychuk** [comment]
@mattn but after having 
```sql
INSERT INTO .... RETURNING C1 INTO :C1
```
how to catch that value.
Already tried `db.QueryRow().Scan(&id)`, tried to bind &id in args.

**Comment by dddpaul** [comment]
```res, err := stmt.Exec(&id)``` do not work either. 

@mattn, is there a proper way to fetch last insert id?

**Comment by mattn** [comment]
Now supported LastInsertId.

https://github.com/mattn/go-oci8/commit/b4f440d002b6694ccf019f4ea7368e61ef2c1d30

**Comment by dddpaul** [comment]
I'm getting something like:

```
strconv.ParseInt: parsing "41414157646a41414241414159483541414100": value out of range
```

when running _example/lastinsertid/main.go.

Checked on Oracle 11g and Oracle 12c XE.

**Comment by mattn** [comment]
Sorry, I reverted last change. Now should be work. However you need to note the lastinsertid is not consistent value. if you want to get real last insert id, need to call GetLastInsertId().

**Comment by dddpaul** [comment]
@mattn, thanks. I've able to fetch LastInsertId now.

I can use returning value in other selects from sqlplus, for example, like:

```
SELECT * FROM lastinsertid_example WHERE ROWID = 'AAAE5GAABAAAKhBAAA';
```

Also I've tried to run this query in Go program (in fact, I've just appended this to _example/lastinsertid/main.go):
```
...
rowID := oci8.GetLastInsertId(lastInsertId)
var id string
db.QueryRow("select id from lastinsertid_example where rowid = :1", rowID).Scan(id)
println(id)
```

And I'm getting error here - ```ORA-01410: invalid ROWID```. Is this error cause in your driver or in ROWID mechanism nature?

**Comment by mattn** [comment]
should be fixed.

**Comment by dddpaul** [comment]
Thanks, works like a charm now.

**Comment by yzwlcc** [comment]
it must have to call oci8.GetLastInsertId()?
why not just write the insertid into res.LastInsertId()...

thx
