### ISSUE TITLE
finally got it installed on windows 64

### ISSUE THREAD

**Issue by libliflin** [mattn/go-oci8#79]
No idea if all this was necessary, but it's what got it working for me. 

Local Oracle XE; Windows server 2012; both 64 bit.

1. go to msys2.github.io and follow instructions.
2. install go 1.6
2. uninstall git for windows
3. open msys.bat and do
3. pacman -S git
4. git config username
5. pacman -S mingw-w64-x86_64-gcc
6. close msys and open up mingw64
7. open up oraclexe\app\oracle\product\11.2.0\server\oci\include\oratypes.h and change line 230 to be
8. `#define _int64 __int64`
9. go get -u github.com/mattn/go-oci8
10. cd into example (in the mingw64.bat)
11. export GO_OCI8_CONNECT_STRING=connectionstring
12. go run example.go
13. cry that you can't use output parameters of stored procedures.

**Comment by ricsmania** [comment]
@libliflin about item 15, go-oci8 was built to support standard SQL through the database/sql package, so it doesn't support specific Oracle features like out params. If you need those, I suggest you take a look of other drivers like [Rana](https://github.com/rana/ora).

But keep in mind that it is much slower than go-oci8. But you can use both on the same application, and then use the most appropriate driver for each task.

**Comment by mahaben** [comment]
@libliflin 
Did you get the following error when you added "#define _int64 __int64" to oratypes.h?

c:/oraclexe/app/oracle/product/11.2.0/server/oci/lib/msvc/oci.lib: error adding
symbols: File in wrong format
collect2.exe: error: ld returned 1 exit status

Thanks,

**Comment by libliflin** [comment]
I don't have access to that machine anymore; and I don't remember because it's been a year.  I do remember a lot of fiddling around to get the magic linker to work; the file had the wrong libraries in it. But i don't remember anything more than that. Sorry!
