### ISSUE TITLE
ORACLE type SYS_REFCURSOR 

### ISSUE THREAD

**Issue by x0d3r** [mattn/go-oci8#8]
Hello,  there's support for ORACLE type SYS_REFCURSOR  as OUT parameters in a procedure?

**Comment by MichaelS11** [comment]
Does the below PR solve this? If not, can I get an example SQL query?

https://github.com/mattn/go-oci8/pull/383

**Comment by MichaelS11** [comment]
Best that can be done:

https://godoc.org/github.com/mattn/go-oci8#example-package--SqlCursorFunction
