### ISSUE TITLE
Cross compiling go-oci8?

### ISSUE THREAD

**Issue by kylewolfe** [mattn/go-oci8#84]
I'm sure this is probably not related directly to go-oci8, but I'll ask here. I have a simple example project building correctly on Windows x64 (Go 1.6). I'm now looking to cross compile for Linux x64.

```
$ env GOOS=linux go build -v
runtime
errors
math
sync/atomic
unicode/utf8
sort
unicode
sync
io
syscall
bytes
strings
time
os
strconv
reflect
fmt
database/sql/driver
database/sql
github.com/mattn/go-oci8
local/go-ora
```

Moving the resulting binary to Linux, I get the following result:

```
sql: unknown driver "oci8" (forgotten import?)
```

Is cross compilation possible or do I need to rebuild on the target architecture?

**Comment by mattn** [comment]
do you have cross-compiling environment? go-oci8 uses cgo so you must have C compiler for windows. Also pkg-config for windows.

**Comment by ricsmania** [comment]
I never cross compiled from Windows to Linux, but I did compile from Linux to Windows using Docker and it works perfectly.

Did you set the CGO_ENABLED environment variable?

Have you thought about using Docker? It might be a better option. If you are interested this is the Dockerfile I use:

```docker
FROM golang

ADD /instantclient_12_1 /usr/instantclient_12_1

RUN apt-get update
RUN apt-get install -y pkg-config
RUN apt-get install -y libaio1

ADD oci8.pc /usr/lib/pkgconfig/oci8.pc

ENV LD_LIBRARY_PATH /usr/lib:/usr/local/lib:/usr/instantclient_12_1

RUN ln -s /usr/instantclient_12_1/libclntsh.so.12.1 /usr/instantclient_12_1/libclntsh.so
RUN ln -s /usr/instantclient_12_1/libclntshcore.so.12.1 /usr/instantclient_12_1/libclntshcore.so
RUN ln -s /usr/instantclient_12_1/libocci.so.12.1 /usr/instantclient_12_1/libocci.so

RUN go get -u github.com/mattn/go-oci8
```

And oci8.pc:

```
prefix=/usr
includedir=${prefix}/instantclient_12_1/sdk/include
libdir=${prefix}/instantclient_12_1

Name: oci8
Description: Oracle Instant Client
Version: 12.1
Cflags: -I${includedir}
Libs: -L${libdir} -lclntsh
```

In order to build the image you need to download Oracle Instant Client and put it in the instantclient_12_1 folder

**Comment by kylewolfe** [comment]
@mattn, I do have those prereqs fulfilled, and I've built successfully for Windows already.

Thank you @ricsmania. I did not have CGO_ENABLED set. After setting I get the following:

```
$ env GOOS=linux go build -v
runtime
errors
math
sync/atomic
unicode/utf8
sort
unicode
sync
runtime/cgo
io
syscall
# runtime/cgo
C:\Users\wolfek9\AppData\Local\Temp\go-build731452338\runtime\cgo\_obj\_cgo_main.c:1:0: error: -fPIC ignored for target (all code is position independent) [-Werror]
 int main() { return 0; }
 ^
cc1.exe: all warnings being treated as errors
bytes
strings
time
strconv
os
reflect
fmt
database/sql/driver
database/sql
```

Any idea what might be causing this?

**Comment by rof20004** [comment]
@ricsmania How you compile from Linux to Windows, I get the same error today, from Linux to Windows:

```
GOOS=windows GOARCH=amd64 go build
```

The error: sql: unknown driver "oci8" (forgotten import?)

**Comment by vk1818** [comment]
@ricsmania man you are real rockstar i was going crazy with this oci8, thanks it worked

**Comment by rof20004** [comment]
@MichaelS11 Thanks!

**Comment by MichaelS11** [comment]
Welcome :)

**Comment by rof20004** [comment]
@MichaelS11 A question:

With this, I do not need to install instant client to the systems? I mean, the binary generated have all driver needs?

**Comment by MichaelS11** [comment]
When building the program, need either the instant client, full client, or Oracle database on the system.

When running the built program, only need a few items from the Oracle software, but any of the above three should work as well.

For Windows it seem to only need: oci.dll and oraociei11.dll.
For Linux seem to need: glogin.sql, libclntsh.so.11.1, libheteroxa11.so, libnnz11.so, libocci.so.11.1, libociei.so, libocijdbc11.so, libsqlplus.so, libsqlplusic.so, libsqora.so.11.1

**Comment by rof20004** [comment]
@MichaelS11 can you share these guides? Thanks anyway, your solution is better than mine :)

**Comment by MichaelS11** [comment]
When I was looking into it I had just done an internet search. I did not save the results. Here are a couple of links I found just by doing another internet search.

https://stackoverflow.com/questions/38785691/trying-to-build-static-cgo-executable-with-oracle-libraries-on-linux-ubuntu

https://github.com/mattn/go-oci8/issues/102

I am sure there is more information out there that you can find, just would need to spend time looking for it.

**Comment by MichaelS11** [comment]
Welcome :)

**Comment by kylewolfe** [comment]
Closing as Linux -> Windows has been addressed, and I no longer need Windows -> Linux solution.
