### ISSUE TITLE
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

### ISSUE THREAD

**Issue by drewwells** [mattn/go-oci8#88]
I pointed _example/oracle.go to a containerized version of Oracle DB on localhost. This error prevents any sql calls from executing. It appears to be a problem with my DSN. I'm able to connect to this server with Oracle SQLDeveloper and directly to apex/em running on the server. Is there some trick to defining the DSN?

I'm using DSN: `user:pass@localhost:1521/xe`

**Comment by drewwells** [comment]
Seems the magic sauce is to post issues here. The sid was incorrect so connection was failing, problem with the container not oci8.

**Comment by mevric** [comment]
Using Oracle Service Name:-
db, err := sql.Open("ora", "user/password@hostname:1521/serviceName")

Using Oracle SID:-
db, err := sql.Open("ora", "user/password@hostname:1521:SID")

notice the difference between / and : after the port number
/ -> for serviceName
: -> for SID
