### ISSUE TITLE
Cannot return rows when select from views

### ISSUE THREAD

**Issue by lujiacn** [mattn/go-oci8#92]
Hi 
some select statement not work well.
select \* from view_name --> can get colnames, but "rows.Next()" always false, no results
select a,b,c from view_name --> works fine
select \* from a_table --> works fine

Any one meet the same issue?

I am using ubuntux64, go1.6 and oracle instance 11.2

Thanks!

**Comment by MichaelS11** [comment]
@mattn Close this?

I can select from views all the time.
