### ISSUE TITLE
create table statement with param error

### ISSUE THREAD

**Issue by linlexing** [mattn/go-oci8#93]
run:
`db.Exec("create table tmp_1 as(select 1 from dual where 1=:a)", 1)`
return err:
>err: sql: expected 0 arguments, got 1

**Comment by djadala** [comment]
May be this is some optimization by oracle, it actually doesn't use parameter ?

**Comment by mattn** [comment]
go-oci8 does not support named placeholder.

On 4/8/16, Jamil Djadala <notifications@github.com> wrote:
> May be this is some optimization by oracle, it actually doesn't use
> parameter ?
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/go-oci8/issues/93#issuecomment-207223363


-- 
- Yasuhiro Matsumoto

**Comment by djadala** [comment]
yes, it does not support named placeholders, but it support placeholders in order of occurrence, oci8 complain that it expect 0 arguments  ...

**Comment by djadala** [comment]
actually go sql package complays, using info from go-oci8 driver that this sql have 0 arguments/placeholders, and we pass 1 argument.

**Comment by djadala** [comment]
if you call
`db.Exec("create table tmp_1 as(select 1 from dual where 1=:a)")`
, oracle returns:
`ORA-01027: bind variables not allowed for data definition operations`
so this is invalid sql

**Comment by linlexing** [comment]
I understand, **create table as** statement can not use bind parameters, I will use a combination of statements instead. However, the error message is returned if it is clear, will not be confused.

**Comment by djadala** [comment]
unfortunately, oracle does not return error when this sql is prepared, it return error when this is executed, and argument count  check is performed  after prepare and before execute.
btw, where clause in   `create table as`   is useless.
Regards

**Comment by linlexing** [comment]
@djadala 
>btw, where clause in create table as is useless.

Are you sure ? I've tested there is no problem
