### ISSUE TITLE
The performance is defeated by gopkg.in/goracle.v1 (similar as python cx_Oracle)

### ISSUE THREAD

**Issue by yourchanges** [mattn/go-oci8#99]
Hi,

I have write a simple code to fetch the **2000000** rows from table use three golang oracle driver:
- gopkg.in/goracle.v1                  **==> about 22 seconds**
- github.com/mattn/go-oci8        **==> about 34 seconds**
- gopkg.in/rana/ora.v3                **==> about 660 seconds**

(Note：the python cx_Oracle only takes 18 seconds to do the same thing)

**My ENV:**
centos 6.6 64bit
golang 1.5.3

**The code:**

`func FetchData(db *sql.DB) []int {

```
var r []int

sqlstr := `SELECT id FROM xxxx.geolocation`

// Prepare statement for reading data
stmtOut, err := db.Prepare(sqlstr)
checkErr(err)
defer stmtOut.Close()

rows, err := stmtOut.Query()
checkErr(err)

for rows.Next() {
    var id int
    err = rows.Scan(&id)
    checkErr(err)
    r = append(r, id)
}
return r
```

}`

**Comment by drewwells** [comment]
gooracle is discontinued and likely crashes under concurrent loads. If your intention is to improve performance of go-oci8, a benchmark test and sample data would help improve performance of this driver.

**Comment by MichaelS11** [comment]
@mattn Without full benchmark code I think this thread can be closed.

**Comment by mattn** [comment]
If you'll provide full code of benchmark, please reopen this.
